export const localProducts = [
  {
    "name": "FER T",
    "description": "Epaisseur : 2 mm Hauteur : 25 mm Largeur : 25 mm",
    "basePrice": 20,
    "unitPriceExclTax": 20,
    "VATRate": 10,
    "marginPercent": 20,
    "sellingPrice": 26.4,
    "linearWeight": 0.29,
    "thickness": 2,
    "height": 25,
    "width": 25,
    "diameter": null,
    "circumference": null,
    "sectionArea": null,
    "weight": null,
    "matiere": "Aluminium",
    "productCode": 1
  },
  {
    "name": "FER T",
    "description": "Epaisseur : 2 mm Hauteur : 30 mm Largeur : 30 mm",
    "basePrice": 20,
    "unitPriceExclTax": 20,
    "VATRate": 10,
    "marginPercent": 20,
    "sellingPrice": 26.4,
    "linearWeight": 0.34,
    "thickness": 2,
    "height": 30,
    "width": 30,
    "diameter": null,
    "circumference": null,
    "sectionArea": null,
    "weight": null,
    "matiere": "Aluminium",
    "productCode": 2
  },
  {
    "name": "FER T",
    "description": "Epaisseur : 3 mm Hauteur : 30 mm Largeur : 30 mm",
    "basePrice": 20,
    "unitPriceExclTax": 20,
    "VATRate": 10,
    "marginPercent": 20,
    "sellingPrice": 26.4,
    "linearWeight": 0.51,
    "thickness": 3,
    "height": 30,
    "width": 30,
    "diameter": null,
    "circumference": null,
    "sectionArea": null,
    "weight": null,
    "matiere": "Aluminium",
    "productCode": 3
  },
  {
    "name": "FER T",
    "description": "Epaisseur : 3 mm Hauteur : 40 mm Largeur : 40 mm",
    "basePrice": 20,
    "unitPriceExclTax": 20,
    "VATRate": 10,
    "marginPercent": 20,
    "sellingPrice": 26.4,
    "linearWeight": 0.68,
    "thickness": 3,
    "height": 40,
    "width": 40,
    "diameter": null,
    "circumference": null,
    "sectionArea": null,
    "weight": null,
    "matiere": "Aluminium",
    "productCode": 4
  },
  {
    "name": "FER T",
    "description": "Epaisseur : 4 mm Hauteur : 40 mm Largeur : 40 mm",
    "basePrice": 20,
    "unitPriceExclTax": 20,
    "VATRate": 10,
    "marginPercent": 20,
    "sellingPrice": 26.4,
    "linearWeight": 0.9,
    "thickness": 4,
    "height": 40,
    "width": 40,
    "diameter": null,
    "circumference": null,
    "sectionArea": null,
    "weight": null,
    "matiere": "Aluminium",
    "productCode": 5
  },
  {
    "name": "FER T",
    "description": "Epaisseur : 5 mm Hauteur : 50 mm Largeur : 50 mm",
    "basePrice": 20,
    "unitPriceExclTax": 20,
    "VATRate": 10,
    "marginPercent": 20,
    "sellingPrice": 26.4,
    "linearWeight": 1.41,
    "thickness": 5,
    "height": 50,
    "width": 50,
    "diameter": null,
    "circumference": null,
    "sectionArea": null,
    "weight": null,
    "matiere": "Aluminium",
    "productCode": 6
  },
  {
    "name": "FER T",
    "description": "Epaisseur : 6 mm Hauteur : 60 mm Largeur : 60 mm",
    "basePrice": 20,
    "unitPriceExclTax": 20,
    "VATRate": 10,
    "marginPercent": 20,
    "sellingPrice": 26.4,
    "linearWeight": 2.04,
    "thickness": 6,
    "height": 60,
    "width": 60,
    "diameter": null,
    "circumference": null,
    "sectionArea": null,
    "weight": null,
    "matiere": "Aluminium",
    "productCode": 7
  },
  {
    "name": "FER T",
    "description": "Epaisseur : 8 mm Hauteur : 80 mm Largeur : 80 mm",
    "basePrice": 20,
    "unitPriceExclTax": 20,
    "VATRate": 10,
    "marginPercent": 20,
    "sellingPrice": 26.4,
    "linearWeight": 3.61,
    "thickness": 8,
    "height": 80,
    "width": 80,
    "diameter": null,
    "circumference": null,
    "sectionArea": null,
    "weight": null,
    "matiere": "Aluminium",
    "productCode": 8
  },
  {
    "name": "Cornière à ailes égales",
    "description": "Epaisseur : 1.5 mm Hauteur Ailes : 15 mm",
    "basePrice": 20,
    "unitPriceExclTax": 20,
    "VATRate": 10,
    "marginPercent": 20,
    "sellingPrice": 26.4,
    "linearWeight": 0.13,
    "thickness": 1.5,
    "height": 15,
    "width": null,
    "diameter": null,
    "circumference": null,
    "sectionArea": 0,
    "weight": null,
    "matiere": "Aluminium",
    "productCode": 9
  },
  {
    "name": "Cornière à ailes égales",
    "description": "Epaisseur : 2 mm Hauteur Ailes : 15 mm",
    "basePrice": 20,
    "unitPriceExclTax": 20,
    "VATRate": 10,
    "marginPercent": 20,
    "sellingPrice": 26.4,
    "linearWeight": 0.17,
    "thickness": 2,
    "height": 15,
    "width": null,
    "diameter": null,
    "circumference": null,
    "sectionArea": 0,
    "weight": null,
    "matiere": "Aluminium",
    "productCode": 10
  },
  {
    "name": "Cornière à ailes égales",
    "description": "Epaisseur : 1.5 mm Hauteur Ailes : 20 mm",
    "basePrice": 20,
    "unitPriceExclTax": 20,
    "VATRate": 10,
    "marginPercent": 20,
    "sellingPrice": 26.4,
    "linearWeight": 0.18,
    "thickness": 1.5,
    "height": 20,
    "width": null,
    "diameter": null,
    "circumference": null,
    "sectionArea": 0,
    "weight": null,
    "matiere": "Aluminium",
    "productCode": 11
  },
  {
    "name": "Cornière à ailes égales",
    "description": "Epaisseur : 2 mm Hauteur Ailes : 20 mm",
    "basePrice": 20,
    "unitPriceExclTax": 20,
    "VATRate": 10,
    "marginPercent": 20,
    "sellingPrice": 26.4,
    "linearWeight": 0.22,
    "thickness": 2,
    "height": 20,
    "width": null,
    "diameter": null,
    "circumference": null,
    "sectionArea": 0,
    "weight": null,
    "matiere": "Aluminium",
    "productCode": 12
  },
  {
    "name": "Cornière à ailes égales",
    "description": "Epaisseur : 2 mm Hauteur Ailes : 25 mm",
    "basePrice": 20,
    "unitPriceExclTax": 20,
    "VATRate": 10,
    "marginPercent": 20,
    "sellingPrice": 26.4,
    "linearWeight": 0.29,
    "thickness": 2,
    "height": 25,
    "width": null,
    "diameter": null,
    "circumference": null,
    "sectionArea": 0,
    "weight": null,
    "matiere": "Aluminium",
    "productCode": 13
  },
  {
    "name": "Cornière à ailes égales",
    "description": "Epaisseur : 2 mm Hauteur Ailes : 30 mm",
    "basePrice": 20,
    "unitPriceExclTax": 20,
    "VATRate": 10,
    "marginPercent": 20,
    "sellingPrice": 26.4,
    "linearWeight": 0.34,
    "thickness": 2,
    "height": 30,
    "width": null,
    "diameter": null,
    "circumference": null,
    "sectionArea": 0,
    "weight": null,
    "matiere": "Aluminium",
    "productCode": 14
  },
  {
    "name": "Cornière à ailes égales",
    "description": "Epaisseur : 3 mm Hauteur Ailes : 30 mm",
    "basePrice": 20,
    "unitPriceExclTax": 20,
    "VATRate": 10,
    "marginPercent": 20,
    "sellingPrice": 26.4,
    "linearWeight": 0.51,
    "thickness": 3,
    "height": 30,
    "width": null,
    "diameter": null,
    "circumference": null,
    "sectionArea": 0,
    "weight": null,
    "matiere": "Aluminium",
    "productCode": 15
  },
  {
    "name": "Cornière à ailes égales",
    "description": "Epaisseur : 3 mm Hauteur Ailes : 35 mm",
    "basePrice": 20,
    "unitPriceExclTax": 20,
    "VATRate": 10,
    "marginPercent": 20,
    "sellingPrice": 26.4,
    "linearWeight": 0.59,
    "thickness": 3,
    "height": 35,
    "width": null,
    "diameter": null,
    "circumference": null,
    "sectionArea": 0,
    "weight": null,
    "matiere": "Aluminium",
    "productCode": 16
  },
  {
    "name": "Cornière à ailes égales",
    "description": "Epaisseur : 2 mm Hauteur Ailes : 40 mm",
    "basePrice": 20,
    "unitPriceExclTax": 20,
    "VATRate": 10,
    "marginPercent": 20,
    "sellingPrice": 26.4,
    "linearWeight": 0.46,
    "thickness": 2,
    "height": 40,
    "width": null,
    "diameter": null,
    "circumference": null,
    "sectionArea": 0,
    "weight": null,
    "matiere": "Aluminium",
    "productCode": 17
  },
  {
    "name": "Cornière à ailes égales",
    "description": "Epaisseur : 3 mm Hauteur Ailes : 40 mm",
    "basePrice": 20,
    "unitPriceExclTax": 20,
    "VATRate": 10,
    "marginPercent": 20,
    "sellingPrice": 26.4,
    "linearWeight": 0.68,
    "thickness": 3,
    "height": 40,
    "width": null,
    "diameter": null,
    "circumference": null,
    "sectionArea": 0,
    "weight": null,
    "matiere": "Aluminium",
    "productCode": 18
  },
  {
    "name": "Cornière à ailes égales",
    "description": "Epaisseur : 4 mm Hauteur Ailes : 40 mm",
    "basePrice": 20,
    "unitPriceExclTax": 20,
    "VATRate": 10,
    "marginPercent": 20,
    "sellingPrice": 26.4,
    "linearWeight": 0.9,
    "thickness": 4,
    "height": 40,
    "width": null,
    "diameter": null,
    "circumference": null,
    "sectionArea": 0,
    "weight": null,
    "matiere": "Aluminium",
    "productCode": 19
  },
  {
    "name": "Cornière à ailes égales",
    "description": "Epaisseur : 2 mm Hauteur Ailes : 50 mm",
    "basePrice": 20,
    "unitPriceExclTax": 20,
    "VATRate": 10,
    "marginPercent": 20,
    "sellingPrice": 26.4,
    "linearWeight": 0.58,
    "thickness": 2,
    "height": 50,
    "width": null,
    "diameter": null,
    "circumference": null,
    "sectionArea": 0,
    "weight": null,
    "matiere": "Aluminium",
    "productCode": 20
  },
  {
    "name": "Cornière à ailes égales",
    "description": "Epaisseur : 3 mm Hauteur Ailes : 50 mm",
    "basePrice": 20,
    "unitPriceExclTax": 20,
    "VATRate": 10,
    "marginPercent": 20,
    "sellingPrice": 26.4,
    "linearWeight": 0.87,
    "thickness": 3,
    "height": 50,
    "width": null,
    "diameter": null,
    "circumference": null,
    "sectionArea": 0,
    "weight": null,
    "matiere": "Aluminium",
    "productCode": 21
  },
  {
    "name": "Cornière à ailes égales",
    "description": "Epaisseur : 4 mm Hauteur Ailes : 50 mm",
    "basePrice": 20,
    "unitPriceExclTax": 20,
    "VATRate": 10,
    "marginPercent": 20,
    "sellingPrice": 26.4,
    "linearWeight": 1.14,
    "thickness": 4,
    "height": 50,
    "width": null,
    "diameter": null,
    "circumference": null,
    "sectionArea": 0,
    "weight": null,
    "matiere": "Aluminium",
    "productCode": 22
  },
  {
    "name": "Cornière à ailes égales",
    "description": "Epaisseur : 5 mm Hauteur Ailes : 50 mm",
    "basePrice": 20,
    "unitPriceExclTax": 20,
    "VATRate": 10,
    "marginPercent": 20,
    "sellingPrice": 26.4,
    "linearWeight": 1.41,
    "thickness": 5,
    "height": 50,
    "width": null,
    "diameter": null,
    "circumference": null,
    "sectionArea": 0,
    "weight": null,
    "matiere": "Aluminium",
    "productCode": 23
  },
  {
    "name": "Cornière à ailes égales",
    "description": "Epaisseur : 2 mm Hauteur Ailes : 60 mm",
    "basePrice": 20,
    "unitPriceExclTax": 20,
    "VATRate": 10,
    "marginPercent": 20,
    "sellingPrice": 26.4,
    "linearWeight": 0.7,
    "thickness": 2,
    "height": 60,
    "width": null,
    "diameter": null,
    "circumference": null,
    "sectionArea": 0,
    "weight": null,
    "matiere": "Aluminium",
    "productCode": 24
  },
  {
    "name": "Cornière à ailes égales",
    "description": "Epaisseur : 4 mm Hauteur Ailes : 60 mm",
    "basePrice": 20,
    "unitPriceExclTax": 20,
    "VATRate": 10,
    "marginPercent": 20,
    "sellingPrice": 26.4,
    "linearWeight": 1.38,
    "thickness": 4,
    "height": 60,
    "width": null,
    "diameter": null,
    "circumference": null,
    "sectionArea": 0,
    "weight": null,
    "matiere": "Aluminium",
    "productCode": 25
  },
  {
    "name": "Cornière à ailes égales",
    "description": "Epaisseur : 6 mm Hauteur Ailes : 60 mm",
    "basePrice": 20,
    "unitPriceExclTax": 20,
    "VATRate": 10,
    "marginPercent": 20,
    "sellingPrice": 26.4,
    "linearWeight": 2.02,
    "thickness": 6,
    "height": 60,
    "width": null,
    "diameter": null,
    "circumference": null,
    "sectionArea": 0,
    "weight": null,
    "matiere": "Aluminium",
    "productCode": 26
  },
  {
    "name": "Cornière à ailes égales",
    "description": "Epaisseur : 8 mm Hauteur Ailes : 80 mm",
    "basePrice": 20,
    "unitPriceExclTax": 20,
    "VATRate": 10,
    "marginPercent": 20,
    "sellingPrice": 26.4,
    "linearWeight": 3.61,
    "thickness": 8,
    "height": 80,
    "width": null,
    "diameter": null,
    "circumference": null,
    "sectionArea": 0,
    "weight": null,
    "matiere": "Aluminium",
    "productCode": 27
  },
  {
    "name": "Cornière à ailes égales",
    "description": "Epaisseur : 10 mm Hauteur Ailes : 100 mm",
    "basePrice": 20,
    "unitPriceExclTax": 20,
    "VATRate": 10,
    "marginPercent": 20,
    "sellingPrice": 26.4,
    "linearWeight": 5.64,
    "thickness": 10,
    "height": 100,
    "width": null,
    "diameter": null,
    "circumference": null,
    "sectionArea": 0,
    "weight": null,
    "matiere": "Aluminium",
    "productCode": 28
  },
  {
    "name": "Tube rectangulaire",
    "description": "Hauteur : 25 mm Largeur : 15 mm Epaisseur : 2 mm",
    "basePrice": 20,
    "unitPriceExclTax": 20,
    "VATRate": 10,
    "marginPercent": 20,
    "sellingPrice": 26.4,
    "linearWeight": 0.43,
    "thickness": 2,
    "height": 25,
    "width": 15,
    "diameter": null,
    "circumference": null,
    "sectionArea": 0,
    "weight": null,
    "matiere": "Aluminium",
    "productCode": 29
  },
  {
    "name": "Tube rectangulaire",
    "description": "Hauteur : 30 mm Largeur : 15 mm Epaisseur : 1.5 mm",
    "basePrice": 20,
    "unitPriceExclTax": 20,
    "VATRate": 10,
    "marginPercent": 20,
    "sellingPrice": 26.4,
    "linearWeight": 0.37,
    "thickness": 1.5,
    "height": 30,
    "width": 15,
    "diameter": null,
    "circumference": null,
    "sectionArea": 0,
    "weight": null,
    "matiere": "Aluminium",
    "productCode": 30
  },
  {
    "name": "Tube rectangulaire",
    "description": "Hauteur : 30 mm Largeur : 20 mm Epaisseur : 2 mm",
    "basePrice": 20,
    "unitPriceExclTax": 20,
    "VATRate": 10,
    "marginPercent": 20,
    "sellingPrice": 26.4,
    "linearWeight": 0.55,
    "thickness": 2,
    "height": 30,
    "width": 20,
    "diameter": null,
    "circumference": null,
    "sectionArea": 0,
    "weight": null,
    "matiere": "Aluminium",
    "productCode": 31
  },
  {
    "name": "Tube rectangulaire",
    "description": "Hauteur : 40 mm Largeur : 20 mm Epaisseur : 2 mm",
    "basePrice": 20,
    "unitPriceExclTax": 20,
    "VATRate": 10,
    "marginPercent": 20,
    "sellingPrice": 26.4,
    "linearWeight": 0.66,
    "thickness": 2,
    "height": 40,
    "width": 20,
    "diameter": null,
    "circumference": null,
    "sectionArea": 0,
    "weight": null,
    "matiere": "Aluminium",
    "productCode": 32
  },
  {
    "name": "Tube rectangulaire",
    "description": "Hauteur : 40 mm Largeur : 20 mm Epaisseur : 3 mm",
    "basePrice": 20,
    "unitPriceExclTax": 20,
    "VATRate": 10,
    "marginPercent": 20,
    "sellingPrice": 26.4,
    "linearWeight": 0.97,
    "thickness": 3,
    "height": 40,
    "width": 20,
    "diameter": null,
    "circumference": null,
    "sectionArea": 0,
    "weight": null,
    "matiere": "Aluminium",
    "productCode": 33
  },
  {
    "name": "Tube rectangulaire",
    "description": "Hauteur : 40 mm Largeur : 20 mm Epaisseur : 4 mm",
    "basePrice": 30,
    "unitPriceExclTax": 30,
    "VATRate": 10,
    "marginPercent": 20,
    "sellingPrice": 39.6,
    "linearWeight": 1.23,
    "thickness": 4,
    "height": 40,
    "width": 20,
    "diameter": null,
    "circumference": null,
    "sectionArea": 0,
    "weight": null,
    "matiere": "Aluminium",
    "productCode": 34
  },
  {
    "name": "Tube rectangulaire",
    "description": "Hauteur : 50 mm Largeur : 20 mm Epaisseur : 2 mm",
    "basePrice": 20,
    "unitPriceExclTax": 20,
    "VATRate": 10,
    "marginPercent": 20,
    "sellingPrice": 26.4,
    "linearWeight": 0.78,
    "thickness": 2,
    "height": 50,
    "width": 20,
    "diameter": null,
    "circumference": null,
    "sectionArea": 0,
    "weight": null,
    "matiere": "Aluminium",
    "productCode": 35
  },
  {
    "name": "Tube rectangulaire",
    "description": "Hauteur : 50 mm Largeur : 25 mm Epaisseur : 2 mm",
    "basePrice": 20,
    "unitPriceExclTax": 20,
    "VATRate": 10,
    "marginPercent": 20,
    "sellingPrice": 26.4,
    "linearWeight": 0.85,
    "thickness": 2,
    "height": 50,
    "width": 25,
    "diameter": null,
    "circumference": null,
    "sectionArea": 0,
    "weight": null,
    "matiere": "Aluminium",
    "productCode": 36
  },
  {
    "name": "Tube rectangulaire",
    "description": "Hauteur : 50 mm Largeur : 30 mm Epaisseur : 2 mm",
    "basePrice": 20,
    "unitPriceExclTax": 20,
    "VATRate": 10,
    "marginPercent": 20,
    "sellingPrice": 26.4,
    "linearWeight": 0.9,
    "thickness": 2,
    "height": 50,
    "width": 30,
    "diameter": null,
    "circumference": null,
    "sectionArea": 0,
    "weight": null,
    "matiere": "Aluminium",
    "productCode": 37
  },
  {
    "name": "Tube rectangulaire",
    "description": "Hauteur : 50 mm Largeur : 30 mm Epaisseur : 3 mm",
    "basePrice": 20,
    "unitPriceExclTax": 20,
    "VATRate": 10,
    "marginPercent": 20,
    "sellingPrice": 26.4,
    "linearWeight": 1.32,
    "thickness": 3,
    "height": 50,
    "width": 30,
    "diameter": null,
    "circumference": null,
    "sectionArea": 0,
    "weight": null,
    "matiere": "Aluminium",
    "productCode": 38
  },
  {
    "name": "Tube rectangulaire",
    "description": "Hauteur : 60 mm Largeur : 30 mm Epaisseur : 2 mm",
    "basePrice": 20,
    "unitPriceExclTax": 20,
    "VATRate": 10,
    "marginPercent": 20,
    "sellingPrice": 26.4,
    "linearWeight": 1.02,
    "thickness": 2,
    "height": 60,
    "width": 30,
    "diameter": null,
    "circumference": null,
    "sectionArea": 0,
    "weight": null,
    "matiere": "Aluminium",
    "productCode": 39
  },
  {
    "name": "Tube rectangulaire",
    "description": "Hauteur : 60 mm Largeur : 30 mm Epaisseur : 3 mm",
    "basePrice": 20,
    "unitPriceExclTax": 20,
    "VATRate": 10,
    "marginPercent": 20,
    "sellingPrice": 26.4,
    "linearWeight": 1.5,
    "thickness": 3,
    "height": 60,
    "width": 30,
    "diameter": null,
    "circumference": null,
    "sectionArea": 0,
    "weight": null,
    "matiere": "Aluminium",
    "productCode": 40
  },
  {
    "name": "Tube rectangulaire",
    "description": "Hauteur : 60 mm Largeur : 40 mm Epaisseur : 2 mm",
    "basePrice": 20,
    "unitPriceExclTax": 20,
    "VATRate": 10,
    "marginPercent": 20,
    "sellingPrice": 26.4,
    "linearWeight": 1.14,
    "thickness": 2,
    "height": 60,
    "width": 40,
    "diameter": null,
    "circumference": null,
    "sectionArea": 0,
    "weight": null,
    "matiere": "Aluminium",
    "productCode": 41
  },
  {
    "name": "Tube rectangulaire",
    "description": "Hauteur : 60 mm Largeur : 40 mm Epaisseur : 3 mm",
    "basePrice": 20,
    "unitPriceExclTax": 20,
    "VATRate": 10,
    "marginPercent": 20,
    "sellingPrice": 26.4,
    "linearWeight": 1.67,
    "thickness": 3,
    "height": 60,
    "width": 40,
    "diameter": null,
    "circumference": null,
    "sectionArea": 0,
    "weight": null,
    "matiere": "Aluminium",
    "productCode": 42
  },
  {
    "name": "Tube rectangulaire",
    "description": "Hauteur : 60 mm Largeur : 40 mm Epaisseur : 4 mm",
    "basePrice": 30,
    "unitPriceExclTax": 30,
    "VATRate": 10,
    "marginPercent": 20,
    "sellingPrice": 39.6,
    "linearWeight": 2.18,
    "thickness": 4,
    "height": 60,
    "width": 40,
    "diameter": null,
    "circumference": null,
    "sectionArea": 0,
    "weight": null,
    "matiere": "Aluminium",
    "productCode": 43
  },
  {
    "name": "Tube rectangulaire",
    "description": "Hauteur : 80 mm Largeur : 20 mm Epaisseur : 2 mm",
    "basePrice": 20,
    "unitPriceExclTax": 20,
    "VATRate": 10,
    "marginPercent": 20,
    "sellingPrice": 26.4,
    "linearWeight": 1.14,
    "thickness": 2,
    "height": 80,
    "width": 20,
    "diameter": null,
    "circumference": null,
    "sectionArea": 0,
    "weight": null,
    "matiere": "Aluminium",
    "productCode": 44
  },
  {
    "name": "Tube rectangulaire",
    "description": "Hauteur : 80 mm Largeur : 40 mm Epaisseur : 2 mm",
    "basePrice": 20,
    "unitPriceExclTax": 20,
    "VATRate": 10,
    "marginPercent": 20,
    "sellingPrice": 26.4,
    "linearWeight": 1.38,
    "thickness": 2,
    "height": 80,
    "width": 40,
    "diameter": null,
    "circumference": null,
    "sectionArea": 0,
    "weight": null,
    "matiere": "Aluminium",
    "productCode": 45
  },
  {
    "name": "Tube rectangulaire",
    "description": "Hauteur : 80 mm Largeur : 40 mm Epaisseur : 3 mm",
    "basePrice": 20,
    "unitPriceExclTax": 20,
    "VATRate": 10,
    "marginPercent": 20,
    "sellingPrice": 26.4,
    "linearWeight": 2.04,
    "thickness": 3,
    "height": 80,
    "width": 40,
    "diameter": null,
    "circumference": null,
    "sectionArea": 0,
    "weight": null,
    "matiere": "Aluminium",
    "productCode": 46
  },
  {
    "name": "Tube rectangulaire",
    "description": "Hauteur : 80 mm Largeur : 40 mm Epaisseur : 4 mm",
    "basePrice": 30,
    "unitPriceExclTax": 30,
    "VATRate": 10,
    "marginPercent": 20,
    "sellingPrice": 39.6,
    "linearWeight": 2.65,
    "thickness": 4,
    "height": 80,
    "width": 40,
    "diameter": null,
    "circumference": null,
    "sectionArea": 0,
    "weight": null,
    "matiere": "Aluminium",
    "productCode": 47
  },
  {
    "name": "Tube rectangulaire",
    "description": "Hauteur : 80 mm Largeur : 50 mm Epaisseur : 5 mm",
    "basePrice": 30,
    "unitPriceExclTax": 30,
    "VATRate": 10,
    "marginPercent": 20,
    "sellingPrice": 39.6,
    "linearWeight": 3.56,
    "thickness": 5,
    "height": 80,
    "width": 50,
    "diameter": null,
    "circumference": null,
    "sectionArea": 0,
    "weight": null,
    "matiere": "Aluminium",
    "productCode": 48
  },
  {
    "name": "Tube carré",
    "description": "Epaisseur : 1.5 mm Hauteur : 20 mm",
    "basePrice": 20,
    "unitPriceExclTax": 20,
    "VATRate": 10,
    "marginPercent": 20,
    "sellingPrice": 26.4,
    "linearWeight": 0.33,
    "thickness": 1.5,
    "height": 20,
    "width": null,
    "diameter": null,
    "circumference": null,
    "sectionArea": null,
    "weight": null,
    "matiere": "Aluminium",
    "productCode": 49
  },
  {
    "name": "Tube carré",
    "description": "Epaisseur : 2 mm Hauteur : 20 mm",
    "basePrice": 20,
    "unitPriceExclTax": 20,
    "VATRate": 10,
    "marginPercent": 20,
    "sellingPrice": 26.4,
    "linearWeight": 0.43,
    "thickness": 2,
    "height": 20,
    "width": null,
    "diameter": null,
    "circumference": null,
    "sectionArea": null,
    "weight": null,
    "matiere": "Aluminium",
    "productCode": 50
  },
  {
    "name": "Tube carré",
    "description": "Epaisseur : 2 mm Hauteur : 25 mm",
    "basePrice": 20,
    "unitPriceExclTax": 20,
    "VATRate": 10,
    "marginPercent": 20,
    "sellingPrice": 26.4,
    "linearWeight": 0.55,
    "thickness": 2,
    "height": 25,
    "width": null,
    "diameter": null,
    "circumference": null,
    "sectionArea": null,
    "weight": null,
    "matiere": "Aluminium",
    "productCode": 51
  },
  {
    "name": "Tube carré",
    "description": "Epaisseur : 3 mm Hauteur : 25 mm",
    "basePrice": 20,
    "unitPriceExclTax": 20,
    "VATRate": 10,
    "marginPercent": 20,
    "sellingPrice": 26.4,
    "linearWeight": 0.78,
    "thickness": 3,
    "height": 25,
    "width": null,
    "diameter": null,
    "circumference": null,
    "sectionArea": null,
    "weight": null,
    "matiere": "Aluminium",
    "productCode": 52
  },
  {
    "name": "Tube carré",
    "description": "Epaisseur : 1.5 mm Hauteur : 30 mm",
    "basePrice": 20,
    "unitPriceExclTax": 20,
    "VATRate": 10,
    "marginPercent": 20,
    "sellingPrice": 26.4,
    "linearWeight": 0.51,
    "thickness": 1.5,
    "height": 30,
    "width": null,
    "diameter": null,
    "circumference": null,
    "sectionArea": null,
    "weight": null,
    "matiere": "Aluminium",
    "productCode": 53
  },
  {
    "name": "Tube carré",
    "description": "Epaisseur : 2 mm Hauteur : 30 mm",
    "basePrice": 20,
    "unitPriceExclTax": 20,
    "VATRate": 10,
    "marginPercent": 20,
    "sellingPrice": 26.4,
    "linearWeight": 0.66,
    "thickness": 2,
    "height": 30,
    "width": null,
    "diameter": null,
    "circumference": null,
    "sectionArea": null,
    "weight": null,
    "matiere": "Aluminium",
    "productCode": 54
  },
  {
    "name": "Tube carré",
    "description": "Epaisseur : 3 mm Hauteur : 30 mm",
    "basePrice": 20,
    "unitPriceExclTax": 20,
    "VATRate": 10,
    "marginPercent": 20,
    "sellingPrice": 26.4,
    "linearWeight": 0.97,
    "thickness": 3,
    "height": 30,
    "width": null,
    "diameter": null,
    "circumference": null,
    "sectionArea": null,
    "weight": null,
    "matiere": "Aluminium",
    "productCode": 55
  },
  {
    "name": "Tube carré",
    "description": "Epaisseur : 2 mm Hauteur : 35 mm",
    "basePrice": 20,
    "unitPriceExclTax": 20,
    "VATRate": 10,
    "marginPercent": 20,
    "sellingPrice": 26.4,
    "linearWeight": 0.78,
    "thickness": 2,
    "height": 35,
    "width": null,
    "diameter": null,
    "circumference": null,
    "sectionArea": null,
    "weight": null,
    "matiere": "Aluminium",
    "productCode": 56
  },
  {
    "name": "Barre carrée pleine",
    "description": "Hauteur : 10 mm",
    "basePrice": 20,
    "unitPriceExclTax": 20,
    "VATRate": 10,
    "marginPercent": 20,
    "sellingPrice": 26.4,
    "linearWeight": 0.31,
    "thickness": null,
    "height": 10,
    "width": null,
    "diameter": null,
    "circumference": null,
    "sectionArea": null,
    "weight": null,
    "matiere": "Aluminium",
    "productCode": 57
  },
  {
    "name": "Barre carrée pleine",
    "description": "Hauteur : 12 mm",
    "basePrice": 20,
    "unitPriceExclTax": 20,
    "VATRate": 10,
    "marginPercent": 20,
    "sellingPrice": 26.4,
    "linearWeight": 0.44,
    "thickness": null,
    "height": 12,
    "width": null,
    "diameter": null,
    "circumference": null,
    "sectionArea": null,
    "weight": null,
    "matiere": "Aluminium",
    "productCode": 58
  },
  {
    "name": "Barre carrée pleine",
    "description": "Hauteur : 14 mm",
    "basePrice": 20,
    "unitPriceExclTax": 20,
    "VATRate": 10,
    "marginPercent": 20,
    "sellingPrice": 26.4,
    "linearWeight": 0.61,
    "thickness": null,
    "height": 14,
    "width": null,
    "diameter": null,
    "circumference": null,
    "sectionArea": null,
    "weight": null,
    "matiere": "Aluminium",
    "productCode": 59
  },
  {
    "name": "Barre carrée pleine",
    "description": "Hauteur : 16 mm",
    "basePrice": 20,
    "unitPriceExclTax": 20,
    "VATRate": 10,
    "marginPercent": 20,
    "sellingPrice": 26.4,
    "linearWeight": 0.79,
    "thickness": null,
    "height": 16,
    "width": null,
    "diameter": null,
    "circumference": null,
    "sectionArea": null,
    "weight": null,
    "matiere": "Aluminium",
    "productCode": 60
  },
  {
    "name": "Barre carrée pleine",
    "description": "Hauteur : 20 mm",
    "basePrice": 20,
    "unitPriceExclTax": 20,
    "VATRate": 10,
    "marginPercent": 20,
    "sellingPrice": 26.4,
    "linearWeight": 1.23,
    "thickness": null,
    "height": 20,
    "width": null,
    "diameter": null,
    "circumference": null,
    "sectionArea": null,
    "weight": null,
    "matiere": "Aluminium",
    "productCode": 61
  },
  {
    "name": "Barre carrée pleine",
    "description": "Hauteur : 25 mm",
    "basePrice": 20,
    "unitPriceExclTax": 20,
    "VATRate": 10,
    "marginPercent": 20,
    "sellingPrice": 26.4,
    "linearWeight": 1.93,
    "thickness": null,
    "height": 25,
    "width": null,
    "diameter": null,
    "circumference": null,
    "sectionArea": null,
    "weight": null,
    "matiere": "Aluminium",
    "productCode": 62
  },
  {
    "name": "Barre carrée pleine",
    "description": "Hauteur : 30 mm",
    "basePrice": 20,
    "unitPriceExclTax": 20,
    "VATRate": 10,
    "marginPercent": 20,
    "sellingPrice": 26.4,
    "linearWeight": 2.48,
    "thickness": null,
    "height": 30,
    "width": null,
    "diameter": null,
    "circumference": null,
    "sectionArea": null,
    "weight": null,
    "matiere": "Aluminium",
    "productCode": 63
  },
  {
    "name": "Barre carrée pleine",
    "description": "Hauteur : 40 mm",
    "basePrice": 20,
    "unitPriceExclTax": 20,
    "VATRate": 10,
    "marginPercent": 20,
    "sellingPrice": 26.4,
    "linearWeight": 4.93,
    "thickness": null,
    "height": 40,
    "width": null,
    "diameter": null,
    "circumference": null,
    "sectionArea": null,
    "weight": null,
    "matiere": "Aluminium",
    "productCode": 64
  },
  {
    "name": "Barre carrée pleine",
    "description": "Hauteur : 45 mm",
    "basePrice": 20,
    "unitPriceExclTax": 20,
    "VATRate": 10,
    "marginPercent": 20,
    "sellingPrice": 26.4,
    "linearWeight": 6.24,
    "thickness": null,
    "height": 45,
    "width": null,
    "diameter": null,
    "circumference": null,
    "sectionArea": null,
    "weight": null,
    "matiere": "Aluminium",
    "productCode": 65
  },
  {
    "name": "Barre carrée pleine",
    "description": "Hauteur : 50 mm",
    "basePrice": 20,
    "unitPriceExclTax": 20,
    "VATRate": 10,
    "marginPercent": 20,
    "sellingPrice": 26.4,
    "linearWeight": 7.7,
    "thickness": null,
    "height": 50,
    "width": null,
    "diameter": null,
    "circumference": null,
    "sectionArea": null,
    "weight": null,
    "matiere": "Aluminium",
    "productCode": 66
  },
  {
    "name": "Barre carrée pleine",
    "description": "Hauteur : 55 mm",
    "basePrice": 20,
    "unitPriceExclTax": 20,
    "VATRate": 10,
    "marginPercent": 20,
    "sellingPrice": 26.4,
    "linearWeight": 9.32,
    "thickness": null,
    "height": 55,
    "width": null,
    "diameter": null,
    "circumference": null,
    "sectionArea": null,
    "weight": null,
    "matiere": "Aluminium",
    "productCode": 67
  },
  {
    "name": "Barre carrée pleine",
    "description": "Hauteur : 60 mm",
    "basePrice": 20,
    "unitPriceExclTax": 20,
    "VATRate": 10,
    "marginPercent": 20,
    "sellingPrice": 26.4,
    "linearWeight": 11.09,
    "thickness": null,
    "height": 60,
    "width": null,
    "diameter": null,
    "circumference": null,
    "sectionArea": null,
    "weight": null,
    "matiere": "Aluminium",
    "productCode": 68
  },
  {
    "name": "Barre carrée pleine",
    "description": "Hauteur : 65 mm",
    "basePrice": 20,
    "unitPriceExclTax": 20,
    "VATRate": 10,
    "marginPercent": 20,
    "sellingPrice": 26.4,
    "linearWeight": 13.01,
    "thickness": null,
    "height": 65,
    "width": null,
    "diameter": null,
    "circumference": null,
    "sectionArea": null,
    "weight": null,
    "matiere": "Aluminium",
    "productCode": 69
  },
  {
    "name": "Barre carrée pleine",
    "description": "Hauteur : 70 mm",
    "basePrice": 20,
    "unitPriceExclTax": 20,
    "VATRate": 10,
    "marginPercent": 20,
    "sellingPrice": 26.4,
    "linearWeight": 15.09,
    "thickness": null,
    "height": 70,
    "width": null,
    "diameter": null,
    "circumference": null,
    "sectionArea": null,
    "weight": null,
    "matiere": "Aluminium",
    "productCode": 70
  },
  {
    "name": "Barre carrée pleine",
    "description": "Hauteur : 80 mm",
    "basePrice": 20,
    "unitPriceExclTax": 20,
    "VATRate": 10,
    "marginPercent": 20,
    "sellingPrice": 26.4,
    "linearWeight": 19.71,
    "thickness": null,
    "height": 80,
    "width": null,
    "diameter": null,
    "circumference": null,
    "sectionArea": null,
    "weight": null,
    "matiere": "Aluminium",
    "productCode": 71
  },
  {
    "name": "Barre carrée pleine",
    "description": "Hauteur : 90 mm",
    "basePrice": 20,
    "unitPriceExclTax": 20,
    "VATRate": 10,
    "marginPercent": 20,
    "sellingPrice": 26.4,
    "linearWeight": 24.95,
    "thickness": null,
    "height": 90,
    "width": null,
    "diameter": null,
    "circumference": null,
    "sectionArea": null,
    "weight": null,
    "matiere": "Aluminium",
    "productCode": 72
  },
  {
    "name": "Barre carrée pleine",
    "description": "Hauteur : 100 mm",
    "basePrice": 20,
    "unitPriceExclTax": 20,
    "VATRate": 10,
    "marginPercent": 20,
    "sellingPrice": 26.4,
    "linearWeight": 30.8,
    "thickness": null,
    "height": 100,
    "width": null,
    "diameter": null,
    "circumference": null,
    "sectionArea": null,
    "weight": null,
    "matiere": "Aluminium",
    "productCode": 73
  },
  {
    "name": "Cornière à ailes égales",
    "description": "Epaisseur : 3 mm Hauteur Ailes : 20 mm",
    "basePrice": 18,
    "unitPriceExclTax": 18,
    "VATRate": 10,
    "marginPercent": 20,
    "sellingPrice": 23.76,
    "linearWeight": 0.97,
    "thickness": 3,
    "height": 20,
    "width": null,
    "diameter": null,
    "circumference": null,
    "sectionArea": 1.13,
    "weight": null,
    "matiere": "Inox",
    "productCode": 74
  },
  {
    "name": "Cornière à ailes égales",
    "description": "Epaisseur : 3 mm Hauteur Ailes : 25 mm",
    "basePrice": 18,
    "unitPriceExclTax": 18,
    "VATRate": 10,
    "marginPercent": 20,
    "sellingPrice": 23.76,
    "linearWeight": 1.23,
    "thickness": 3,
    "height": 25,
    "width": null,
    "diameter": null,
    "circumference": null,
    "sectionArea": 1.43,
    "weight": null,
    "matiere": "Inox",
    "productCode": 75
  },
  {
    "name": "Cornière à ailes égales",
    "description": "Epaisseur : 3 mm Hauteur Ailes : 30 mm",
    "basePrice": 18,
    "unitPriceExclTax": 18,
    "VATRate": 10,
    "marginPercent": 20,
    "sellingPrice": 23.76,
    "linearWeight": 1.5,
    "thickness": 3,
    "height": 30,
    "width": null,
    "diameter": null,
    "circumference": null,
    "sectionArea": 1.74,
    "weight": null,
    "matiere": "Inox",
    "productCode": 76
  },
  {
    "name": "Cornière à ailes égales",
    "description": "Epaisseur : 4 mm Hauteur Ailes : 40 mm",
    "basePrice": 18,
    "unitPriceExclTax": 18,
    "VATRate": 10,
    "marginPercent": 20,
    "sellingPrice": 23.76,
    "linearWeight": 2.66,
    "thickness": 4,
    "height": 40,
    "width": null,
    "diameter": null,
    "circumference": null,
    "sectionArea": 3.08,
    "weight": null,
    "matiere": "Inox",
    "productCode": 77
  },
  {
    "name": "Cornière à ailes égales",
    "description": "Epaisseur : 5 mm Hauteur Ailes : 50 mm",
    "basePrice": 18,
    "unitPriceExclTax": 18,
    "VATRate": 10,
    "marginPercent": 20,
    "sellingPrice": 23.76,
    "linearWeight": 4.15,
    "thickness": 5,
    "height": 50,
    "width": null,
    "diameter": null,
    "circumference": null,
    "sectionArea": 4.8,
    "weight": null,
    "matiere": "Inox",
    "productCode": 78
  },
  {
    "name": "Cornière à ailes égales",
    "description": "Epaisseur : 6 mm Hauteur Ailes : 60 mm",
    "basePrice": 18,
    "unitPriceExclTax": 18,
    "VATRate": 10,
    "marginPercent": 20,
    "sellingPrice": 23.76,
    "linearWeight": 5.96,
    "thickness": 6,
    "height": 60,
    "width": null,
    "diameter": null,
    "circumference": null,
    "sectionArea": 6.91,
    "weight": null,
    "matiere": "Inox",
    "productCode": 79
  },
  {
    "name": "Cornière à ailes égales",
    "description": "Epaisseur : 7 mm Hauteur Ailes : 70 mm",
    "basePrice": 18,
    "unitPriceExclTax": 18,
    "VATRate": 10,
    "marginPercent": 20,
    "sellingPrice": 23.76,
    "linearWeight": 8.12,
    "thickness": 7,
    "height": 70,
    "width": null,
    "diameter": null,
    "circumference": null,
    "sectionArea": 9.4,
    "weight": null,
    "matiere": "Inox",
    "productCode": 80
  },
  {
    "name": "Cornière à ailes égales",
    "description": "Epaisseur : 8 mm Hauteur Ailes : 80 mm",
    "basePrice": 18,
    "unitPriceExclTax": 18,
    "VATRate": 10,
    "marginPercent": 20,
    "sellingPrice": 23.76,
    "linearWeight": 10.59,
    "thickness": 8,
    "height": 80,
    "width": null,
    "diameter": null,
    "circumference": null,
    "sectionArea": 12.3,
    "weight": null,
    "matiere": "Inox",
    "productCode": 81
  },
  {
    "name": "Cornière à ailes égales",
    "description": "Epaisseur : 10 mm Hauteur Ailes : 100 mm",
    "basePrice": 18,
    "unitPriceExclTax": 18,
    "VATRate": 10,
    "marginPercent": 20,
    "sellingPrice": 23.76,
    "linearWeight": 16.5,
    "thickness": 10,
    "height": 100,
    "width": null,
    "diameter": null,
    "circumference": null,
    "sectionArea": 19.2,
    "weight": null,
    "matiere": "Inox",
    "productCode": 82
  },
  {
    "name": "FER T",
    "description": "Epaisseur : 3 mm Hauteur : 20 mm Largeur : 20 mm",
    "basePrice": 18,
    "unitPriceExclTax": 18,
    "VATRate": 10,
    "marginPercent": 20,
    "sellingPrice": 23.76,
    "linearWeight": 0.97,
    "thickness": 3,
    "height": 20,
    "width": 20,
    "diameter": null,
    "circumference": null,
    "sectionArea": 0,
    "weight": null,
    "matiere": "Inox",
    "productCode": 83
  },
  {
    "name": "FER T",
    "description": "Epaisseur : 4 mm Hauteur : 20 mm Largeur : 20 mm",
    "basePrice": 18,
    "unitPriceExclTax": 18,
    "VATRate": 10,
    "marginPercent": 20,
    "sellingPrice": 23.76,
    "linearWeight": 1.32,
    "thickness": 4,
    "height": 20,
    "width": 20,
    "diameter": null,
    "circumference": null,
    "sectionArea": 0,
    "weight": null,
    "matiere": "Inox",
    "productCode": 84
  },
  {
    "name": "FER T",
    "description": "Epaisseur : 3 mm Hauteur : 30 mm Largeur : 30 mm",
    "basePrice": 18,
    "unitPriceExclTax": 18,
    "VATRate": 10,
    "marginPercent": 20,
    "sellingPrice": 23.76,
    "linearWeight": 1.51,
    "thickness": 3,
    "height": 30,
    "width": 30,
    "diameter": null,
    "circumference": null,
    "sectionArea": 0,
    "weight": null,
    "matiere": "Inox",
    "productCode": 85
  },
  {
    "name": "FER T",
    "description": "Epaisseur : 4 mm Hauteur : 40 mm Largeur : 40 mm",
    "basePrice": 18,
    "unitPriceExclTax": 18,
    "VATRate": 10,
    "marginPercent": 20,
    "sellingPrice": 23.76,
    "linearWeight": 2.67,
    "thickness": 4,
    "height": 40,
    "width": 40,
    "diameter": null,
    "circumference": null,
    "sectionArea": 0,
    "weight": null,
    "matiere": "Inox",
    "productCode": 86
  },
  {
    "name": "FER T",
    "description": "Epaisseur : 5 mm Hauteur : 50 mm Largeur : 50 mm",
    "basePrice": 18,
    "unitPriceExclTax": 18,
    "VATRate": 10,
    "marginPercent": 20,
    "sellingPrice": 23.76,
    "linearWeight": 4.18,
    "thickness": 5,
    "height": 50,
    "width": 50,
    "diameter": null,
    "circumference": null,
    "sectionArea": 0,
    "weight": null,
    "matiere": "Inox",
    "productCode": 87
  },
  {
    "name": "FER T",
    "description": "Epaisseur : 6 mm Hauteur : 60 mm Largeur : 60 mm",
    "basePrice": 18,
    "unitPriceExclTax": 18,
    "VATRate": 10,
    "marginPercent": 20,
    "sellingPrice": 23.76,
    "linearWeight": 6.02,
    "thickness": 6,
    "height": 60,
    "width": 60,
    "diameter": null,
    "circumference": null,
    "sectionArea": 0,
    "weight": null,
    "matiere": "Inox",
    "productCode": 88
  },
  {
    "name": "FER T",
    "description": "Epaisseur : 8 mm Hauteur : 80 mm Largeur : 80 mm",
    "basePrice": 18,
    "unitPriceExclTax": 18,
    "VATRate": 10,
    "marginPercent": 20,
    "sellingPrice": 23.76,
    "linearWeight": 10.7,
    "thickness": 8,
    "height": 80,
    "width": 80,
    "diameter": null,
    "circumference": null,
    "sectionArea": 0,
    "weight": null,
    "matiere": "Inox",
    "productCode": 89
  },
  {
    "name": "FER T",
    "description": "Epaisseur : 9 mm Hauteur : 90 mm Largeur : 90 mm",
    "basePrice": 18,
    "unitPriceExclTax": 18,
    "VATRate": 10,
    "marginPercent": 20,
    "sellingPrice": 23.76,
    "linearWeight": 13.42,
    "thickness": 9,
    "height": 90,
    "width": 90,
    "diameter": null,
    "circumference": null,
    "sectionArea": 0,
    "weight": null,
    "matiere": "Inox",
    "productCode": 90
  },
  {
    "name": "FER T",
    "description": "Epaisseur : 10 mm Hauteur : 100 mm Largeur : 100 mm",
    "basePrice": 18,
    "unitPriceExclTax": 18,
    "VATRate": 10,
    "marginPercent": 20,
    "sellingPrice": 23.76,
    "linearWeight": 16.61,
    "thickness": 10,
    "height": 100,
    "width": 100,
    "diameter": null,
    "circumference": null,
    "sectionArea": 0,
    "weight": null,
    "matiere": "Inox",
    "productCode": 91
  },
  {
    "name": "Tube rond",
    "description": "Diamètre extérieur : 17.2 mm Epaisseur : 1.6 mm",
    "basePrice": 18,
    "unitPriceExclTax": 18,
    "VATRate": 10,
    "marginPercent": 20,
    "sellingPrice": 23.76,
    "linearWeight": 0.69,
    "thickness": 1.6,
    "height": null,
    "width": null,
    "diameter": 17.2,
    "circumference": null,
    "sectionArea": null,
    "weight": null,
    "matiere": "Inox",
    "productCode": 92
  },
  {
    "name": "Tube rond",
    "description": "Diamètre extérieur : 21.3 mm Epaisseur : 1.6 mm",
    "basePrice": 18,
    "unitPriceExclTax": 18,
    "VATRate": 10,
    "marginPercent": 20,
    "sellingPrice": 23.76,
    "linearWeight": 0.87,
    "thickness": 1.6,
    "height": null,
    "width": null,
    "diameter": 21.3,
    "circumference": null,
    "sectionArea": null,
    "weight": null,
    "matiere": "Inox",
    "productCode": 93
  },
  {
    "name": "Tube rond",
    "description": "Diamètre extérieur : 25 mm Epaisseur : 1.5 mm",
    "basePrice": 18,
    "unitPriceExclTax": 18,
    "VATRate": 10,
    "marginPercent": 20,
    "sellingPrice": 23.76,
    "linearWeight": 0.96,
    "thickness": 1.5,
    "height": null,
    "width": null,
    "diameter": 25,
    "circumference": null,
    "sectionArea": null,
    "weight": null,
    "matiere": "Inox",
    "productCode": 94
  },
  {
    "name": "Tube rond",
    "description": "Diamètre extérieur : 25 mm Epaisseur : 2 mm",
    "basePrice": 18,
    "unitPriceExclTax": 18,
    "VATRate": 10,
    "marginPercent": 20,
    "sellingPrice": 23.76,
    "linearWeight": 1.24,
    "thickness": 2,
    "height": null,
    "width": null,
    "diameter": 25,
    "circumference": null,
    "sectionArea": null,
    "weight": null,
    "matiere": "Inox",
    "productCode": 95
  },
  {
    "name": "Tube rond",
    "description": "Diamètre extérieur : 26.9 mm Epaisseur : 1.6 mm",
    "basePrice": 18,
    "unitPriceExclTax": 18,
    "VATRate": 10,
    "marginPercent": 20,
    "sellingPrice": 23.76,
    "linearWeight": 1.11,
    "thickness": 1.6,
    "height": null,
    "width": null,
    "diameter": 26.9,
    "circumference": null,
    "sectionArea": null,
    "weight": null,
    "matiere": "Inox",
    "productCode": 96
  },
  {
    "name": "Tube rond",
    "description": "Diamètre extérieur : 26.9 mm Epaisseur : 2 mm",
    "basePrice": 18,
    "unitPriceExclTax": 18,
    "VATRate": 10,
    "marginPercent": 20,
    "sellingPrice": 23.76,
    "linearWeight": 1.35,
    "thickness": 2,
    "height": null,
    "width": null,
    "diameter": 26.9,
    "circumference": null,
    "sectionArea": null,
    "weight": null,
    "matiere": "Inox",
    "productCode": 97
  },
  {
    "name": "Tube rond",
    "description": "Diamètre extérieur : 30 mm Epaisseur : 2 mm",
    "basePrice": 18,
    "unitPriceExclTax": 18,
    "VATRate": 10,
    "marginPercent": 20,
    "sellingPrice": 23.76,
    "linearWeight": 1.52,
    "thickness": 2,
    "height": null,
    "width": null,
    "diameter": 30,
    "circumference": null,
    "sectionArea": null,
    "weight": null,
    "matiere": "Inox",
    "productCode": 98
  },
  {
    "name": "Tube rond",
    "description": "Diamètre extérieur : 33.7 mm Epaisseur : 1.5 mm",
    "basePrice": 18,
    "unitPriceExclTax": 18,
    "VATRate": 10,
    "marginPercent": 20,
    "sellingPrice": 23.76,
    "linearWeight": 2.43,
    "thickness": 1.5,
    "height": null,
    "width": null,
    "diameter": 33.7,
    "circumference": null,
    "sectionArea": null,
    "weight": null,
    "matiere": "Inox",
    "productCode": 99
  },
  {
    "name": "Tube rond",
    "description": "Diamètre extérieur : 33.7 mm Epaisseur : 2 mm",
    "basePrice": 18,
    "unitPriceExclTax": 18,
    "VATRate": 10,
    "marginPercent": 20,
    "sellingPrice": 23.76,
    "linearWeight": 1.72,
    "thickness": 2,
    "height": null,
    "width": null,
    "diameter": 33.7,
    "circumference": null,
    "sectionArea": null,
    "weight": null,
    "matiere": "Inox",
    "productCode": 100
  },
  {
    "name": "Tube rond",
    "description": "Diamètre extérieur : 33.7 mm Epaisseur : 2.6 mm",
    "basePrice": 18,
    "unitPriceExclTax": 18,
    "VATRate": 10,
    "marginPercent": 20,
    "sellingPrice": 23.76,
    "linearWeight": 2.19,
    "thickness": 2.6,
    "height": null,
    "width": null,
    "diameter": 33.7,
    "circumference": null,
    "sectionArea": null,
    "weight": null,
    "matiere": "Inox",
    "productCode": 101
  },
  {
    "name": "Tube rond",
    "description": "Diamètre extérieur : 35 mm Epaisseur : 2 mm",
    "basePrice": 18,
    "unitPriceExclTax": 18,
    "VATRate": 10,
    "marginPercent": 20,
    "sellingPrice": 23.76,
    "linearWeight": 1.79,
    "thickness": 2,
    "height": null,
    "width": null,
    "diameter": 35,
    "circumference": null,
    "sectionArea": null,
    "weight": null,
    "matiere": "Inox",
    "productCode": 102
  },
  {
    "name": "Tube rond",
    "description": "Diamètre extérieur : 40 mm Epaisseur : 2 mm",
    "basePrice": 18,
    "unitPriceExclTax": 18,
    "VATRate": 10,
    "marginPercent": 20,
    "sellingPrice": 23.76,
    "linearWeight": 2.06,
    "thickness": 2,
    "height": null,
    "width": null,
    "diameter": 40,
    "circumference": null,
    "sectionArea": null,
    "weight": null,
    "matiere": "Inox",
    "productCode": 103
  },
  {
    "name": "Tube rond",
    "description": "Diamètre extérieur : 42.4 mm Epaisseur : 2 mm",
    "basePrice": 18,
    "unitPriceExclTax": 18,
    "VATRate": 10,
    "marginPercent": 20,
    "sellingPrice": 23.76,
    "linearWeight": 2.19,
    "thickness": 2,
    "height": null,
    "width": null,
    "diameter": 42.4,
    "circumference": null,
    "sectionArea": null,
    "weight": null,
    "matiere": "Inox",
    "productCode": 104
  },
  {
    "name": "Tube rond",
    "description": "Diamètre extérieur : 42.4 mm Epaisseur : 3.2 mm",
    "basePrice": 18,
    "unitPriceExclTax": 18,
    "VATRate": 10,
    "marginPercent": 20,
    "sellingPrice": 23.76,
    "linearWeight": 3.4,
    "thickness": 3.2,
    "height": null,
    "width": null,
    "diameter": 42.4,
    "circumference": null,
    "sectionArea": null,
    "weight": null,
    "matiere": "Inox",
    "productCode": 105
  },
  {
    "name": "Tube rond",
    "description": "Diamètre extérieur : 43 mm Epaisseur : 1.5 mm",
    "basePrice": 18,
    "unitPriceExclTax": 18,
    "VATRate": 10,
    "marginPercent": 20,
    "sellingPrice": 23.76,
    "linearWeight": 1.79,
    "thickness": 1.5,
    "height": null,
    "width": null,
    "diameter": 43,
    "circumference": null,
    "sectionArea": null,
    "weight": null,
    "matiere": "Inox",
    "productCode": 106
  },
  {
    "name": "Tube rond",
    "description": "Diamètre extérieur : 48.3 mm Epaisseur : 3.2 mm",
    "basePrice": 18,
    "unitPriceExclTax": 18,
    "VATRate": 10,
    "marginPercent": 20,
    "sellingPrice": 23.76,
    "linearWeight": 3.92,
    "thickness": 3.2,
    "height": null,
    "width": null,
    "diameter": 48.3,
    "circumference": null,
    "sectionArea": null,
    "weight": null,
    "matiere": "Inox",
    "productCode": 107
  },
  {
    "name": "Tube rond",
    "description": "Diamètre extérieur : 60.3 mm Epaisseur : 2 mm",
    "basePrice": 18,
    "unitPriceExclTax": 18,
    "VATRate": 10,
    "marginPercent": 20,
    "sellingPrice": 23.76,
    "linearWeight": 3.21,
    "thickness": 2,
    "height": null,
    "width": null,
    "diameter": 60.3,
    "circumference": null,
    "sectionArea": null,
    "weight": null,
    "matiere": "Inox",
    "productCode": 108
  },
  {
    "name": "Tube rond",
    "description": "Diamètre extérieur : 60.3 mm Epaisseur : 3.6 mm",
    "basePrice": 18,
    "unitPriceExclTax": 18,
    "VATRate": 10,
    "marginPercent": 20,
    "sellingPrice": 23.76,
    "linearWeight": 6.11,
    "thickness": 3.6,
    "height": null,
    "width": null,
    "diameter": 60.3,
    "circumference": null,
    "sectionArea": null,
    "weight": null,
    "matiere": "Inox",
    "productCode": 109
  },
  {
    "name": "Barre ronde pleine",
    "description": "Diamètre : 6 mm Circonfèrence : 18.8 mm",
    "basePrice": 18,
    "unitPriceExclTax": 18,
    "VATRate": 10,
    "marginPercent": 20,
    "sellingPrice": 23.76,
    "linearWeight": 0.24,
    "thickness": null,
    "height": null,
    "width": null,
    "diameter": 6,
    "circumference": 18.8,
    "sectionArea": 0.28,
    "weight": null,
    "matiere": "Inox",
    "productCode": 110
  },
  {
    "name": "Barre ronde pleine",
    "description": "Diamètre : 8 mm Circonfèrence : 25.1 mm",
    "basePrice": 18,
    "unitPriceExclTax": 18,
    "VATRate": 10,
    "marginPercent": 20,
    "sellingPrice": 23.76,
    "linearWeight": 0.43,
    "thickness": null,
    "height": null,
    "width": null,
    "diameter": 8,
    "circumference": 25.1,
    "sectionArea": 0.5,
    "weight": null,
    "matiere": "Inox",
    "productCode": 111
  },
  {
    "name": "Barre ronde pleine",
    "description": "Diamètre : 10 mm Circonfèrence : 31.4 mm",
    "basePrice": 18,
    "unitPriceExclTax": 18,
    "VATRate": 10,
    "marginPercent": 20,
    "sellingPrice": 23.76,
    "linearWeight": 0.68,
    "thickness": null,
    "height": null,
    "width": null,
    "diameter": 10,
    "circumference": 31.4,
    "sectionArea": 0.79,
    "weight": null,
    "matiere": "Inox",
    "productCode": 112
  },
  {
    "name": "Barre ronde pleine",
    "description": "Diamètre : 12 mm Circonfèrence : 37.7 mm",
    "basePrice": 18,
    "unitPriceExclTax": 18,
    "VATRate": 10,
    "marginPercent": 20,
    "sellingPrice": 23.76,
    "linearWeight": 0.98,
    "thickness": null,
    "height": null,
    "width": null,
    "diameter": 12,
    "circumference": 37.7,
    "sectionArea": 1.13,
    "weight": null,
    "matiere": "Inox",
    "productCode": 113
  },
  {
    "name": "Barre ronde pleine",
    "description": "Diamètre : 14 mm Circonfèrence : 44.0 mm",
    "basePrice": 18,
    "unitPriceExclTax": 18,
    "VATRate": 10,
    "marginPercent": 20,
    "sellingPrice": 23.76,
    "linearWeight": 1.33,
    "thickness": null,
    "height": null,
    "width": null,
    "diameter": 14,
    "circumference": 44,
    "sectionArea": 1.54,
    "weight": null,
    "matiere": "Inox",
    "productCode": 114
  },
  {
    "name": "Barre ronde pleine",
    "description": "Diamètre : 16 mm Circonfèrence : 50.3 mm",
    "basePrice": 18,
    "unitPriceExclTax": 18,
    "VATRate": 10,
    "marginPercent": 20,
    "sellingPrice": 23.76,
    "linearWeight": 1.74,
    "thickness": null,
    "height": null,
    "width": null,
    "diameter": 16,
    "circumference": 50.3,
    "sectionArea": 2.01,
    "weight": null,
    "matiere": "Inox",
    "productCode": 115
  },
  {
    "name": "Barre ronde pleine",
    "description": "Diamètre : 18 mm Circonfèrence : 56.5 mm",
    "basePrice": 18,
    "unitPriceExclTax": 18,
    "VATRate": 10,
    "marginPercent": 20,
    "sellingPrice": 23.76,
    "linearWeight": 2.2,
    "thickness": null,
    "height": null,
    "width": null,
    "diameter": 18,
    "circumference": 56.5,
    "sectionArea": 2.54,
    "weight": null,
    "matiere": "Inox",
    "productCode": 116
  },
  {
    "name": "Barre ronde pleine",
    "description": "Diamètre : 20 mm Circonfèrence : 62.8 mm",
    "basePrice": 18,
    "unitPriceExclTax": 18,
    "VATRate": 10,
    "marginPercent": 20,
    "sellingPrice": 23.76,
    "linearWeight": 2.72,
    "thickness": null,
    "height": null,
    "width": null,
    "diameter": 20,
    "circumference": 62.8,
    "sectionArea": 3.14,
    "weight": null,
    "matiere": "Inox",
    "productCode": 117
  },
  {
    "name": "Barre ronde pleine",
    "description": "Diamètre : 25 mm Circonfèrence : 78.5 mm",
    "basePrice": 18,
    "unitPriceExclTax": 18,
    "VATRate": 10,
    "marginPercent": 20,
    "sellingPrice": 23.76,
    "linearWeight": 4.24,
    "thickness": null,
    "height": null,
    "width": null,
    "diameter": 25,
    "circumference": 78.5,
    "sectionArea": 4.91,
    "weight": null,
    "matiere": "Inox",
    "productCode": 118
  },
  {
    "name": "Barre ronde pleine",
    "description": "Diamètre : 30 mm Circonfèrence : 94.2 mm",
    "basePrice": 18,
    "unitPriceExclTax": 18,
    "VATRate": 10,
    "marginPercent": 20,
    "sellingPrice": 23.76,
    "linearWeight": 6.11,
    "thickness": null,
    "height": null,
    "width": null,
    "diameter": 30,
    "circumference": 94.2,
    "sectionArea": 7.07,
    "weight": null,
    "matiere": "Inox",
    "productCode": 119
  },
  {
    "name": "Barre ronde pleine",
    "description": "Diamètre : 40 mm Circonfèrence : 126 mm",
    "basePrice": 18,
    "unitPriceExclTax": 18,
    "VATRate": 10,
    "marginPercent": 20,
    "sellingPrice": 23.76,
    "linearWeight": 10.85,
    "thickness": null,
    "height": null,
    "width": null,
    "diameter": 40,
    "circumference": 126,
    "sectionArea": 12.6,
    "weight": null,
    "matiere": "Inox",
    "productCode": 120
  },
  {
    "name": "Barre ronde pleine",
    "description": "Diamètre : 50 mm Circonfèrence : 157 mm",
    "basePrice": 18,
    "unitPriceExclTax": 18,
    "VATRate": 10,
    "marginPercent": 20,
    "sellingPrice": 23.76,
    "linearWeight": 16.94,
    "thickness": null,
    "height": null,
    "width": null,
    "diameter": 50,
    "circumference": 157,
    "sectionArea": 19.6,
    "weight": null,
    "matiere": "Inox",
    "productCode": 121
  },
  {
    "name": "Barre ronde pleine",
    "description": "Diamètre : 60 mm Circonfèrence : 188 mm",
    "basePrice": 18,
    "unitPriceExclTax": 18,
    "VATRate": 10,
    "marginPercent": 20,
    "sellingPrice": 23.76,
    "linearWeight": 24.42,
    "thickness": null,
    "height": null,
    "width": null,
    "diameter": 60,
    "circumference": 188,
    "sectionArea": 28.3,
    "weight": null,
    "matiere": "Inox",
    "productCode": 122
  },
  {
    "name": "Barre ronde pleine",
    "description": "Diamètre : 80 mm Circonfèrence : 251 mm",
    "basePrice": 18,
    "unitPriceExclTax": 18,
    "VATRate": 10,
    "marginPercent": 20,
    "sellingPrice": 23.76,
    "linearWeight": 43.45,
    "thickness": null,
    "height": null,
    "width": null,
    "diameter": 80,
    "circumference": 251,
    "sectionArea": 50.3,
    "weight": null,
    "matiere": "Inox",
    "productCode": 123
  },
  {
    "name": "Barre ronde pleine",
    "description": "Diamètre : 100 mm Circonfèrence : 314 mm",
    "basePrice": 18,
    "unitPriceExclTax": 18,
    "VATRate": 10,
    "marginPercent": 20,
    "sellingPrice": 23.76,
    "linearWeight": 67.87,
    "thickness": null,
    "height": null,
    "width": null,
    "diameter": 100,
    "circumference": 314,
    "sectionArea": 78.5,
    "weight": null,
    "matiere": "Inox",
    "productCode": 124
  },
  {
    "name": "Fer plat",
    "description": "Epaisseur : 3 mm Largeur : 20 mm",
    "basePrice": 18,
    "unitPriceExclTax": 18,
    "VATRate": 10,
    "marginPercent": 20,
    "sellingPrice": 23.76,
    "linearWeight": 0.52,
    "thickness": 3,
    "width": 20,
    "height": null,
    "diameter": null,
    "circumference": null,
    "sectionArea": null,
    "weight": null,
    "productCode": 125,
    "matiere": "Inox"
  },
  {
    "name": "Fer plat",
    "description": "Epaisseur : 4 mm Largeur : 20 mm",
    "basePrice": 18,
    "unitPriceExclTax": 18,
    "VATRate": 10,
    "marginPercent": 20,
    "sellingPrice": 23.76,
    "linearWeight": 0.7,
    "thickness": 4,
    "width": 20,
    "height": null,
    "diameter": null,
    "circumference": null,
    "sectionArea": null,
    "weight": null,
    "productCode": 126,
    "matiere": "Inox"
  },
  {
    "name": "Fer plat",
    "description": "Epaisseur : 5 mm Largeur : 20 mm",
    "basePrice": 18,
    "unitPriceExclTax": 18,
    "VATRate": 10,
    "marginPercent": 20,
    "sellingPrice": 23.76,
    "linearWeight": 0.87,
    "thickness": 5,
    "width": 20,
    "height": null,
    "diameter": null,
    "circumference": null,
    "sectionArea": null,
    "weight": null,
    "productCode": 127,
    "matiere": "Inox"
  },
  {
    "name": "Fer plat",
    "description": "Epaisseur : 6 mm Largeur : 20 mm",
    "basePrice": 18,
    "unitPriceExclTax": 18,
    "VATRate": 10,
    "marginPercent": 20,
    "sellingPrice": 23.76,
    "linearWeight": 1.03,
    "thickness": 6,
    "width": 20,
    "height": null,
    "diameter": null,
    "circumference": null,
    "sectionArea": null,
    "weight": null,
    "productCode": 128,
    "matiere": "Inox"
  },
  {
    "name": "Fer plat",
    "description": "Epaisseur : 8 mm Largeur : 20 mm",
    "basePrice": 18,
    "unitPriceExclTax": 18,
    "VATRate": 10,
    "marginPercent": 20,
    "sellingPrice": 23.76,
    "linearWeight": 1.43,
    "thickness": 8,
    "width": 20,
    "height": null,
    "diameter": null,
    "circumference": null,
    "sectionArea": null,
    "weight": null,
    "productCode": 129,
    "matiere": "Inox"
  },
  {
    "name": "Fer plat",
    "description": "Epaisseur : 3 mm Largeur : 25 mm",
    "basePrice": 18,
    "unitPriceExclTax": 18,
    "VATRate": 10,
    "marginPercent": 20,
    "sellingPrice": 23.76,
    "linearWeight": 0.66,
    "thickness": 3,
    "width": 25,
    "height": null,
    "diameter": null,
    "circumference": null,
    "sectionArea": null,
    "weight": null,
    "productCode": 130,
    "matiere": "Inox"
  },
  {
    "name": "Fer plat",
    "description": "Epaisseur : 4 mm Largeur : 25 mm",
    "basePrice": 18,
    "unitPriceExclTax": 18,
    "VATRate": 10,
    "marginPercent": 20,
    "sellingPrice": 23.76,
    "linearWeight": 0.88,
    "thickness": 4,
    "width": 25,
    "height": null,
    "diameter": null,
    "circumference": null,
    "sectionArea": null,
    "weight": null,
    "productCode": 131,
    "matiere": "Inox"
  },
  {
    "name": "Fer plat",
    "description": "Epaisseur : 5 mm Largeur : 25 mm",
    "basePrice": 18,
    "unitPriceExclTax": 18,
    "VATRate": 10,
    "marginPercent": 20,
    "sellingPrice": 23.76,
    "linearWeight": 1.08,
    "thickness": 5,
    "width": 25,
    "height": null,
    "diameter": null,
    "circumference": null,
    "sectionArea": null,
    "weight": null,
    "productCode": 132,
    "matiere": "Inox"
  },
  {
    "name": "Fer plat",
    "description": "Epaisseur : 6 mm Largeur : 25 mm",
    "basePrice": 18,
    "unitPriceExclTax": 18,
    "VATRate": 10,
    "marginPercent": 20,
    "sellingPrice": 23.76,
    "linearWeight": 1.3,
    "thickness": 6,
    "width": 25,
    "height": null,
    "diameter": null,
    "circumference": null,
    "sectionArea": null,
    "weight": null,
    "productCode": 133,
    "matiere": "Inox"
  },
  {
    "name": "Fer plat",
    "description": "Epaisseur : 8 mm Largeur : 25 mm",
    "basePrice": 18,
    "unitPriceExclTax": 18,
    "VATRate": 10,
    "marginPercent": 20,
    "sellingPrice": 23.76,
    "linearWeight": 1.73,
    "thickness": 8,
    "width": 25,
    "height": null,
    "diameter": null,
    "circumference": null,
    "sectionArea": null,
    "weight": null,
    "productCode": 134,
    "matiere": "Inox"
  },
  {
    "name": "Cornière à ailes égales",
    "description": "Epaisseur : 3 mm Hauteur Ailes : 30 mm",
    "basePrice": 6,
    "unitPriceExclTax": 6,
    "VATRate": 10,
    "marginPercent": 20,
    "sellingPrice": 7.92,
    "linearWeight": 1.5,
    "thickness": 3,
    "height": 30,
    "width": null,
    "diameter": null,
    "circumference": null,
    "sectionArea": 1.74,
    "weight": null,
    "productCode": 135,
    "matiere": "Galvanisé"
  },
  {
    "name": "Cornière à ailes égales",
    "description": "Epaisseur : 3.5 mm Hauteur Ailes : 35 mm",
    "basePrice": 6,
    "unitPriceExclTax": 6,
    "VATRate": 10,
    "marginPercent": 20,
    "sellingPrice": 7.92,
    "linearWeight": 2.04,
    "thickness": 3.5,
    "height": 35,
    "width": null,
    "diameter": null,
    "circumference": null,
    "sectionArea": 2.35,
    "weight": null,
    "productCode": 136,
    "matiere": "Galvanisé"
  },
  {
    "name": "Cornière à ailes égales",
    "description": "Epaisseur : 4 mm Hauteur Ailes : 40 mm",
    "basePrice": 6,
    "unitPriceExclTax": 6,
    "VATRate": 10,
    "marginPercent": 20,
    "sellingPrice": 7.92,
    "linearWeight": 2.66,
    "thickness": 4,
    "height": 40,
    "width": null,
    "diameter": null,
    "circumference": null,
    "sectionArea": 3.08,
    "weight": null,
    "productCode": 137,
    "matiere": "Galvanisé"
  },
  {
    "name": "Cornière à ailes égales",
    "description": "Epaisseur : 5 mm Hauteur Ailes : 50 mm",
    "basePrice": 6,
    "unitPriceExclTax": 6,
    "VATRate": 10,
    "marginPercent": 20,
    "sellingPrice": 7.92,
    "linearWeight": 4.15,
    "thickness": 5,
    "height": 50,
    "width": null,
    "diameter": null,
    "circumference": null,
    "sectionArea": 4.8,
    "weight": null,
    "productCode": 138,
    "matiere": "Galvanisé"
  },
  {
    "name": "Tube rond SENDZINIR NF EN 10305-3 S4",
    "description": "Diamètre extérieur : 21.3 mm Epaisseur : 2.3 mm",
    "basePrice": 6,
    "unitPriceExclTax": 6,
    "VATRate": 10,
    "marginPercent": 20,
    "sellingPrice": 7.92,
    "linearWeight": 1.18,
    "thickness": 2.3,
    "height": null,
    "width": null,
    "diameter": 21.3,
    "circumference": null,
    "sectionArea": null,
    "weight": null,
    "productCode": 139,
    "matiere": "Galvanisé"
  },
  {
    "name": "Tube rond SENDZINIR NF EN 10305-3 S4",
    "description": "Diamètre extérieur : 26.9 mm Epaisseur : 2.3 mm",
    "basePrice": 6,
    "unitPriceExclTax": 6,
    "VATRate": 10,
    "marginPercent": 20,
    "sellingPrice": 7.92,
    "linearWeight": 1.54,
    "thickness": 2.3,
    "height": null,
    "width": null,
    "diameter": 26.9,
    "circumference": null,
    "sectionArea": null,
    "weight": null,
    "productCode": 140,
    "matiere": "Galvanisé"
  },
  {
    "name": "Tube rond SENDZINIR NF EN 10305-3 S4",
    "description": "Diamètre extérieur : 30 mm Epaisseur : 1.5 mm",
    "basePrice": 6,
    "unitPriceExclTax": 6,
    "VATRate": 10,
    "marginPercent": 20,
    "sellingPrice": 7.92,
    "linearWeight": 1.28,
    "thickness": 1.5,
    "height": null,
    "width": null,
    "diameter": 30,
    "circumference": null,
    "sectionArea": null,
    "weight": null,
    "productCode": 141,
    "matiere": "Galvanisé"
  },
  {
    "name": "Tube rond SENDZINIR NF EN 10305-3 S4",
    "description": "Diamètre extérieur : 33.7 mm Epaisseur : 2.9 mm",
    "basePrice": 6,
    "unitPriceExclTax": 6,
    "VATRate": 10,
    "marginPercent": 20,
    "sellingPrice": 7.92,
    "linearWeight": 2.42,
    "thickness": 2.9,
    "height": null,
    "width": null,
    "diameter": 33.7,
    "circumference": null,
    "sectionArea": null,
    "weight": null,
    "productCode": 142,
    "matiere": "Galvanisé"
  },
  {
    "name": "Tube rond SENDZINIR NF EN 10305-3 S4",
    "description": "Diamètre extérieur : 40 mm Epaisseur : 1.5 mm",
    "basePrice": 6,
    "unitPriceExclTax": 6,
    "VATRate": 10,
    "marginPercent": 20,
    "sellingPrice": 7.92,
    "linearWeight": 1.72,
    "thickness": 1.5,
    "height": null,
    "width": null,
    "diameter": 40,
    "circumference": null,
    "sectionArea": null,
    "weight": null,
    "productCode": 143,
    "matiere": "Galvanisé"
  },
  {
    "name": "Tube rond SENDZINIR NF EN 10305-3 S4",
    "description": "Diamètre extérieur : 42.4 mm Epaisseur : 2.9 mm",
    "basePrice": 6,
    "unitPriceExclTax": 6,
    "VATRate": 10,
    "marginPercent": 20,
    "sellingPrice": 7.92,
    "linearWeight": 3.1,
    "thickness": 2.9,
    "height": null,
    "width": null,
    "diameter": 42.4,
    "circumference": null,
    "sectionArea": null,
    "weight": null,
    "productCode": 144,
    "matiere": "Galvanisé"
  },
  {
    "name": "Tube rond SENDZINIR NF EN 10305-3 S4",
    "description": "Diamètre extérieur : 48.3 mm Epaisseur : 2.9 mm",
    "basePrice": 6,
    "unitPriceExclTax": 6,
    "VATRate": 10,
    "marginPercent": 20,
    "sellingPrice": 7.92,
    "linearWeight": 3.58,
    "thickness": 2.9,
    "height": null,
    "width": null,
    "diameter": 48.3,
    "circumference": null,
    "sectionArea": null,
    "weight": null,
    "productCode": 145,
    "matiere": "Galvanisé"
  },
  {
    "name": "Tube rond SENDZINIR NF EN 10305-3 S4",
    "description": "Diamètre extérieur : 50 mm Epaisseur : 1.5 mm",
    "basePrice": 6,
    "unitPriceExclTax": 6,
    "VATRate": 10,
    "marginPercent": 20,
    "sellingPrice": 7.92,
    "linearWeight": 2.16,
    "thickness": 1.5,
    "height": null,
    "width": null,
    "diameter": 50,
    "circumference": null,
    "sectionArea": null,
    "weight": null,
    "productCode": 146,
    "matiere": "Galvanisé"
  },
  {
    "name": "Tube rond SENDZINIR NF EN 10305-3 S4",
    "description": "Diamètre extérieur : 50 mm Epaisseur : 2 mm",
    "basePrice": 6,
    "unitPriceExclTax": 6,
    "VATRate": 10,
    "marginPercent": 20,
    "sellingPrice": 7.92,
    "linearWeight": 2.61,
    "thickness": 2,
    "height": null,
    "width": null,
    "diameter": 50,
    "circumference": null,
    "sectionArea": null,
    "weight": null,
    "productCode": 147,
    "matiere": "Galvanisé"
  },
  {
    "name": "Tube rond SENDZINIR NF EN 10305-3 S4",
    "description": "Diamètre extérieur : 60 mm Epaisseur : 1.5 mm",
    "basePrice": 6,
    "unitPriceExclTax": 6,
    "VATRate": 10,
    "marginPercent": 20,
    "sellingPrice": 7.92,
    "linearWeight": 2.6,
    "thickness": 1.5,
    "height": null,
    "width": null,
    "diameter": 60,
    "circumference": null,
    "sectionArea": null,
    "weight": null,
    "productCode": 148,
    "matiere": "Galvanisé"
  },
  {
    "name": "Tube rond SENDZINIR NF EN 10305-3 S4",
    "description": "Diamètre extérieur : 60 mm Epaisseur : 2 mm",
    "basePrice": 6,
    "unitPriceExclTax": 6,
    "VATRate": 10,
    "marginPercent": 20,
    "sellingPrice": 7.92,
    "linearWeight": 3.45,
    "thickness": 2,
    "height": null,
    "width": null,
    "diameter": 60,
    "circumference": null,
    "sectionArea": null,
    "weight": null,
    "productCode": 149,
    "matiere": "Galvanisé"
  },
  {
    "name": "Tube carré SENDZINIR NF EN 10305-3 S4",
    "description": "Hauteur : 20 mm Epaisseur : 1.5 mm",
    "basePrice": 6,
    "unitPriceExclTax": 6,
    "VATRate": 10,
    "marginPercent": 20,
    "sellingPrice": 7.92,
    "linearWeight": 0.96,
    "thickness": 1.5,
    "height": 20,
    "width": 20,
    "diameter": null,
    "circumference": null,
    "sectionArea": null,
    "weight": null,
    "productCode": 150,
    "matiere": "Galvanisé"
  },
  {
    "name": "Tube carré SENDZINIR NF EN 10305-3 S4",
    "description": "Hauteur : 25 mm Epaisseur : 1.5 mm",
    "basePrice": 6,
    "unitPriceExclTax": 6,
    "VATRate": 10,
    "marginPercent": 20,
    "sellingPrice": 7.92,
    "linearWeight": 1.22,
    "thickness": 1.5,
    "height": 25,
    "width": 25,
    "diameter": null,
    "circumference": null,
    "sectionArea": null,
    "weight": null,
    "productCode": 151,
    "matiere": "Galvanisé"
  },
  {
    "name": "Tube carré SENDZINIR NF EN 10305-3 S4",
    "description": "Hauteur : 25 mm Epaisseur : 2 mm",
    "basePrice": 6,
    "unitPriceExclTax": 6,
    "VATRate": 10,
    "marginPercent": 20,
    "sellingPrice": 7.92,
    "linearWeight": 1.58,
    "thickness": 2,
    "height": 25,
    "width": 25,
    "diameter": null,
    "circumference": null,
    "sectionArea": null,
    "weight": null,
    "productCode": 152,
    "matiere": "Galvanisé"
  },
  {
    "name": "Tube carré SENDZINIR NF EN 10305-3 S4",
    "description": "Hauteur : 30 mm Epaisseur : 2 mm",
    "basePrice": 6,
    "unitPriceExclTax": 6,
    "VATRate": 10,
    "marginPercent": 20,
    "sellingPrice": 7.92,
    "linearWeight": 1.94,
    "thickness": 2,
    "height": 30,
    "width": 30,
    "diameter": null,
    "circumference": null,
    "sectionArea": null,
    "weight": null,
    "productCode": 153,
    "matiere": "Galvanisé"
  },
  {
    "name": "Tube carré SENDZINIR NF EN 10305-3 S4",
    "description": "Hauteur : 35 mm Epaisseur : 2 mm",
    "basePrice": 6,
    "unitPriceExclTax": 6,
    "VATRate": 10,
    "marginPercent": 20,
    "sellingPrice": 7.92,
    "linearWeight": 2.28,
    "thickness": 2,
    "height": 35,
    "width": 35,
    "diameter": null,
    "circumference": null,
    "sectionArea": null,
    "weight": null,
    "productCode": 154,
    "matiere": "Galvanisé"
  },
  {
    "name": "Tube carré SENDZINIR NF EN 10305-3 S4",
    "description": "Hauteur : 40 mm Epaisseur : 2 mm",
    "basePrice": 6,
    "unitPriceExclTax": 6,
    "VATRate": 10,
    "marginPercent": 20,
    "sellingPrice": 7.92,
    "linearWeight": 2.63,
    "thickness": 2,
    "height": 40,
    "width": 40,
    "diameter": null,
    "circumference": null,
    "sectionArea": null,
    "weight": null,
    "productCode": 155,
    "matiere": "Galvanisé"
  },
  {
    "name": "Tube carré SENDZINIR NF EN 10305-3 S4",
    "description": "Hauteur : 50 mm Epaisseur : 2 mm",
    "basePrice": 6,
    "unitPriceExclTax": 6,
    "VATRate": 10,
    "marginPercent": 20,
    "sellingPrice": 7.92,
    "linearWeight": 3.32,
    "thickness": 2,
    "height": 50,
    "width": 50,
    "diameter": null,
    "circumference": null,
    "sectionArea": null,
    "weight": null,
    "productCode": 156,
    "matiere": "Galvanisé"
  },
  {
    "name": "Tube carré SENDZINIR NF EN 10305-3 S4",
    "description": "Hauteur : 60 mm Epaisseur : 2 mm",
    "basePrice": 6,
    "unitPriceExclTax": 6,
    "VATRate": 10,
    "marginPercent": 20,
    "sellingPrice": 7.92,
    "linearWeight": 3.95,
    "thickness": 2,
    "height": 60,
    "width": 60,
    "diameter": null,
    "circumference": null,
    "sectionArea": null,
    "weight": null,
    "productCode": 157,
    "matiere": "Galvanisé"
  },
  {
    "name": "Tube carré SENDZINIR NF EN 10305-3 S4",
    "description": "Hauteur : 80 mm Epaisseur : 2 mm",
    "basePrice": 6,
    "unitPriceExclTax": 6,
    "VATRate": 10,
    "marginPercent": 20,
    "sellingPrice": 7.92,
    "linearWeight": 5.39,
    "thickness": 2,
    "height": 80,
    "width": 80,
    "diameter": null,
    "circumference": null,
    "sectionArea": null,
    "weight": null,
    "productCode": 158,
    "matiere": "Galvanisé"
  },
  {
    "name": "Tube carré SENDZINIR NF EN 10305-3 S4",
    "description": "Hauteur : 100 mm Epaisseur : 2 mm",
    "basePrice": 6,
    "unitPriceExclTax": 6,
    "VATRate": 10,
    "marginPercent": 20,
    "sellingPrice": 7.92,
    "linearWeight": 7.45,
    "thickness": 2,
    "height": 100,
    "width": 100,
    "diameter": null,
    "circumference": null,
    "sectionArea": null,
    "weight": null,
    "productCode": 159,
    "matiere": "Galvanisé"
  },
  {
    "name": "Tube carré SENDZINIR NF EN 10305-3 S4",
    "description": "Hauteur : 100 mm Epaisseur : 3 mm",
    "basePrice": 6,
    "unitPriceExclTax": 6,
    "VATRate": 10,
    "marginPercent": 20,
    "sellingPrice": 7.92,
    "linearWeight": 9.92,
    "thickness": 3,
    "height": 100,
    "width": 100,
    "diameter": null,
    "circumference": null,
    "sectionArea": null,
    "weight": null,
    "productCode": 160,
    "matiere": "Galvanisé"
  },
  {
    "name": "Tube rectangulaire SENDZINIR NF EN 10305-3 S4",
    "description": "Hauteur : 35 mm Largeur : 20 mm Epaisseur : 2 mm",
    "basePrice": 6,
    "unitPriceExclTax": 6,
    "VATRate": 10,
    "marginPercent": 20,
    "sellingPrice": 7.92,
    "linearWeight": 1.76,
    "thickness": 2,
    "height": 35,
    "width": 20,
    "diameter": null,
    "circumference": null,
    "sectionArea": null,
    "weight": null,
    "productCode": 161,
    "matiere": "Galvanisé"
  },
  {
    "name": "Tube rectangulaire SENDZINIR NF EN 10305-3 S4",
    "description": "Hauteur : 40 mm Largeur : 20 mm Epaisseur : 2 mm",
    "basePrice": 6,
    "unitPriceExclTax": 6,
    "VATRate": 10,
    "marginPercent": 20,
    "sellingPrice": 7.92,
    "linearWeight": 1.94,
    "thickness": 2,
    "height": 40,
    "width": 20,
    "diameter": null,
    "circumference": null,
    "sectionArea": null,
    "weight": null,
    "productCode": 162,
    "matiere": "Galvanisé"
  },
  {
    "name": "Tube rectangulaire SENDZINIR NF EN 10305-3 S4",
    "description": "Hauteur : 40 mm Largeur : 27 mm Epaisseur : 2 mm",
    "basePrice": 6,
    "unitPriceExclTax": 6,
    "VATRate": 10,
    "marginPercent": 20,
    "sellingPrice": 7.92,
    "linearWeight": 2.18,
    "thickness": 2,
    "height": 40,
    "width": 27,
    "diameter": null,
    "circumference": null,
    "sectionArea": null,
    "weight": null,
    "productCode": 163,
    "matiere": "Galvanisé"
  },
  {
    "name": "Tube rectangulaire SENDZINIR NF EN 10305-3 S4",
    "description": "Hauteur : 50 mm Largeur : 30 mm Epaisseur : 2 mm",
    "basePrice": 6,
    "unitPriceExclTax": 6,
    "VATRate": 10,
    "marginPercent": 20,
    "sellingPrice": 7.92,
    "linearWeight": 2.63,
    "thickness": 2,
    "height": 50,
    "width": 30,
    "diameter": null,
    "circumference": null,
    "sectionArea": null,
    "weight": null,
    "productCode": 164,
    "matiere": "Galvanisé"
  },
  {
    "name": "Tube rectangulaire SENDZINIR NF EN 10305-3 S4",
    "description": "Hauteur : 60 mm Largeur : 30 mm Epaisseur : 2 mm",
    "basePrice": 6,
    "unitPriceExclTax": 6,
    "VATRate": 10,
    "marginPercent": 20,
    "sellingPrice": 7.92,
    "linearWeight": 2.97,
    "thickness": 2,
    "height": 60,
    "width": 30,
    "diameter": null,
    "circumference": null,
    "sectionArea": null,
    "weight": null,
    "productCode": 165,
    "matiere": "Galvanisé"
  },
  {
    "name": "Tube rectangulaire SENDZINIR NF EN 10305-3 S4",
    "description": "Hauteur : 60 mm Largeur : 40 mm Epaisseur : 2 mm",
    "basePrice": 6,
    "unitPriceExclTax": 6,
    "VATRate": 10,
    "marginPercent": 20,
    "sellingPrice": 7.92,
    "linearWeight": 3.32,
    "thickness": 2,
    "height": 60,
    "width": 40,
    "diameter": null,
    "circumference": null,
    "sectionArea": null,
    "weight": null,
    "productCode": 166,
    "matiere": "Galvanisé"
  },
  {
    "name": "Tube rectangulaire SENDZINIR NF EN 10305-3 S4",
    "description": "Hauteur : 80 mm Largeur : 40 mm Epaisseur : 2 mm",
    "basePrice": 6,
    "unitPriceExclTax": 6,
    "VATRate": 10,
    "marginPercent": 20,
    "sellingPrice": 7.92,
    "linearWeight": 4,
    "thickness": 2,
    "height": 80,
    "width": 40,
    "diameter": null,
    "circumference": null,
    "sectionArea": null,
    "weight": null,
    "productCode": 167,
    "matiere": "Galvanisé"
  },
  {
    "name": "Tube rectangulaire SENDZINIR NF EN 10305-3 S4",
    "description": "Hauteur : 100 mm Largeur : 20 mm Epaisseur : 2 mm",
    "basePrice": 6,
    "unitPriceExclTax": 6,
    "VATRate": 10,
    "marginPercent": 20,
    "sellingPrice": 7.92,
    "linearWeight": 4.31,
    "thickness": 2,
    "height": 100,
    "width": 20,
    "diameter": null,
    "circumference": null,
    "sectionArea": null,
    "weight": null,
    "productCode": 168,
    "matiere": "Galvanisé"
  },
  {
    "name": "Tube rectangulaire SENDZINIR NF EN 10305-3 S4",
    "description": "Hauteur : 100 mm Largeur : 50 mm Epaisseur : 2 mm",
    "basePrice": 6,
    "unitPriceExclTax": 6,
    "VATRate": 10,
    "marginPercent": 20,
    "sellingPrice": 7.92,
    "linearWeight": 4.9,
    "thickness": 2,
    "height": 100,
    "width": 50,
    "diameter": null,
    "circumference": null,
    "sectionArea": null,
    "weight": null,
    "productCode": 169,
    "matiere": "Galvanisé"
  },
  {
    "name": "Tôle perforée",
    "description": "Épaisseur : 1.5 mm Trous ronds diamètre 10 mm",
    "basePrice": 8.5,
    "unitPriceExclTax": 8.5,
    "VATRate": 10,
    "marginPercent": 20,
    "sellingPrice": 11.22,
    "linearWeight": 12.98,
    "thickness": 1.5,
    "height": null,
    "width": null,
    "diameter": null,
    "circumference": null,
    "sectionArea": null,
    "weight": 12.98,
    "productCode": 170,
    "matiere": "Galvanisé"
  },
  {
    "name": "Tôle perforée",
    "description": "Épaisseur : 2 mm Trous ronds diamètre 5 mm",
    "basePrice": 8.5,
    "unitPriceExclTax": 8.5,
    "VATRate": 10,
    "marginPercent": 20,
    "sellingPrice": 11.22,
    "linearWeight": 17.27,
    "thickness": 2,
    "height": null,
    "width": null,
    "diameter": null,
    "circumference": null,
    "sectionArea": null,
    "weight": 17.27,
    "productCode": 171,
    "matiere": "Galvanisé"
  },
  {
    "name": "Tôle perforée",
    "description": "Épaisseur : 1.5 mm Trous carré 10/10 mm",
    "basePrice": 8.5,
    "unitPriceExclTax": 8.5,
    "VATRate": 10,
    "marginPercent": 20,
    "sellingPrice": 11.22,
    "linearWeight": 12.98,
    "thickness": 1.5,
    "height": null,
    "width": null,
    "diameter": null,
    "circumference": null,
    "sectionArea": null,
    "weight": 12.98,
    "productCode": 172,
    "matiere": "Galvanisé"
  }
]
