import { Injectable } from '@angular/core';

@Injectable({
  providedIn: 'root',
})
export class MatiereDataService {
  constructor() {}

  // Aluminium
  fer_t_aluminium = [
    {
      id: 0,
      epaisseur: 2,
      hauteur: 25,
      largeur: 25,
      masseKgM: 0.29,
      pxKg: 20,
      nomProd: 'FER T ( Epaisseur : 2 mm Hauteur : 25 mm Largeur : 25 mm)',
    },
    {
      id: 1,
      epaisseur: 2,
      hauteur: 30,
      largeur: 30,
      masseKgM: 0.34,
      pxKg: 20,
      nomProd: 'FER T ( Epaisseur : 2 mm Hauteur : 30 mm Largeur : 30 mm)',
    },
    {
      id: 2,
      epaisseur: 3,
      hauteur: 30,
      largeur: 30,
      masseKgM: 0.51,
      pxKg: 20,
      nomProd: 'FER T ( Epaisseur : 3 mm Hauteur : 30 mm Largeur : 30 mm)',
    },
    {
      id: 3,
      epaisseur: 3,
      hauteur: 40,
      largeur: 40,
      masseKgM: 0.68,
      pxKg: 20,
      nomProd: 'FER T ( Epaisseur : 3 mm Hauteur : 40 mm Largeur : 40 mm)',
    },
    {
      id: 4,
      epaisseur: 4,
      hauteur: 40,
      largeur: 40,
      masseKgM: 0.9,
      pxKg: 20,
      nomProd: 'FER T ( Epaisseur : 4 mm Hauteur : 40 mm Largeur : 40 mm)',
    },
    {
      id: 5,
      epaisseur: 5,
      hauteur: 50,
      largeur: 50,
      masseKgM: 1.41,
      pxKg: 20,
      nomProd: 'FER T ( Epaisseur : 5 mm Hauteur : 50 mm Largeur : 50 mm)',
    },
    {
      id: 6,
      epaisseur: 6,
      hauteur: 60,
      largeur: 60,
      masseKgM: 2.04,
      pxKg: 20,
      nomProd: 'FER T ( Epaisseur : 6 mm Hauteur : 60 mm Largeur : 60 mm)',
    },
    {
      id: 7,
      epaisseur: 8,
      hauteur: 80,
      largeur: 80,
      masseKgM: 3.61,
      pxKg: 20,
      nomProd: 'FER T ( Epaisseur : 8 mm Hauteur : 80 mm Largeur : 80 mm)',
    },
  ];
  corniere_egale_aluminium = [
    {
      id: 0,
      epaisseur: 1.5,
      hauteurAiles: 15,
      masse: 0.13,
      section: 0,
      pxKg: 20,
      pxKgGalva: 6,
      description:
        'Cornière à ailes égales ( Epaisseur : 1.5 mm Hauteur Ailes : 15 mm)',
    },
    {
      id: 1,
      epaisseur: 2,
      hauteurAiles: 15,
      masse: 0.17,
      section: 0,
      pxKg: 20,
      pxKgGalva: 6,
      description:
        'Cornière à ailes égales ( Epaisseur : 2 mm Hauteur Ailes : 15 mm)',
    },
    {
      id: 2,
      epaisseur: 1.5,
      hauteurAiles: 20,
      masse: 0.18,
      section: 0,
      pxKg: 20,
      pxKgGalva: 6,
      description:
        'Cornière à ailes égales ( Epaisseur : 1.5 mm Hauteur Ailes : 20 mm)',
    },
    {
      id: 3,
      epaisseur: 2,
      hauteurAiles: 20,
      masse: 0.22,
      section: 0,
      pxKg: 20,
      pxKgGalva: 6,
      description:
        'Cornière à ailes égales ( Epaisseur : 2 mm Hauteur Ailes : 20 mm)',
    },
    {
      id: 4,
      epaisseur: 2,
      hauteurAiles: 25,
      masse: 0.29,
      section: 0,
      pxKg: 20,
      pxKgGalva: 6,
      description:
        'Cornière à ailes égales ( Epaisseur : 2 mm Hauteur Ailes : 25 mm)',
    },
    {
      id: 5,
      epaisseur: 2,
      hauteurAiles: 30,
      masse: 0.34,
      section: 0,
      pxKg: 20,
      pxKgGalva: 6,
      description:
        'Cornière à ailes égales ( Epaisseur : 2 mm Hauteur Ailes : 30 mm)',
    },
    {
      id: 6,
      epaisseur: 3,
      hauteurAiles: 30,
      masse: 0.51,
      section: 0,
      pxKg: 20,
      pxKgGalva: 6,
      description:
        'Cornière à ailes égales ( Epaisseur : 3 mm Hauteur Ailes : 30 mm)',
    },
    {
      id: 7,
      epaisseur: 3,
      hauteurAiles: 35,
      masse: 0.59,
      section: 0,
      pxKg: 20,
      pxKgGalva: 6,
      description:
        'Cornière à ailes égales ( Epaisseur : 3 mm Hauteur Ailes : 35 mm)',
    },
    {
      id: 8,
      epaisseur: 2,
      hauteurAiles: 40,
      masse: 0.46,
      section: 0,
      pxKg: 20,
      pxKgGalva: 6,
      description:
        'Cornière à ailes égales ( Epaisseur : 2 mm Hauteur Ailes : 40 mm)',
    },
    {
      id: 9,
      epaisseur: 3,
      hauteurAiles: 40,
      masse: 0.68,
      section: 0,
      pxKg: 20,
      pxKgGalva: 6,
      description:
        'Cornière à ailes égales ( Epaisseur : 3 mm Hauteur Ailes : 40 mm)',
    },
    {
      id: 10,
      epaisseur: 4,
      hauteurAiles: 40,
      masse: 0.9,
      section: 0,
      pxKg: 20,
      pxKgGalva: 6,
      description:
        'Cornière à ailes égales ( Epaisseur : 4 mm Hauteur Ailes : 40 mm)',
    },
    {
      id: 11,
      epaisseur: 2,
      hauteurAiles: 50,
      masse: 0.58,
      section: 0,
      pxKg: 20,
      pxKgGalva: 6,
      description:
        'Cornière à ailes égales ( Epaisseur : 2 mm Hauteur Ailes : 50 mm)',
    },
    {
      id: 12,
      epaisseur: 3,
      hauteurAiles: 50,
      masse: 0.87,
      section: 0,
      pxKg: 20,
      pxKgGalva: 6,
      description:
        'Cornière à ailes égales ( Epaisseur : 3 mm Hauteur Ailes : 50 mm)',
    },
    {
      id: 13,
      epaisseur: 4,
      hauteurAiles: 50,
      masse: 1.14,
      section: 0,
      pxKg: 20,
      pxKgGalva: 6,
      description:
        'Cornière à ailes égales ( Epaisseur : 4 mm Hauteur Ailes : 50 mm)',
    },
    {
      id: 14,
      epaisseur: 5,
      hauteurAiles: 50,
      masse: 1.41,
      section: 0,
      pxKg: 20,
      pxKgGalva: 6,
      description:
        'Cornière à ailes égales ( Epaisseur : 5 mm Hauteur Ailes : 50 mm)',
    },
    {
      id: 15,
      epaisseur: 2,
      hauteurAiles: 60,
      masse: 0.7,
      section: 0,
      pxKg: 20,
      pxKgGalva: 6,
      description:
        'Cornière à ailes égales ( Epaisseur : 2 mm Hauteur Ailes : 60 mm)',
    },
    {
      id: 16,
      epaisseur: 4,
      hauteurAiles: 60,
      masse: 1.38,
      section: 0,
      pxKg: 20,
      pxKgGalva: 6,
      description:
        'Cornière à ailes égales ( Epaisseur : 4 mm Hauteur Ailes : 60 mm)',
    },
    {
      id: 17,
      epaisseur: 6,
      hauteurAiles: 60,
      masse: 2.02,
      section: 0,
      pxKg: 20,
      pxKgGalva: 6,
      description:
        'Cornière à ailes égales ( Epaisseur : 6 mm Hauteur Ailes : 60 mm)',
    },
    {
      id: 18,
      epaisseur: 8,
      hauteurAiles: 80,
      masse: 3.61,
      section: 0,
      pxKg: 20,
      pxKgGalva: 6,
      description:
        'Cornière à ailes égales ( Epaisseur : 8 mm Hauteur Ailes : 80 mm)',
    },
    {
      id: 19,
      epaisseur: 10,
      hauteurAiles: 100,
      masse: 5.64,
      section: 0,
      pxKg: 20,
      pxKgGalva: 6,
      description:
        'Cornière à ailes égales ( Epaisseur : 10 mm Hauteur Ailes : 100 mm)',
    },
  ];
    /*
  ! A supprimer
  */
  profile_h_aluminium = [
    {
      id: 0,
      h: 140,
      a: 8,
      b: 8,
      c: 140,
      d: 90,
      masseKgM: 7.66,
      pxKg: 20,
      pxKgGalva: 6,
      nom: "Profilé H ( H : 140 mm Epaisseur de la Semelle : 8 mm Epaisseur de l'âme : 8 mm Hauteur de l'âme : 140 mm Largeur de la Semelle : 90 mm)",
    },
  ];
  profile_u_aluminium = [
    {
      choix: 10,
      U: 10,
      epaisseur: 2,
      hauteur: 10,
      largeur: 10,
      masse: 0.15,
      pxKg: 0,
      pxKgGalva: 'alu',
      hidden: 20,
      nom: "Profilé U ( U : 10 mm Epaisseur de l'âme : 2 mm Hauteur de l'âme : 10 mm Largeur de la Semelle : 10 mm)",
    },
    {
      choix: 15,
      U: 15,
      epaisseur: 2,
      hauteur: 15,
      largeur: 15,
      masse: 0.24,
      pxKg: 0,
      pxKgGalva: 'alu',
      hidden: 20,
      nom: "Profilé U ( U : 15 mm Epaisseur de l'âme : 2 mm Hauteur de l'âme : 15 mm Largeur de la Semelle : 15 mm)",
    },
    {
      choix: 20,
      U: 20,
      epaisseur: 2,
      hauteur: 20,
      largeur: 20,
      masse: 0.33,
      pxKg: 0,
      pxKgGalva: 'alu',
      hidden: 20,
      nom: "Profilé U ( U : 20 mm Epaisseur de l'âme : 2 mm Hauteur de l'âme : 20 mm Largeur de la Semelle : 20 mm)",
    },
    {
      choix: 25,
      U: 25,
      epaisseur: 2,
      hauteur: 25,
      largeur: 25,
      masse: 0.42,
      pxKg: 0,
      pxKgGalva: 'alu',
      hidden: 20,
      nom: "Profilé U ( U : 25 mm Epaisseur de l'âme : 2 mm Hauteur de l'âme : 25 mm Largeur de la Semelle : 25 mm)",
    },
    {
      choix: 25,
      U: 25,
      epaisseur: 2.5,
      hauteur: 25,
      largeur: 25,
      masse: 0.52,
      pxKg: 0,
      pxKgGalva: 'alu',
      hidden: 20,
      nom: "Profilé U ( U : 25 mm Epaisseur de l'âme : 2.5 mm Hauteur de l'âme : 25 mm Largeur de la Semelle : 25 mm)",
    },
    {
      choix: 30,
      U: 30,
      epaisseur: 2,
      hauteur: 30,
      largeur: 20,
      masse: 0.4,
      pxKg: 0,
      pxKgGalva: 'alu',
      hidden: 20,
      nom: "Profilé U ( U : 30 mm Epaisseur de l'âme : 2 mm Hauteur de l'âme : 30 mm Largeur de la Semelle : 20 mm)",
    },
    {
      choix: 30,
      U: 30,
      epaisseur: 2,
      hauteur: 30,
      largeur: 30,
      masse: 0.51,
      pxKg: 0,
      pxKgGalva: 'alu',
      hidden: 20,
      nom: "Profilé U ( U : 30 mm Epaisseur de l'âme : 2 mm Hauteur de l'âme : 30 mm Largeur de la Semelle : 30 mm)",
    },
    {
      choix: 30,
      U: 30,
      epaisseur: 3,
      hauteur: 30,
      largeur: 30,
      masse: 0.75,
      pxKg: 0,
      pxKgGalva: 'alu',
      hidden: 20,
      nom: "Profilé U ( U : 30 mm Epaisseur de l'âme : 3 mm Hauteur de l'âme : 30 mm Largeur de la Semelle : 30 mm)",
    },
    {
      choix: 40,
      U: 40,
      epaisseur: 2,
      hauteur: 40,
      largeur: 20,
      masse: 0.45,
      pxKg: 0,
      pxKgGalva: 'alu',
      hidden: 20,
      nom: "Profilé U ( U : 40 mm Epaisseur de l'âme : 2 mm Hauteur de l'âme : 40 mm Largeur de la Semelle : 20 mm)",
    },
    {
      choix: 40,
      U: 40,
      epaisseur: 2,
      hauteur: 40,
      largeur: 40,
      masse: 0.68,
      pxKg: 0,
      pxKgGalva: 'alu',
      hidden: 20,
      nom: "Profilé U ( U : 40 mm Epaisseur de l'âme : 2 mm Hauteur de l'âme : 40 mm Largeur de la Semelle : 40 mm)",
    },
    {
      choix: 40,
      U: 40,
      epaisseur: 4,
      hauteur: 40,
      largeur: 40,
      masse: 1.33,
      pxKg: 0,
      pxKgGalva: 'alu',
      hidden: 20,
      nom: "Profilé U ( U : 40 mm Epaisseur de l'âme : 4 mm Hauteur de l'âme : 40 mm Largeur de la Semelle : 40 mm)",
    },
    {
      choix: 50,
      U: 50,
      epaisseur: 2.5,
      hauteur: 50,
      largeur: 25,
      masse: 0.7,
      pxKg: 0,
      pxKgGalva: 'alu',
      hidden: 20,
      nom: "Profilé U ( U : 50 mm Epaisseur de l'âme : 2.5 mm Hauteur de l'âme : 50 mm Largeur de la Semelle : 25 mm)",
    },
    {
      choix: 50,
      U: 50,
      epaisseur: 3,
      hauteur: 50,
      largeur: 30,
      masse: 0.92,
      pxKg: 0,
      pxKgGalva: 'alu',
      hidden: 20,
      nom: "Profilé U ( U : 50 mm Epaisseur de l'âme : 3 mm Hauteur de l'âme : 50 mm Largeur de la Semelle : 30 mm)",
    },
    {
      choix: 50,
      U: 50,
      epaisseur: 4,
      hauteur: 50,
      largeur: 30,
      masse: 1.21,
      pxKg: 0,
      pxKgGalva: 'alu',
      hidden: 20,
      nom: "Profilé U ( U : 50 mm Epaisseur de l'âme : 4 mm Hauteur de l'âme : 50 mm Largeur de la Semelle : 30 mm)",
    },
    {
      choix: 60,
      U: 60,
      epaisseur: 4,
      hauteur: 60,
      largeur: 40,
      masse: 1.57,
      pxKg: 0,
      pxKgGalva: 'alu',
      hidden: 20,
      nom: "Profilé U ( U : 60 mm Epaisseur de l'âme : 4 mm Hauteur de l'âme : 60 mm Largeur de la Semelle : 40 mm)",
    },
    {
      choix: 80,
      U: 80,
      epaisseur: 4,
      hauteur: 80,
      largeur: 40,
      masse: 1.8,
      pxKg: 0,
      pxKgGalva: 'alu',
      hidden: 20,
      nom: "Profilé U ( U : 80 mm Epaisseur de l'âme : 4 mm Hauteur de l'âme : 80 mm Largeur de la Semelle : 40 mm)",
    },
    {
      choix: 80,
      U: 80,
      epaisseur: 5,
      hauteur: 80,
      largeur: 40,
      masse: 2.22,
      pxKg: 0,
      pxKgGalva: 'alu',
      hidden: 20,
      nom: "Profilé U ( U : 80 mm Epaisseur de l'âme : 5 mm Hauteur de l'âme : 80 mm Largeur de la Semelle : 40 mm)",
    },
    {
      choix: 80,
      U: 80,
      epaisseur: 5,
      hauteur: 80,
      largeur: 50,
      masse: 2.52,
      pxKg: 0,
      pxKgGalva: 'alu',
      hidden: 20,
      nom: "Profilé U ( U : 80 mm Epaisseur de l'âme : 5 mm Hauteur de l'âme : 80 mm Largeur de la Semelle : 50 mm)",
    },
    {
      choix: 100,
      U: 100,
      epaisseur: 5,
      hauteur: 100,
      largeur: 50,
      masse: 2.88,
      pxKg: 0,
      pxKgGalva: 'alu',
      hidden: 20,
      nom: "Profilé U ( U : 100 mm Epaisseur de l'âme : 5 mm Hauteur de l'âme : 100 mm Largeur de la Semelle : 50 mm)",
    },
    {
      choix: 100,
      U: 100,
      epaisseur: 6,
      hauteur: 100,
      largeur: 50,
      masse: 3.54,
      pxKg: 0,
      pxKgGalva: 'alu',
      hidden: 20,
      nom: "Profilé U ( U : 100 mm Epaisseur de l'âme : 6 mm Hauteur de l'âme : 100 mm Largeur de la Semelle : 50 mm)",
    },
  ];
  /*
  ! A supprimer
  */
  tube_rectangulaire_aluminium = [
    {
      choix: 0,
      hauteur: 25,
      largeur: 15,
      epaisseur: 2,
      masse: 0.43,
      pxKg: 20,
      pxKgGalva: 6,
      nom: 'Tube rectangulaire ( Hauteur : 25 mm Largeur : 15 mm Epaisseur : 2 mm)',
    },
    {
      choix: 1,
      hauteur: 30,
      largeur: 15,
      epaisseur: 1.5,
      masse: 0.37,
      pxKg: 20,
      pxKgGalva: 6,
      nom: 'Tube rectangulaire ( Hauteur : 30 mm Largeur : 15 mm Epaisseur : 1.5 mm)',
    },
    {
      choix: 2,
      hauteur: 30,
      largeur: 20,
      epaisseur: 2,
      masse: 0.55,
      pxKg: 20,
      pxKgGalva: 6,
      nom: 'Tube rectangulaire ( Hauteur : 30 mm Largeur : 20 mm Epaisseur : 2 mm)',
    },
    {
      choix: 3,
      hauteur: 40,
      largeur: 20,
      epaisseur: 2,
      masse: 0.66,
      pxKg: 20,
      pxKgGalva: 6,
      nom: 'Tube rectangulaire ( Hauteur : 40 mm Largeur : 20 mm Epaisseur : 2 mm)',
    },
    {
      choix: 4,
      hauteur: 40,
      largeur: 20,
      epaisseur: 3,
      masse: 0.97,
      pxKg: 20,
      pxKgGalva: 6,
      nom: 'Tube rectangulaire ( Hauteur : 40 mm Largeur : 20 mm Epaisseur : 3 mm)',
    },
    {
      choix: 5,
      hauteur: 40,
      largeur: 20,
      epaisseur: 4,
      masse: 1.23,
      pxKg: 30,
      pxKgGalva: 30,
      nom: 'Tube rectangulaire ( Hauteur : 40 mm Largeur : 20 mm Epaisseur : 4 mm)',
    },
    {
      choix: 6,
      hauteur: 50,
      largeur: 20,
      epaisseur: 2,
      masse: 0.78,
      pxKg: 20,
      pxKgGalva: 6,
      nom: 'Tube rectangulaire ( Hauteur : 50 mm Largeur : 20 mm Epaisseur : 2 mm)',
    },
    {
      choix: 7,
      hauteur: 50,
      largeur: 25,
      epaisseur: 2,
      masse: 0.85,
      pxKg: 20,
      pxKgGalva: 6,
      nom: 'Tube rectangulaire ( Hauteur : 50 mm Largeur : 25 mm Epaisseur : 2 mm)',
    },
    {
      choix: 8,
      hauteur: 50,
      largeur: 30,
      epaisseur: 2,
      masse: 0.9,
      pxKg: 20,
      pxKgGalva: 6,
      nom: 'Tube rectangulaire ( Hauteur : 50 mm Largeur : 30 mm Epaisseur : 2 mm)',
    },
    {
      choix: 9,
      hauteur: 50,
      largeur: 30,
      epaisseur: 3,
      masse: 1.32,
      pxKg: 20,
      pxKgGalva: 6,
      nom: 'Tube rectangulaire ( Hauteur : 50 mm Largeur : 30 mm Epaisseur : 3 mm)',
    },
    {
      choix: 10,
      hauteur: 60,
      largeur: 30,
      epaisseur: 2,
      masse: 1.02,
      pxKg: 20,
      pxKgGalva: 6,
      nom: 'Tube rectangulaire ( Hauteur : 60 mm Largeur : 30 mm Epaisseur : 2 mm)',
    },
    {
      choix: 11,
      hauteur: 60,
      largeur: 30,
      epaisseur: 3,
      masse: 1.5,
      pxKg: 20,
      pxKgGalva: 6,
      nom: 'Tube rectangulaire ( Hauteur : 60 mm Largeur : 30 mm Epaisseur : 3 mm)',
    },
    {
      choix: 12,
      hauteur: 60,
      largeur: 40,
      epaisseur: 2,
      masse: 1.14,
      pxKg: 20,
      pxKgGalva: 6,
      nom: 'Tube rectangulaire ( Hauteur : 60 mm Largeur : 40 mm Epaisseur : 2 mm)',
    },
    {
      choix: 13,
      hauteur: 60,
      largeur: 40,
      epaisseur: 3,
      masse: 1.67,
      pxKg: 20,
      pxKgGalva: 6,
      nom: 'Tube rectangulaire ( Hauteur : 60 mm Largeur : 40 mm Epaisseur : 3 mm)',
    },
    {
      choix: 14,
      hauteur: 60,
      largeur: 40,
      epaisseur: 4,
      masse: 2.18,
      pxKg: 30,
      pxKgGalva: 30,
      nom: 'Tube rectangulaire ( Hauteur : 60 mm Largeur : 40 mm Epaisseur : 4 mm)',
    },
    {
      choix: 15,
      hauteur: 80,
      largeur: 20,
      epaisseur: 2,
      masse: 1.14,
      pxKg: 20,
      pxKgGalva: 6,
      nom: 'Tube rectangulaire ( Hauteur : 80 mm Largeur : 20 mm Epaisseur : 2 mm)',
    },
    {
      choix: 16,
      hauteur: 80,
      largeur: 40,
      epaisseur: 2,
      masse: 1.38,
      pxKg: 20,
      pxKgGalva: 6,
      nom: 'Tube rectangulaire ( Hauteur : 80 mm Largeur : 40 mm Epaisseur : 2 mm)',
    },
    {
      choix: 17,
      hauteur: 80,
      largeur: 40,
      epaisseur: 3,
      masse: 2.04,
      pxKg: 20,
      pxKgGalva: 6,
      nom: 'Tube rectangulaire ( Hauteur : 80 mm Largeur : 40 mm Epaisseur : 3 mm)',
    },
    {
      choix: 18,
      hauteur: 80,
      largeur: 40,
      epaisseur: 4,
      masse: 2.65,
      pxKg: 30,
      pxKgGalva: 30,
      nom: 'Tube rectangulaire ( Hauteur : 80 mm Largeur : 40 mm Epaisseur : 4 mm)',
    },
    {
      choix: 19,
      hauteur: 80,
      largeur: 50,
      epaisseur: 5,
      masse: 3.56,
      pxKg: 30,
      pxKgGalva: 30,
      nom: 'Tube rectangulaire ( Hauteur : 80 mm Largeur : 50 mm Epaisseur : 5 mm)',
    },
  ];

  //Inox
  corniere_egale_inox = [
    {
      choix: 0,
      epaisseur: 3,
      hauteurAiles: 20,
      masse: 0.97,
      section: 1.13,
      pxKg: 18,
      pxKgGalva: 6,
      nom: 'Cornière à ailes égales (Epaisseur : 3 mm Hauteur Ailes : 20 mm)',
    },
    {
      choix: 1,
      epaisseur: 3,
      hauteurAiles: 25,
      masse: 1.23,
      section: 1.43,
      pxKg: 18,
      pxKgGalva: 6,
      nom: 'Cornière à ailes égales (Epaisseur : 3 mm Hauteur Ailes : 25 mm)',
    },
    {
      choix: 2,
      epaisseur: 3,
      hauteurAiles: 30,
      masse: 1.5,
      section: 1.74,
      pxKg: 18,
      pxKgGalva: 6,
      nom: 'Cornière à ailes égales (Epaisseur : 3 mm Hauteur Ailes : 30 mm)',
    },
    {
      choix: 3,
      epaisseur: 4,
      hauteurAiles: 40,
      masse: 2.66,
      section: 3.08,
      pxKg: 18,
      pxKgGalva: 6,
      nom: 'Cornière à ailes égales (Epaisseur : 4 mm Hauteur Ailes : 40 mm)',
    },
    {
      choix: 4,
      epaisseur: 5,
      hauteurAiles: 50,
      masse: 4.15,
      section: 4.8,
      pxKg: 18,
      pxKgGalva: 6,
      nom: 'Cornière à ailes égales (Epaisseur : 5 mm Hauteur Ailes : 50 mm)',
    },
    {
      choix: 5,
      epaisseur: 6,
      hauteurAiles: 60,
      masse: 5.96,
      section: 6.91,
      pxKg: 18,
      pxKgGalva: 6,
      nom: 'Cornière à ailes égales (Epaisseur : 6 mm Hauteur Ailes : 60 mm)',
    },
    {
      choix: 6,
      epaisseur: 7,
      hauteurAiles: 70,
      masse: 8.12,
      section: 9.4,
      pxKg: 18,
      pxKgGalva: 6,
      nom: 'Cornière à ailes égales (Epaisseur : 7 mm Hauteur Ailes : 70 mm)',
    },
    {
      choix: 7,
      epaisseur: 8,
      hauteurAiles: 80,
      masse: 10.59,
      section: 12.3,
      pxKg: 18,
      pxKgGalva: 6,
      nom: 'Cornière à ailes égales (Epaisseur : 8 mm Hauteur Ailes : 80 mm)',
    },
    {
      choix: 8,
      epaisseur: 10,
      hauteurAiles: 100,
      masse: 16.5,
      section: 19.2,
      pxKg: 18,
      pxKgGalva: 6,
      nom: 'Cornière à ailes égales (Epaisseur : 10 mm Hauteur Ailes : 100 mm)',
    },
  ];
  fer_t_inox = [
    {
      choix: 0,
      epaisseur: 3,
      hauteur: 20,
      largeur: 20,
      masse: 0.97,
      section: 0,
      pxKg: 18,
      pxKgGalva: 6,
      nom: 'FER T ( Epaisseur : 3 mm Hauteur : 20 mm Largeur : 20 mm)',
    },
    {
      choix: 1,
      epaisseur: 4,
      hauteur: 20,
      largeur: 20,
      masse: 1.32,
      section: 0,
      pxKg: 18,
      pxKgGalva: 6,
      nom: 'FER T ( Epaisseur : 4 mm Hauteur : 20 mm Largeur : 20 mm)',
    },
    {
      choix: 2,
      epaisseur: 3,
      hauteur: 30,
      largeur: 30,
      masse: 1.51,
      section: 0,
      pxKg: 18,
      pxKgGalva: 6,
      nom: 'FER T ( Epaisseur : 3 mm Hauteur : 30 mm Largeur : 30 mm)',
    },
    {
      choix: 3,
      epaisseur: 4,
      hauteur: 40,
      largeur: 40,
      masse: 2.67,
      section: 0,
      pxKg: 18,
      pxKgGalva: 6,
      nom: 'FER T ( Epaisseur : 4 mm Hauteur : 40 mm Largeur : 40 mm)',
    },
    {
      choix: 4,
      epaisseur: 5,
      hauteur: 50,
      largeur: 50,
      masse: 4.18,
      section: 0,
      pxKg: 18,
      pxKgGalva: 6,
      nom: 'FER T ( Epaisseur : 5 mm Hauteur : 50 mm Largeur : 50 mm)',
    },
    {
      choix: 5,
      epaisseur: 6,
      hauteur: 60,
      largeur: 60,
      masse: 6.02,
      section: 0,
      pxKg: 18,
      pxKgGalva: 6,
      nom: 'FER T ( Epaisseur : 6 mm Hauteur : 60 mm Largeur : 60 mm)',
    },
    {
      choix: 6,
      epaisseur: 8,
      hauteur: 80,
      largeur: 80,
      masse: 10.7,
      section: 0,
      pxKg: 18,
      pxKgGalva: 6,
      nom: 'FER T ( Epaisseur : 8 mm Hauteur : 80 mm Largeur : 80 mm)',
    },
    {
      choix: 7,
      epaisseur: 9,
      hauteur: 90,
      largeur: 90,
      masse: 13.42,
      section: 0,
      pxKg: 18,
      pxKgGalva: 6,
      nom: 'FER T ( Epaisseur : 9 mm Hauteur : 90 mm Largeur : 90 mm)',
    },
    {
      choix: 8,
      epaisseur: 10,
      hauteur: 100,
      largeur: 100,
      masse: 16.61,
      section: 0,
      pxKg: 18,
      pxKgGalva: 6,
      nom: 'FER T ( Epaisseur : 10 mm Hauteur : 100 mm Largeur : 100 mm)',
    },
  ];
  poutrelle_hea_heb_inox = [
    {
      Choix: 0,
      HEB_HEA: 100,
      A: 10,
      B: 6,
      C: 100,
      D: 100,
      Masse_kg_m: 23.1,
      Section: 0,
      px_kg: 'inox',
      px_kg_val: 50,
      px_kg_galva: 50,
      nom_prod:
        "Poutrelle HEB ( HEB/HEA : 100 mm Epaisseur de la Semelle : 10 mm Epaisseur de l'âme : 6 mm Hauteur de l'âme : 100 mm Largeur de la Semelle : 100 mm)",
    },
    {
      Choix: 1,
      HEB_HEA: 120,
      A: 11,
      B: 6.5,
      C: 120,
      D: 120,
      Masse_kg_m: 30.25,
      Section: 0,
      px_kg: 'inox',
      px_kg_val: 50,
      px_kg_galva: 50,
      nom_prod:
        "Poutrelle HEB ( HEB/HEA : 120 mm Epaisseur de la Semelle : 11 mm Epaisseur de l'âme : 6.5 mm Hauteur de l'âme : 120 mm Largeur de la Semelle : 120 mm)",
    },
    {
      Choix: 2,
      HEB_HEA: 140,
      A: 12,
      B: 7,
      C: 140,
      D: 140,
      Masse_kg_m: 38.17,
      Section: 0,
      px_kg: 'inox',
      px_kg_val: 50,
      px_kg_galva: 50,
      nom_prod:
        "Poutrelle HEB ( HEB/HEA : 140 mm Epaisseur de la Semelle : 12 mm Epaisseur de l'âme : 7 mm Hauteur de l'âme : 140 mm Largeur de la Semelle : 140 mm)",
    },
    {
      Choix: 3,
      HEB_HEA: 150,
      A: 10,
      B: 7,
      C: 150,
      D: 150,
      Masse_kg_m: 34.98,
      Section: 0,
      px_kg: 'inox',
      px_kg_val: 50,
      px_kg_galva: 50,
      nom_prod:
        "Poutrelle HEB ( HEB/HEA : 150 mm Epaisseur de la Semelle : 10 mm Epaisseur de l'âme : 7 mm Hauteur de l'âme : 150 mm Largeur de la Semelle : 150 mm)",
    },
    {
      Choix: 4,
      HEB_HEA: 160,
      A: 10,
      B: 7,
      C: 160,
      D: 161,
      Masse_kg_m: 47.19,
      Section: 0,
      px_kg: 'inox',
      px_kg_val: 50,
      px_kg_galva: 50,
      nom_prod:
        "Poutrelle HEB ( HEB/HEA : 160 mm Epaisseur de la Semelle : 10 mm Epaisseur de l'âme : 7 mm Hauteur de l'âme : 160 mm Largeur de la Semelle : 161 mm)",
    },
    {
      Choix: 5,
      HEB_HEA: 180,
      A: 15,
      B: 15,
      C: 180,
      D: 180,
      Masse_kg_m: 68.42,
      Section: 0,
      px_kg: 'inox',
      px_kg_val: 50,
      px_kg_galva: 50,
      nom_prod:
        "Poutrelle HEB ( HEB/HEA : 180 mm Epaisseur de la Semelle : 15 mm Epaisseur de l'âme : 15 mm Hauteur de l'âme : 180 mm Largeur de la Semelle : 180 mm)",
    },
    {
      Choix: 6,
      HEB_HEA: 200,
      A: 12,
      B: 8,
      C: 200,
      D: 200,
      Masse_kg_m: 55.44,
      Section: 0,
      px_kg: 'inox',
      px_kg_val: 50,
      px_kg_galva: 50,
      nom_prod:
        "Poutrelle HEB ( HEB/HEA : 200 mm Epaisseur de la Semelle : 12 mm Epaisseur de l'âme : 8 mm Hauteur de l'âme : 200 mm Largeur de la Semelle : 200 mm)",
    },
    {
      Choix: 7,
      HEB_HEA: 250,
      A: 14,
      B: 9,
      C: 250,
      D: 250,
      Masse_kg_m: 79.64,
      Section: 0,
      px_kg: 'inox',
      px_kg_val: 50,
      px_kg_galva: 50,
      nom_prod:
        "Poutrelle HEB ( HEB/HEA : 250 mm Epaisseur de la Semelle : 14 mm Epaisseur de l'âme : 9 mm Hauteur de l'âme : 250 mm Largeur de la Semelle : 250 mm)",
    },
  ];

  tube_rond_inox_304l = [
    {
      id: 0,
      diametre_exterieur: 17.2,
      epaisseur: 1.6,
      masse_kg_m: 0.69,
      px_kg: 18,
      px_kg_galva: 6,
      description:
        'Tube rond ( Diamètre extérieur : 17.2 mm Epaisseur : 1.6 mm)',
    },
    {
      id: 1,
      diametre_exterieur: 21.3,
      epaisseur: 1.6,
      masse_kg_m: 0.87,
      px_kg: 18,
      px_kg_galva: 6,
      description:
        'Tube rond ( Diamètre extérieur : 21.3 mm Epaisseur : 1.6 mm)',
    },
    {
      id: 2,
      diametre_exterieur: 25,
      epaisseur: 1.5,
      masse_kg_m: 0.96,
      px_kg: 18,
      px_kg_galva: 6,
      description: 'Tube rond ( Diamètre extérieur : 25 mm Epaisseur : 1.5 mm)',
    },
    {
      id: 3,
      diametre_exterieur: 25,
      epaisseur: 2,
      masse_kg_m: 1.24,
      px_kg: 18,
      px_kg_galva: 6,
      description: 'Tube rond ( Diamètre extérieur : 25 mm Epaisseur : 2 mm)',
    },
    {
      id: 4,
      diametre_exterieur: 26.9,
      epaisseur: 1.6,
      masse_kg_m: 1.11,
      px_kg: 18,
      px_kg_galva: 6,
      description:
        'Tube rond ( Diamètre extérieur : 26.9 mm Epaisseur : 1.6 mm)',
    },
    {
      id: 5,
      diametre_exterieur: 26.9,
      epaisseur: 2,
      masse_kg_m: 1.35,
      px_kg: 18,
      px_kg_galva: 6,
      description: 'Tube rond ( Diamètre extérieur : 26.9 mm Epaisseur : 2 mm)',
    },
    {
      id: 6,
      diametre_exterieur: 30,
      epaisseur: 2,
      masse_kg_m: 1.52,
      px_kg: 18,
      px_kg_galva: 6,
      description: 'Tube rond ( Diamètre extérieur : 30 mm Epaisseur : 2 mm)',
    },
    {
      id: 7,
      diametre_exterieur: 33.7,
      epaisseur: 1.5,
      masse_kg_m: 2.43,
      px_kg: 18,
      px_kg_galva: 6,
      description:
        'Tube rond ( Diamètre extérieur : 33.7 mm Epaisseur : 1.5 mm)',
    },
    {
      id: 8,
      diametre_exterieur: 33.7,
      epaisseur: 2,
      masse_kg_m: 1.72,
      px_kg: 18,
      px_kg_galva: 6,
      description: 'Tube rond ( Diamètre extérieur : 33.7 mm Epaisseur : 2 mm)',
    },
    {
      id: 9,
      diametre_exterieur: 33.7,
      epaisseur: 2.6,
      masse_kg_m: 2.19,
      px_kg: 18,
      px_kg_galva: 6,
      description:
        'Tube rond ( Diamètre extérieur : 33.7 mm Epaisseur : 2.6 mm)',
    },
    {
      id: 10,
      diametre_exterieur: 35,
      epaisseur: 2,
      masse_kg_m: 1.79,
      px_kg: 18,
      px_kg_galva: 6,
      description: 'Tube rond ( Diamètre extérieur : 35 mm Epaisseur : 2 mm)',
    },
    {
      id: 11,
      diametre_exterieur: 40,
      epaisseur: 2,
      masse_kg_m: 2.06,
      px_kg: 18,
      px_kg_galva: 6,
      description: 'Tube rond ( Diamètre extérieur : 40 mm Epaisseur : 2 mm)',
    },
    {
      id: 12,
      diametre_exterieur: 42.4,
      epaisseur: 2,
      masse_kg_m: 2.19,
      px_kg: 18,
      px_kg_galva: 6,
      description: 'Tube rond ( Diamètre extérieur : 42.4 mm Epaisseur : 2 mm)',
    },
    {
      id: 13,
      diametre_exterieur: 42.4,
      epaisseur: 3.2,
      masse_kg_m: 3.4,
      px_kg: 18,
      px_kg_galva: 6,
      description:
        'Tube rond ( Diamètre extérieur : 42.4 mm Epaisseur : 3.2 mm)',
    },
    {
      id: 14,
      diametre_exterieur: 43,
      epaisseur: 1.5,
      masse_kg_m: 1.79,
      px_kg: 18,
      px_kg_galva: 6,
      description: 'Tube rond ( Diamètre extérieur : 43 mm Epaisseur : 1.5 mm)',
    },
    {
      id: 15,
      diametre_exterieur: 48.3,
      epaisseur: 3.2,
      masse_kg_m: 3.92,
      px_kg: 18,
      px_kg_galva: 6,
      description:
        'Tube rond ( Diamètre extérieur : 48.3 mm Epaisseur : 3.2 mm)',
    },
    {
      id: 16,
      diametre_exterieur: 60.3,
      epaisseur: 2,
      masse_kg_m: 3.21,
      px_kg: 18,
      px_kg_galva: 6,
      description: 'Tube rond ( Diamètre extérieur : 60.3 mm Epaisseur : 2 mm)',
    },
    {
      id: 17,
      diametre_exterieur: 60.3,
      epaisseur: 3.6,
      masse_kg_m: 6.11,
      px_kg: 18,
      px_kg_galva: 6,
      description:
        'Tube rond ( Diamètre extérieur : 60.3 mm Epaisseur : 3.6 mm)',
    },
  ];

  barre_rond_plein_inox_304l = [
    {
      id: 0,
      diametre: 6,
      circonference: 18.8,
      masse_kg_m: 0.24,
      section_cm2: 0.28,
      px_kg: 18,
      px_kg_galva: 6,
      description:
        'Barre rond plein ( Diamètre : 6 mm Circonfèrence : 18.8 mm)',
    },
    {
      id: 1,
      diametre: 8,
      circonference: 25.1,
      masse_kg_m: 0.43,
      section_cm2: 0.5,
      px_kg: 18,
      px_kg_galva: 6,
      description:
        'Barre rond plein ( Diamètre : 8 mm Circonfèrence : 25.1 mm)',
    },
    {
      id: 2,
      diametre: 10,
      circonference: 31.4,
      masse_kg_m: 0.68,
      section_cm2: 0.79,
      px_kg: 18,
      px_kg_galva: 6,
      description:
        'Barre rond plein ( Diamètre : 10 mm Circonfèrence : 31.4 mm)',
    },
    {
      id: 3,
      diametre: 12,
      circonference: 37.7,
      masse_kg_m: 0.98,
      section_cm2: 1.13,
      px_kg: 18,
      px_kg_galva: 6,
      description:
        'Barre rond plein ( Diamètre : 12 mm Circonfèrence : 37.7 mm)',
    },
    {
      id: 4,
      diametre: 14,
      circonference: 44.0,
      masse_kg_m: 1.33,
      section_cm2: 1.54,
      px_kg: 18,
      px_kg_galva: 6,
      description:
        'Barre rond plein ( Diamètre : 14 mm Circonfèrence : 44.0 mm)',
    },
    {
      id: 5,
      diametre: 16,
      circonference: 50.3,
      masse_kg_m: 1.74,
      section_cm2: 2.01,
      px_kg: 18,
      px_kg_galva: 6,
      description:
        'Barre rond plein ( Diamètre : 16 mm Circonfèrence : 50.3 mm)',
    },
    {
      id: 6,
      diametre: 18,
      circonference: 56.5,
      masse_kg_m: 2.2,
      section_cm2: 2.54,
      px_kg: 18,
      px_kg_galva: 6,
      description:
        'Barre rond plein ( Diamètre : 18 mm Circonfèrence : 56.5 mm)',
    },
    {
      id: 7,
      diametre: 20,
      circonference: 62.8,
      masse_kg_m: 2.72,
      section_cm2: 3.14,
      px_kg: 18,
      px_kg_galva: 6,
      description:
        'Barre rond plein ( Diamètre : 20 mm Circonfèrence : 62.8 mm)',
    },
    {
      id: 8,
      diametre: 25,
      circonference: 78.5,
      masse_kg_m: 4.24,
      section_cm2: 4.91,
      px_kg: 18,
      px_kg_galva: 6,
      description:
        'Barre rond plein ( Diamètre : 25 mm Circonfèrence : 78.5 mm)',
    },
    {
      id: 9,
      diametre: 30,
      circonference: 94.2,
      masse_kg_m: 6.11,
      section_cm2: 7.07,
      px_kg: 18,
      px_kg_galva: 6,
      description:
        'Barre rond plein ( Diamètre : 30 mm Circonfèrence : 94.2 mm)',
    },
    {
      id: 10,
      diametre: 40,
      circonference: 126,
      masse_kg_m: 10.85,
      section_cm2: 12.6,
      px_kg: 18,
      px_kg_galva: 6,
      description:
        'Barre rond plein ( Diamètre : 40 mm Circonfèrence : 126 mm)',
    },
    {
      id: 11,
      diametre: 50,
      circonference: 157,
      masse_kg_m: 16.94,
      section_cm2: 19.6,
      px_kg: 18,
      px_kg_galva: 6,
      description:
        'Barre rond plein ( Diamètre : 50 mm Circonfèrence : 157 mm)',
    },
    {
      id: 12,
      diametre: 60,
      circonference: 188,
      masse_kg_m: 24.42,
      section_cm2: 28.3,
      px_kg: 18,
      px_kg_galva: 6,
      description:
        'Barre rond plein ( Diamètre : 60 mm Circonfèrence : 188 mm)',
    },
    {
      id: 13,
      diametre: 80,
      circonference: 251,
      masse_kg_m: 43.45,
      section_cm2: 50.3,
      px_kg: 18,
      px_kg_galva: 6,
      description:
        'Barre rond plein ( Diamètre : 80 mm Circonfèrence : 251 mm)',
    },
    {
      id: 14,
      diametre: 100,
      circonference: 314,
      masse_kg_m: 67.87,
      section_cm2: 78.5,
      px_kg: 18,
      px_kg_galva: 6,
      description:
        'Barre rond plein ( Diamètre : 100 mm Circonfèrence : 314 mm)',
    },
  ];

  //Acier
  cornieres_ailes_egales_acier = [
    {
      choix: 0,
      epaisseur: 3,
      hauteurAiles: 20,
      masseKgPerM: 0.97,
      sectionCm2: 1.13,
      pxKg: 3,
      pxKgGalva: 6,
      description:
        'Cornière à ailes égales ( Epaisseur : 3 mm Hauteur Ailes : 20 mm)',
    },
    {
      choix: 1,
      epaisseur: 3,
      hauteurAiles: 25,
      masseKgPerM: 1.23,
      sectionCm2: 1.43,
      pxKg: 3,
      pxKgGalva: 6,
      description:
        'Cornière à ailes égales ( Epaisseur : 3 mm Hauteur Ailes : 25 mm)',
    },
    {
      choix: 2,
      epaisseur: 3,
      hauteurAiles: 30,
      masseKgPerM: 1.5,
      sectionCm2: 1.74,
      pxKg: 3,
      pxKgGalva: 6,
      description:
        'Cornière à ailes égales ( Epaisseur : 3 mm Hauteur Ailes : 30 mm)',
    },
    {
      choix: 3,
      epaisseur: 3.5,
      hauteurAiles: 35,
      masseKgPerM: 2.04,
      sectionCm2: 2.35,
      pxKg: 3,
      pxKgGalva: 6,
      description:
        'Cornière à ailes égales ( Epaisseur : 3.5 mm Hauteur Ailes : 35 mm)',
    },
    {
      choix: 4,
      epaisseur: 4,
      hauteurAiles: 40,
      masseKgPerM: 2.66,
      sectionCm2: 3.08,
      pxKg: 3,
      pxKgGalva: 6,
      description:
        'Cornière à ailes égales ( Epaisseur : 4 mm Hauteur Ailes : 40 mm)',
    },
    {
      choix: 5,
      epaisseur: 4.5,
      hauteurAiles: 45,
      masseKgPerM: 3.37,
      sectionCm2: 3.9,
      pxKg: 3,
      pxKgGalva: 6,
      description:
        'Cornière à ailes égales ( Epaisseur : 4.5 mm Hauteur Ailes : 45 mm)',
    },
    {
      choix: 6,
      epaisseur: 5,
      hauteurAiles: 50,
      masseKgPerM: 4.15,
      sectionCm2: 4.8,
      pxKg: 3,
      pxKgGalva: 6,
      description:
        'Cornière à ailes égales ( Epaisseur : 5 mm Hauteur Ailes : 50 mm)',
    },
    {
      choix: 7,
      epaisseur: 6,
      hauteurAiles: 60,
      masseKgPerM: 5.96,
      sectionCm2: 6.91,
      pxKg: 3,
      pxKgGalva: 6,
      description:
        'Cornière à ailes égales ( Epaisseur : 6 mm Hauteur Ailes : 60 mm)',
    },
    {
      choix: 8,
      epaisseur: 7,
      hauteurAiles: 70,
      masseKgPerM: 8.12,
      sectionCm2: 9.4,
      pxKg: 3,
      pxKgGalva: 6,
      description:
        'Cornière à ailes égales ( Epaisseur : 7 mm Hauteur Ailes : 70 mm)',
    },
    {
      choix: 9,
      epaisseur: 8,
      hauteurAiles: 80,
      masseKgPerM: 10.59,
      sectionCm2: 12.3,
      pxKg: 3,
      pxKgGalva: 6,
      description:
        'Cornière à ailes égales ( Epaisseur : 8 mm Hauteur Ailes : 80 mm)',
    },
    {
      choix: 10,
      epaisseur: 9,
      hauteurAiles: 90,
      masseKgPerM: 13.42,
      sectionCm2: 15.5,
      pxKg: 3,
      pxKgGalva: 6,
      description:
        'Cornière à ailes égales ( Epaisseur : 9 mm Hauteur Ailes : 90 mm)',
    },
    {
      choix: 11,
      epaisseur: 10,
      hauteurAiles: 100,
      masseKgPerM: 16.5,
      sectionCm2: 19.2,
      pxKg: 3,
      pxKgGalva: 6,
      description:
        'Cornière à ailes égales ( Epaisseur : 10 mm Hauteur Ailes : 100 mm)',
    },
    {
      choix: 12,
      epaisseur: 12,
      hauteurAiles: 120,
      masseKgPerM: 23.76,
      sectionCm2: 27.5,
      pxKg: 3,
      pxKgGalva: 6,
      description:
        'Cornière à ailes égales ( Epaisseur : 12 mm Hauteur Ailes : 120 mm)',
    },
    {
      choix: 13,
      epaisseur: 15,
      hauteurAiles: 150,
      masseKgPerM: 37.18,
      sectionCm2: 43.0,
      pxKg: 3,
      pxKgGalva: 6,
      description:
        'Cornière à ailes égales ( Epaisseur : 15 mm Hauteur Ailes : 150 mm)',
    },
    {
      choix: 14,
      epaisseur: 20,
      hauteurAiles: 200,
      masseKgPerM: 65.89,
      sectionCm2: 76.3,
      pxKg: 3,
      pxKgGalva: 6,
      description:
        'Cornière à ailes égales ( Epaisseur : 20 mm Hauteur Ailes : 200 mm)',
    },
  ];

  cornieres_ailes_inegales_acier = [
    {
      id: 0,
      hauteur: 30,
      largeur: 20,
      epaisseur: 3,
      masse: 1.61,
      section: 1.86,
      px_kg: 3,
      px_kg_galva: 6,
      nom: 'Cornière à ailes inégales ( Hauteur : 30 mm Largeur : 20 mm Epaisseur : 3 mm)',
      choix: '0_1.46_30',
    },
    {
      id: 1,
      hauteur: 40,
      largeur: 25,
      epaisseur: 4,
      masse: 2.12,
      section: 2.46,
      px_kg: 3,
      px_kg_galva: 6,
      nom: 'Cornière à ailes inégales ( Hauteur : 40 mm Largeur : 25 mm Epaisseur : 4 mm)',
      choix: '1_1.93_40',
    },
    {
      id: 2,
      hauteur: 45,
      largeur: 30,
      epaisseur: 4,
      masse: 2.46,
      section: 0,
      px_kg: 3,
      px_kg_galva: 6,
      nom: 'Cornière à ailes inégales ( Hauteur : 45 mm Largeur : 30 mm Epaisseur : 4 mm)',
      choix: '2_2.24_45',
    },
    {
      id: 3,
      hauteur: 50,
      largeur: 30,
      epaisseur: 5,
      masse: 3.26,
      section: 3.78,
      px_kg: 3,
      px_kg_galva: 6,
      nom: 'Cornière à ailes inégales ( Hauteur : 50 mm Largeur : 30 mm Epaisseur : 5 mm)',
      choix: '3_2.96_50',
    },
    {
      id: 4,
      hauteur: 60,
      largeur: 40,
      epaisseur: 5,
      masse: 4.14,
      section: 4.79,
      px_kg: 3,
      px_kg_galva: 6,
      nom: 'Cornière à ailes inégales ( Hauteur : 60 mm Largeur : 40 mm Epaisseur : 5 mm)',
      choix: '4_3.76_60',
    },
    {
      id: 5,
      hauteur: 70,
      largeur: 50,
      epaisseur: 6,
      masse: 6.86,
      section: 7.95,
      px_kg: 3,
      px_kg_galva: 6,
      nom: 'Cornière à ailes inégales ( Hauteur : 70 mm Largeur : 50 mm Epaisseur : 6 mm)',
      choix: '5_6.24_70',
    },
    {
      id: 6,
      hauteur: 80,
      largeur: 60,
      epaisseur: 7,
      masse: 8.1,
      section: 9.38,
      px_kg: 3,
      px_kg_galva: 6,
      nom: 'Cornière à ailes inégales ( Hauteur : 80 mm Largeur : 60 mm Epaisseur : 7 mm)',
      choix: '6_7.36_80',
    },
    {
      id: 7,
      hauteur: 100,
      largeur: 75,
      epaisseur: 9,
      masse: 12.98,
      section: 15.0,
      px_kg: 3,
      px_kg_galva: 6,
      nom: 'Cornière à ailes inégales ( Hauteur : 100 mm Largeur : 75 mm Epaisseur : 9 mm)',
      choix: '7_11.8_100',
    },
    {
      id: 8,
      hauteur: 120,
      largeur: 80,
      epaisseur: 12,
      masse: 19.58,
      section: 22.7,
      px_kg: 3,
      px_kg_galva: 6,
      nom: 'Cornière à ailes inégales ( Hauteur : 120 mm Largeur : 80 mm Epaisseur : 12 mm)',
      choix: '8_17.8_120',
    },
    {
      id: 9,
      hauteur: 150,
      largeur: 90,
      epaisseur: 11,
      masse: 21.89,
      section: 25.3,
      px_kg: 3,
      px_kg_galva: 6,
      nom: 'Cornière à ailes inégales ( Hauteur : 150 mm Largeur : 90 mm Epaisseur : 11 mm)',
      choix: '9_19.9_150',
    },
    {
      id: 10,
      hauteur: 200,
      largeur: 100,
      epaisseur: 14,
      masse: 34.76,
      section: 40.3,
      px_kg: 3,
      px_kg_galva: 6,
      nom: 'Cornière à ailes inégales ( Hauteur : 200 mm Largeur : 100 mm Epaisseur : 14 mm)',
      choix: '10_31.6_200',
    },
  ];

  fers_t_acier = [
    {
      id: 0,
      epaisseur: 3,
      hauteur: 20,
      largeur: 20,
      masse: 0.97,
      section: 1.12,
      px_kg: 3,
      px_kg_galva: 6,
      nom: 'FER T ( Epaisseur : 3 mm Hauteur : 20 mm Largeur : 20 mm)',
      choix: '0_0.97_20',
    },
    {
      id: 1,
      epaisseur: 4,
      hauteur: 30,
      largeur: 30,
      masse: 1.95,
      section: 2.26,
      px_kg: 3,
      px_kg_galva: 6,
      nom: 'FER T ( Epaisseur : 4 mm Hauteur : 30 mm Largeur : 30 mm)',
      choix: '1_1.95_30',
    },
    {
      id: 2,
      epaisseur: 5,
      hauteur: 40,
      largeur: 40,
      masse: 3.26,
      section: 3.77,
      px_kg: 3,
      px_kg_galva: 6,
      nom: 'FER T ( Epaisseur : 5 mm Hauteur : 40 mm Largeur : 40 mm)',
      choix: '2_3.26_40',
    },
    {
      id: 3,
      epaisseur: 6,
      hauteur: 50,
      largeur: 50,
      masse: 4.88,
      section: 5.66,
      px_kg: 3,
      px_kg_galva: 6,
      nom: 'FER T ( Epaisseur : 6 mm Hauteur : 50 mm Largeur : 50 mm)',
      choix: '3_4.88_50',
    },
    {
      id: 4,
      epaisseur: 7,
      hauteur: 60,
      largeur: 60,
      masse: 6.85,
      section: 7.94,
      px_kg: 3,
      px_kg_galva: 6,
      nom: 'FER T ( Epaisseur : 7 mm Hauteur : 60 mm Largeur : 60 mm)',
      choix: '4_6.85_60',
    },
    {
      id: 5,
      epaisseur: 9,
      hauteur: 80,
      largeur: 80,
      masse: 11.77,
      section: 13.6,
      px_kg: 3,
      px_kg_galva: 6,
      nom: 'FER T ( Epaisseur : 9 mm Hauteur : 80 mm Largeur : 80 mm)',
      choix: '5_11.77_80',
    },
    {
      id: 6,
      epaisseur: 11,
      hauteur: 100,
      largeur: 100,
      masse: 18.04,
      section: 20.9,
      px_kg: 3,
      px_kg_galva: 6,
      nom: 'FER T ( Epaisseur : 11 mm Hauteur : 100 mm Largeur : 100 mm)',
      choix: '6_18.04_100',
    },
    {
      id: 7,
      epaisseur: 13,
      hauteur: 120,
      largeur: 120,
      masse: 31.02,
      section: 29.6,
      px_kg: 7,
      px_kg_galva: 7,
      nom: 'FER T ( Epaisseur : 13 mm Hauteur : 120 mm Largeur : 120 mm)',
      choix: '7_31.02_120',
    },
  ];

  // • De 30 x 20 à 80 x 40
  tubes_carres_acier = [
    {
      id: 0,
      hauteur: 20,
      epaisseur: 1.5,
      masse: 0.96,
      px_kg: 3,
      px_kg_galva: 6,
      nom: 'Tube carré ( Hauteur : 20 mm Epaisseur : 1.5 mm)',
      choix: '0_0.96_20',
    },
    {
      id: 1,
      hauteur: 20,
      epaisseur: 2,
      masse: 1.24,
      px_kg: 3,
      px_kg_galva: 6,
      nom: 'Tube carré ( Hauteur : 20 mm Epaisseur : 2 mm)',
      choix: '1_1.24_20',
    },
    {
      id: 2,
      hauteur: 25,
      epaisseur: 1.5,
      masse: 1.22,
      px_kg: 3,
      px_kg_galva: 6,
      nom: 'Tube carré ( Hauteur : 25 mm Epaisseur : 1.5 mm)',
      choix: '2_1.22_25',
    },
    {
      id: 3,
      hauteur: 25,
      epaisseur: 2,
      masse: 1.58,
      px_kg: 3,
      px_kg_galva: 6,
      nom: 'Tube carré ( Hauteur : 25 mm Epaisseur : 2 mm)',
      choix: '3_1.58_25',
    },
    {
      id: 4,
      hauteur: 30,
      epaisseur: 1.5,
      masse: 1.47,
      px_kg: 3,
      px_kg_galva: 6,
      nom: 'Tube carré ( Hauteur : 30 mm Epaisseur : 1.5 mm)',
      choix: '4_1.47_30',
    },
    {
      id: 5,
      hauteur: 30,
      epaisseur: 2,
      masse: 1.94,
      px_kg: 3,
      px_kg_galva: 6,
      nom: 'Tube carré ( Hauteur : 30 mm Epaisseur : 2 mm)',
      choix: '5_1.94_30',
    },
    {
      id: 6,
      hauteur: 30,
      epaisseur: 3,
      masse: 2.66,
      px_kg: 3,
      px_kg_galva: 6,
      nom: 'Tube carré ( Hauteur : 30 mm Epaisseur : 3 mm)',
      choix: '6_2.66_30',
    },
    {
      id: 7,
      hauteur: 35,
      epaisseur: 2,
      masse: 2.28,
      px_kg: 3,
      px_kg_galva: 6,
      nom: 'Tube carré ( Hauteur : 35 mm Epaisseur : 2 mm)',
      choix: '7_2.28_35',
    },
    {
      id: 8,
      hauteur: 35,
      epaisseur: 3,
      masse: 3.31,
      px_kg: 3,
      px_kg_galva: 6,
      nom: 'Tube carré ( Hauteur : 35 mm Epaisseur : 3 mm)',
      choix: '8_3.31_35',
    },
  ];

  tubes_rectangulaires_acier = [
    {
      id: 0,
      hauteur: 30,
      largeur: 20,
      epaisseur: 2,
      masse: 1.58,
      px_kg: 3,
      px_kg_galva: 6,
      nom: 'Tube rectangulaire ( Hauteur : 30 mm Largeur : 20 mm Epaisseur : 2 mm)',
    },
    {
      id: 1,
      hauteur: 35,
      largeur: 20,
      epaisseur: 2,
      masse: 1.76,
      px_kg: 3,
      px_kg_galva: 6,
      nom: 'Tube rectangulaire ( Hauteur : 35 mm Largeur : 20 mm Epaisseur : 2 mm)',
    },
    {
      id: 2,
      hauteur: 40,
      largeur: 20,
      epaisseur: 2,
      masse: 1.94,
      px_kg: 3,
      px_kg_galva: 6,
      nom: 'Tube rectangulaire ( Hauteur : 40 mm Largeur : 20 mm Epaisseur : 2 mm)',
    },
    {
      id: 3,
      hauteur: 40,
      largeur: 27,
      epaisseur: 2,
      masse: 2.18,
      px_kg: 3,
      px_kg_galva: 6,
      nom: 'Tube rectangulaire ( Hauteur : 40 mm Largeur : 27 mm Epaisseur : 2 mm)',
    },
    {
      id: 4,
      hauteur: 50,
      largeur: 30,
      epaisseur: 2,
      masse: 2.63,
      px_kg: 3,
      px_kg_galva: 6,
      nom: 'Tube rectangulaire ( Hauteur : 50 mm Largeur : 30 mm Epaisseur : 2 mm)',
    },
    {
      id: 5,
      hauteur: 50,
      largeur: 30,
      epaisseur: 3,
      masse: 3.81,
      px_kg: 3,
      px_kg_galva: 6,
      nom: 'Tube rectangulaire ( Hauteur : 50 mm Largeur : 30 mm Epaisseur : 3 mm)',
    },
    {
      id: 6,
      hauteur: 60,
      largeur: 30,
      epaisseur: 2,
      masse: 2.97,
      px_kg: 3,
      px_kg_galva: 6,
      nom: 'Tube rectangulaire ( Hauteur : 60 mm Largeur : 30 mm Epaisseur : 2 mm)',
    },
    {
      id: 7,
      hauteur: 60,
      largeur: 40,
      epaisseur: 2,
      masse: 3.32,
      px_kg: 3,
      px_kg_galva: 6,
      nom: 'Tube rectangulaire ( Hauteur : 60 mm Largeur : 40 mm Epaisseur : 2 mm)',
    },
    {
      id: 8,
      hauteur: 60,
      largeur: 40,
      epaisseur: 3,
      masse: 4.84,
      px_kg: 3,
      px_kg_galva: 6,
      nom: 'Tube rectangulaire ( Hauteur : 60 mm Largeur : 40 mm Epaisseur : 3 mm)',
    },
    {
      id: 9,
      hauteur: 80,
      largeur: 40,
      epaisseur: 2,
      masse: 4.0,
      px_kg: 3,
      px_kg_galva: 6,
      nom: 'Tube rectangulaire ( Hauteur : 80 mm Largeur : 40 mm Epaisseur : 2 mm)',
    },
    {
      id: 10,
      hauteur: 80,
      largeur: 40,
      epaisseur: 3,
      masse: 5.87,
      px_kg: 3,
      px_kg_galva: 6,
      nom: 'Tube rectangulaire ( Hauteur : 80 mm Largeur : 40 mm Epaisseur : 3 mm)',
    },
    {
      id: 11,
      hauteur: 80,
      largeur: 40,
      epaisseur: 4,
      masse: 7.66,
      px_kg: 6,
      px_kg_galva: 6,
      nom: 'Tube rectangulaire ( Hauteur : 80 mm Largeur : 40 mm Epaisseur : 4 mm)',
    },
    {
      id: 12,
      hauteur: 80,
      largeur: 40,
      epaisseur: 5,
      masse: 8.94,
      px_kg: 6,
      px_kg_galva: 6,
      nom: 'Tube rectangulaire ( Hauteur : 80 mm Largeur : 40 mm Epaisseur : 5 mm)',
    },
  ];

  //Galva

  tole_perforee_galva = [
    {
      id: 0,
      epaisseur: 1.5,
      typeTrous: 'trous ronds diam 10mm',
      masse: 12.98,
      px_kg: 8.5,
      px_kg_galva: 9.5,
      nom: 'Tôle perforée ( Epaisseur : 1.5 mm  : trous ronds diam 10mm mm)',
    },
    {
      id: 1,
      epaisseur: 2,
      typeTrous: 'trous ronds diam 5mm',
      masse: 17.27,
      px_kg: 8.5,
      px_kg_galva: 9.5,
      nom: 'Tôle perforée ( Epaisseur : 2 mm  : trous ronds diam 5mm mm)',
    },
    {
      id: 2,
      epaisseur: 1.5,
      typeTrous: 'trous carré 10/10mm',
      masse: 12.98,
      px_kg: 8.5,
      px_kg_galva: 9.5,
      nom: 'Tôle perforée ( Epaisseur : 1.5 mm  : trous carré 10/10mm mm)',
    },
  ];

  cornieres_ailes_egales_galva = [
    {
      choix: 0,
      epaisseur: 3,
      hauteurAiles: 30,
      masseKg_m: 1.5,
      sectionCm2: 1.74,
      pxKg: 6,
      pxKgGalva: 6,
      nomProduit:
        'Cornière à ailes égales ( Epaisseur : 3 mm Hauteur Ailes : 30 mm)',
    },
    {
      choix: 1,
      epaisseur: 3.5,
      hauteurAiles: 35,
      masseKg_m: 2.04,
      sectionCm2: 2.35,
      pxKg: 6,
      pxKgGalva: 6,
      nomProduit:
        'Cornière à ailes égales ( Epaisseur : 3.5 mm Hauteur Ailes : 35 mm)',
    },
    {
      choix: 2,
      epaisseur: 4,
      hauteurAiles: 40,
      masseKg_m: 2.66,
      sectionCm2: 3.08,
      pxKg: 6,
      pxKgGalva: 6,
      nomProduit:
        'Cornière à ailes égales ( Epaisseur : 4 mm Hauteur Ailes : 40 mm)',
    },
    {
      choix: 3,
      epaisseur: 5,
      hauteurAiles: 50,
      masseKg_m: 4.15,
      sectionCm2: 4.8,
      pxKg: 6,
      pxKgGalva: 6,
      nomProduit:
        'Cornière à ailes égales ( Epaisseur : 5 mm Hauteur Ailes : 50 mm)',
    },
  ];

  tubes_ronds_galva = [
    {
      choix: 0,
      diametreExterieur: 21.3,
      epaisseur: 2.3,
      masseKg_m: 1.18,
      pxKg: 6,
      pxKgGalva: 6,
      nomProduit:
        'Tube rond SENDZINIR NF EN 10305-3 S4 ( Diamètre extérieur : 21.3 mm Epaisseur : 2.3 mm)',
    },
    {
      choix: 1,
      diametreExterieur: 26.9,
      epaisseur: 2.3,
      masseKg_m: 1.54,
      pxKg: 6,
      pxKgGalva: 6,
      nomProduit:
        'Tube rond SENDZINIR NF EN 10305-3 S4 ( Diamètre extérieur : 26.9 mm Epaisseur : 2.3 mm)',
    },
    {
      choix: 2,
      diametreExterieur: 30,
      epaisseur: 1.5,
      masseKg_m: 1.28,
      pxKg: 6,
      pxKgGalva: 6,
      nomProduit:
        'Tube rond SENDZINIR NF EN 10305-3 S4 ( Diamètre extérieur : 30 mm Epaisseur : 1.5 mm)',
    },
    {
      choix: 3,
      diametreExterieur: 33.7,
      epaisseur: 2.9,
      masseKg_m: 2.42,
      pxKg: 6,
      pxKgGalva: 6,
      nomProduit:
        'Tube rond SENDZINIR NF EN 10305-3 S4 ( Diamètre extérieur : 33.7 mm Epaisseur : 2.9 mm)',
    },
    {
      choix: 4,
      diametreExterieur: 40,
      epaisseur: 1.5,
      masseKg_m: 1.72,
      pxKg: 6,
      pxKgGalva: 6,
      nomProduit:
        'Tube rond SENDZINIR NF EN 10305-3 S4 ( Diamètre extérieur : 40 mm Epaisseur : 1.5 mm)',
    },
    {
      choix: 5,
      diametreExterieur: 42.4,
      epaisseur: 2.9,
      masseKg_m: 3.1,
      pxKg: 6,
      pxKgGalva: 6,
      nomProduit:
        'Tube rond SENDZINIR NF EN 10305-3 S4 ( Diamètre extérieur : 42.4 mm Epaisseur : 2.9 mm)',
    },
    {
      choix: 6,
      diametreExterieur: 48.3,
      epaisseur: 2.9,
      masseKg_m: 3.58,
      pxKg: 6,
      pxKgGalva: 6,
      nomProduit:
        'Tube rond SENDZINIR NF EN 10305-3 S4 ( Diamètre extérieur : 48.3 mm Epaisseur : 2.9 mm)',
    },
    {
      choix: 7,
      diametreExterieur: 50,
      epaisseur: 1.5,
      masseKg_m: 2.16,
      pxKg: 6,
      pxKgGalva: 6,
      nomProduit:
        'Tube rond SENDZINIR NF EN 10305-3 S4 ( Diamètre extérieur : 50 mm Epaisseur : 1.5 mm)',
    },
    {
      choix: 8,
      diametreExterieur: 50,
      epaisseur: 2,
      masseKg_m: 2.61,
      pxKg: 6,
      pxKgGalva: 6,
      nomProduit:
        'Tube rond SENDZINIR NF EN 10305-3 S4 ( Diamètre extérieur : 50 mm Epaisseur : 2 mm)',
    },
    {
      choix: 9,
      diametreExterieur: 60,
      epaisseur: 1.5,
      masseKg_m: 2.6,
      pxKg: 6,
      pxKgGalva: 6,
      nomProduit:
        'Tube rond SENDZINIR NF EN 10305-3 S4 ( Diamètre extérieur : 60 mm Epaisseur : 1.5 mm)',
    },
    {
      choix: 10,
      diametreExterieur: 60,
      epaisseur: 2,
      masseKg_m: 3.45,
      pxKg: 6,
      pxKgGalva: 6,
      nomProduit:
        'Tube rond SENDZINIR NF EN 10305-3 S4 ( Diamètre extérieur : 60 mm Epaisseur : 2 mm)',
    },
  ];

  tubes_carres_galva = [
    {
      choix: 0,
      hauteur: 20,
      epaisseur: 1.5,
      masse: 0.96,
      pxKg: 6,
      pxKgGalva: 6,
      nom: 'Tube carré SENDZINIR NF EN 10305-3 S4 ( Hauteur : 20 mm Epaisseur : 1.5 mm)',
    },
    {
      choix: 1,
      hauteur: 25,
      epaisseur: 1.5,
      masse: 1.22,
      pxKg: 6,
      pxKgGalva: 6,
      nom: 'Tube carré SENDZINIR NF EN 10305-3 S4 ( Hauteur : 25 mm Epaisseur : 1.5 mm)',
    },
    {
      choix: 2,
      hauteur: 25,
      epaisseur: 2,
      masse: 1.58,
      pxKg: 6,
      pxKgGalva: 6,
      nom: 'Tube carré SENDZINIR NF EN 10305-3 S4 ( Hauteur : 25 mm Epaisseur : 2 mm)',
    },
    {
      choix: 3,
      hauteur: 30,
      epaisseur: 2,
      masse: 1.94,
      pxKg: 6,
      pxKgGalva: 6,
      nom: 'Tube carré SENDZINIR NF EN 10305-3 S4 ( Hauteur : 30 mm Epaisseur : 2 mm)',
    },
    {
      choix: 4,
      hauteur: 35,
      epaisseur: 2,
      masse: 2.28,
      pxKg: 6,
      pxKgGalva: 6,
      nom: 'Tube carré SENDZINIR NF EN 10305-3 S4 ( Hauteur : 35 mm Epaisseur : 2 mm)',
    },
    {
      choix: 5,
      hauteur: 40,
      epaisseur: 2,
      masse: 2.63,
      pxKg: 6,
      pxKgGalva: 6,
      nom: 'Tube carré SENDZINIR NF EN 10305-3 S4 ( Hauteur : 40 mm Epaisseur : 2 mm)',
    },
    {
      choix: 6,
      hauteur: 50,
      epaisseur: 2,
      masse: 3.32,
      pxKg: 6,
      pxKgGalva: 6,
      nom: 'Tube carré SENDZINIR NF EN 10305-3 S4 ( Hauteur : 50 mm Epaisseur : 2 mm)',
    },
    {
      choix: 7,
      hauteur: 60,
      epaisseur: 2,
      masse: 3.95,
      pxKg: 6,
      pxKgGalva: 6,
      nom: 'Tube carré SENDZINIR NF EN 10305-3 S4 ( Hauteur : 60 mm Epaisseur : 2 mm)',
    },
    {
      choix: 8,
      hauteur: 80,
      epaisseur: 2,
      masse: 5.39,
      pxKg: 6,
      pxKgGalva: 6,
      nom: 'Tube carré SENDZINIR NF EN 10305-3 S4 ( Hauteur : 80 mm Epaisseur : 2 mm)',
    },
    {
      choix: 9,
      hauteur: 100,
      epaisseur: 2,
      masse: 7.45,
      pxKg: 6,
      pxKgGalva: 6,
      nom: 'Tube carré SENDZINIR NF EN 10305-3 S4 ( Hauteur : 100 mm Epaisseur : 2 mm)',
    },
    {
      choix: 10,
      hauteur: 100,
      epaisseur: 3,
      masse: 9.92,
      pxKg: 6,
      pxKgGalva: 6,
      nom: 'Tube carré SENDZINIR NF EN 10305-3 S4 ( Hauteur : 100 mm Epaisseur : 3 mm)',
    },
  ];

  tubes_rectangulaires_galva = [
    {
      id: 0,
      hauteur: 35,
      largeur: 20,
      epaisseur: 2,
      masse: 1.76,
      pxKg: 6,
      pxKgGalva: 6,
      nom: 'Tube rectangulaire SENDZINIR NF EN 10305-3 S4 ( Hauteur : 35 mm Largeur : 20 mm Epaisseur : 2 mm)',
    },
    {
      id: 1,
      hauteur: 40,
      largeur: 20,
      epaisseur: 2,
      masse: 1.94,
      pxKg: 6,
      pxKgGalva: 6,
      nom: 'Tube rectangulaire SENDZINIR NF EN 10305-3 S4 ( Hauteur : 40 mm Largeur : 20 mm Epaisseur : 2 mm)',
    },
    {
      id: 2,
      hauteur: 40,
      largeur: 27,
      epaisseur: 2,
      masse: 2.18,
      pxKg: 6,
      pxKgGalva: 6,
      nom: 'Tube rectangulaire SENDZINIR NF EN 10305-3 S4 ( Hauteur : 40 mm Largeur : 27 mm Epaisseur : 2 mm)',
    },
    {
      id: 3,
      hauteur: 50,
      largeur: 30,
      epaisseur: 2,
      masse: 2.63,
      pxKg: 6,
      pxKgGalva: 6,
      nom: 'Tube rectangulaire SENDZINIR NF EN 10305-3 S4 ( Hauteur : 50 mm Largeur : 30 mm Epaisseur : 2 mm)',
    },
    {
      id: 4,
      hauteur: 60,
      largeur: 30,
      epaisseur: 2,
      masse: 2.97,
      pxKg: 6,
      pxKgGalva: 6,
      nom: 'Tube rectangulaire SENDZINIR NF EN 10305-3 S4 ( Hauteur : 60 mm Largeur : 30 mm Epaisseur : 2 mm)',
    },
    {
      id: 5,
      hauteur: 60,
      largeur: 40,
      epaisseur: 2,
      masse: 3.32,
      pxKg: 6,
      pxKgGalva: 6,
      nom: 'Tube rectangulaire SENDZINIR NF EN 10305-3 S4 ( Hauteur : 60 mm Largeur : 40 mm Epaisseur : 2 mm)',
    },
    {
      id: 6,
      hauteur: 80,
      largeur: 40,
      epaisseur: 2,
      masse: 4.0,
      pxKg: 6,
      pxKgGalva: 6,
      nom: 'Tube rectangulaire SENDZINIR NF EN 10305-3 S4 ( Hauteur : 80 mm Largeur : 40 mm Epaisseur : 2 mm)',
    },
    {
      id: 7,
      hauteur: 100,
      largeur: 20,
      epaisseur: 2,
      masse: 4.31,
      pxKg: 6,
      pxKgGalva: 6,
      nom: 'Tube rectangulaire SENDZINIR NF EN 10305-3 S4 ( Hauteur : 100 mm Largeur : 20 mm Epaisseur : 2 mm)',
    },
    {
      id: 8,
      hauteur: 100,
      largeur: 50,
      epaisseur: 2,
      masse: 4.9,
      pxKg: 6,
      pxKgGalva: 6,
      nom: 'Tube rectangulaire SENDZINIR NF EN 10305-3 S4 ( Hauteur : 100 mm Largeur : 50 mm Epaisseur : 2 mm)',
    },
  ];
}
