const fer_t_aluminium = [
  {
    name: 'FER T',
    description: 'Epaisseur : 2 mm Hauteur : 25 mm Largeur : 25 mm',
    basePrice: null,
    unitPriceExclTax: 20,
    VATRate: null,
    marginPercent: null,
    sellingPrice: 0,
    linearWeight: 0.29,
    thickness: 2,
    height: 25,
    width: 25,
    diameter: null,
    circumference: null,
    sectionArea: null,
    weight: null,
    matiere: 'Aluminium',
    productCode: 1,
  },
  {
    name: 'FER T',
    description: 'Epaisseur : 2 mm Hauteur : 30 mm Largeur : 30 mm',
    basePrice: null,
    unitPriceExclTax: 20,
    VATRate: null,
    marginPercent: null,
    sellingPrice: 0,
    linearWeight: 0.34,
    thickness: 2,
    height: 30,
    width: 30,
    diameter: null,
    circumference: null,
    sectionArea: null,
    weight: null,
    matiere: 'Aluminium',
    productCode: 2, // Numéro croissant

    // Relations supprimées
  },
  {
    name: 'FER T',
    description: 'Epaisseur : 3 mm Hauteur : 30 mm Largeur : 30 mm',
    basePrice: null,
    unitPriceExclTax: 20,
    VATRate: null,
    marginPercent: null,
    sellingPrice: 0,
    linearWeight: 0.51,
    thickness: 3,
    height: 30,
    width: 30,
    diameter: null,
    circumference: null,
    sectionArea: null,
    weight: null,
    matiere: 'Aluminium',
    productCode: 3,
  },
  {
    name: 'FER T',
    description: 'Epaisseur : 3 mm Hauteur : 40 mm Largeur : 40 mm',
    basePrice: null,
    unitPriceExclTax: 20,
    VATRate: null,
    marginPercent: null,
    sellingPrice: 0,
    linearWeight: 0.68,
    thickness: 3,
    height: 40,
    width: 40,
    diameter: null,
    circumference: null,
    sectionArea: null,
    weight: null,
    matiere: 'Aluminium',
    productCode: 4,
  },
  {
    name: 'FER T',
    description: 'Epaisseur : 4 mm Hauteur : 40 mm Largeur : 40 mm',
    basePrice: null,
    unitPriceExclTax: 20,
    VATRate: null,
    marginPercent: null,
    sellingPrice: 0,
    linearWeight: 0.9,
    thickness: 4,
    height: 40,
    width: 40,
    diameter: null,
    circumference: null,
    sectionArea: null,
    weight: null,
    matiere: 'Aluminium',
    productCode: 5,
  },
  {
    name: 'FER T',
    description: 'Epaisseur : 5 mm Hauteur : 50 mm Largeur : 50 mm',
    basePrice: null,
    unitPriceExclTax: 20,
    VATRate: null,
    marginPercent: null,
    sellingPrice: 0,
    linearWeight: 1.41,
    thickness: 5,
    height: 50,
    width: 50,
    diameter: null,
    circumference: null,
    sectionArea: null,
    weight: null,
    matiere: 'Aluminium',
    productCode: 6,
  },
  {
    name: 'FER T',
    description: 'Epaisseur : 6 mm Hauteur : 60 mm Largeur : 60 mm',
    basePrice: null,
    unitPriceExclTax: 20,
    VATRate: null,
    marginPercent: null,
    sellingPrice: 0,
    linearWeight: 2.04,
    thickness: 6,
    height: 60,
    width: 60,
    diameter: null,
    circumference: null,
    sectionArea: null,
    weight: null,
    matiere: 'Aluminium',
    productCode: 7,
  },
  {
    name: 'FER T',
    description: 'Epaisseur : 8 mm Hauteur : 80 mm Largeur : 80 mm',
    basePrice: null,
    unitPriceExclTax: 20,
    VATRate: null,
    marginPercent: null,
    sellingPrice: 0,
    linearWeight: 3.61,
    thickness: 8,
    height: 80,
    width: 80,
    diameter: null,
    circumference: null,
    sectionArea: null,
    weight: null,
    matiere: 'Aluminium',
    productCode: 8,
  },
];

const corniere_egale_aluminium = [
  {
    name: 'Cornière à ailes égales',
    description: 'Epaisseur : 1.5 mm Hauteur Ailes : 15 mm',
    basePrice: null,
    unitPriceExclTax: 20,
    VATRate: null,
    marginPercent: null,
    sellingPrice: 0,
    linearWeight: 0.13,
    thickness: 1.5,
    height: 15,
    width: null,
    diameter: null,
    circumference: null,
    sectionArea: 0,
    weight: null,
    matiere: 'Aluminium',
    productCode: 9,
  },
  {
    name: 'Cornière à ailes égales',
    description: 'Epaisseur : 2 mm Hauteur Ailes : 15 mm',
    basePrice: null,
    unitPriceExclTax: 20,
    VATRate: null,
    marginPercent: null,
    sellingPrice: 0,
    linearWeight: 0.17,
    thickness: 2,
    height: 15,
    width: null,
    diameter: null,
    circumference: null,
    sectionArea: 0,
    weight: null,
    matiere: 'Aluminium',
    productCode: 10,
  },
  {
    name: 'Cornière à ailes égales',
    description: 'Epaisseur : 1.5 mm Hauteur Ailes : 20 mm',
    basePrice: null,
    unitPriceExclTax: 20,
    VATRate: null,
    marginPercent: null,
    sellingPrice: 0,
    linearWeight: 0.18,
    thickness: 1.5,
    height: 20,
    width: null,
    diameter: null,
    circumference: null,
    sectionArea: 0,
    weight: null,
    matiere: 'Aluminium',
    productCode: 11,
  },
  {
    name: 'Cornière à ailes égales',
    description: 'Epaisseur : 2 mm Hauteur Ailes : 20 mm',
    basePrice: null,
    unitPriceExclTax: 20,
    VATRate: null,
    marginPercent: null,
    sellingPrice: 0,
    linearWeight: 0.22,
    thickness: 2,
    height: 20,
    width: null,
    diameter: null,
    circumference: null,
    sectionArea: 0,
    weight: null,
    matiere: 'Aluminium',
    productCode: 12,
  },
  {
    name: 'Cornière à ailes égales',
    description: 'Epaisseur : 2 mm Hauteur Ailes : 25 mm',
    basePrice: null,
    unitPriceExclTax: 20,
    VATRate: null,
    marginPercent: null,
    sellingPrice: 0,
    linearWeight: 0.29,
    thickness: 2,
    height: 25,
    width: null,
    diameter: null,
    circumference: null,
    sectionArea: 0,
    weight: null,
    matiere: 'Aluminium',
    productCode: 13,
  },
  {
    name: 'Cornière à ailes égales',
    description: 'Epaisseur : 2 mm Hauteur Ailes : 30 mm',
    basePrice: null,
    unitPriceExclTax: 20,
    VATRate: null,
    marginPercent: null,
    sellingPrice: 0,
    linearWeight: 0.34,
    thickness: 2,
    height: 30,
    width: null,
    diameter: null,
    circumference: null,
    sectionArea: 0,
    weight: null,
    matiere: 'Aluminium',
    productCode: 14,
  },
  {
    name: 'Cornière à ailes égales',
    description: 'Epaisseur : 3 mm Hauteur Ailes : 30 mm',
    basePrice: null,
    unitPriceExclTax: 20,
    VATRate: null,
    marginPercent: null,
    sellingPrice: 0,
    linearWeight: 0.51,
    thickness: 3,
    height: 30,
    width: null,
    diameter: null,
    circumference: null,
    sectionArea: 0,
    weight: null,
    matiere: 'Aluminium',
    productCode: 15,
  },
  {
    name: 'Cornière à ailes égales',
    description: 'Epaisseur : 3 mm Hauteur Ailes : 35 mm',
    basePrice: null,
    unitPriceExclTax: 20,
    VATRate: null,
    marginPercent: null,
    sellingPrice: 0,
    linearWeight: 0.59,
    thickness: 3,
    height: 35,
    width: null,
    diameter: null,
    circumference: null,
    sectionArea: 0,
    weight: null,
    matiere: 'Aluminium',
    productCode: 16,
  },
  {
    name: 'Cornière à ailes égales',
    description: 'Epaisseur : 2 mm Hauteur Ailes : 40 mm',
    basePrice: null,
    unitPriceExclTax: 20,
    VATRate: null,
    marginPercent: null,
    sellingPrice: 0,
    linearWeight: 0.46,
    thickness: 2,
    height: 40,
    width: null,
    diameter: null,
    circumference: null,
    sectionArea: 0,
    weight: null,
    matiere: 'Aluminium',
    productCode: 17,
  },
  {
    name: 'Cornière à ailes égales',
    description: 'Epaisseur : 3 mm Hauteur Ailes : 40 mm',
    basePrice: null,
    unitPriceExclTax: 20,
    VATRate: null,
    marginPercent: null,
    sellingPrice: 0,
    linearWeight: 0.68,
    thickness: 3,
    height: 40,
    width: null,
    diameter: null,
    circumference: null,
    sectionArea: 0,
    weight: null,
    matiere: 'Aluminium',
    productCode: 18,
  },
  {
    name: 'Cornière à ailes égales',
    description: 'Epaisseur : 4 mm Hauteur Ailes : 40 mm',
    basePrice: null,
    unitPriceExclTax: 20,
    VATRate: null,
    marginPercent: null,
    sellingPrice: 0,
    linearWeight: 0.9,
    thickness: 4,
    height: 40,
    width: null,
    diameter: null,
    circumference: null,
    sectionArea: 0,
    weight: null,
    matiere: 'Aluminium',
    productCode: 19,
  },
  {
    name: 'Cornière à ailes égales',
    description: 'Epaisseur : 2 mm Hauteur Ailes : 50 mm',
    basePrice: null,
    unitPriceExclTax: 20,
    VATRate: null,
    marginPercent: null,
    sellingPrice: 0,
    linearWeight: 0.58,
    thickness: 2,
    height: 50,
    width: null,
    diameter: null,
    circumference: null,
    sectionArea: 0,
    weight: null,
    matiere: 'Aluminium',
    productCode: 20,
  },
  {
    name: 'Cornière à ailes égales',
    description: 'Epaisseur : 3 mm Hauteur Ailes : 50 mm',
    basePrice: null,
    unitPriceExclTax: 20,
    VATRate: null,
    marginPercent: null,
    sellingPrice: 0,
    linearWeight: 0.87,
    thickness: 3,
    height: 50,
    width: null,
    diameter: null,
    circumference: null,
    sectionArea: 0,
    weight: null,
    matiere: 'Aluminium',
    productCode: 21,
  },
  {
    name: 'Cornière à ailes égales',
    description: 'Epaisseur : 4 mm Hauteur Ailes : 50 mm',
    basePrice: null,
    unitPriceExclTax: 20,
    VATRate: null,
    marginPercent: null,
    sellingPrice: 0,
    linearWeight: 1.14,
    thickness: 4,
    height: 50,
    width: null,
    diameter: null,
    circumference: null,
    sectionArea: 0,
    weight: null,
    matiere: 'Aluminium',
    productCode: 22,
  },
  {
    name: 'Cornière à ailes égales',
    description: 'Epaisseur : 5 mm Hauteur Ailes : 50 mm',
    basePrice: null,
    unitPriceExclTax: 20,
    VATRate: null,
    marginPercent: null,
    sellingPrice: 0,
    linearWeight: 1.41,
    thickness: 5,
    height: 50,
    width: null,
    diameter: null,
    circumference: null,
    sectionArea: 0,
    weight: null,
    matiere: 'Aluminium',
    productCode: 23,
  },
  {
    name: 'Cornière à ailes égales',
    description: 'Epaisseur : 2 mm Hauteur Ailes : 60 mm',
    basePrice: null,
    unitPriceExclTax: 20,
    VATRate: null,
    marginPercent: null,
    sellingPrice: 0,
    linearWeight: 0.7,
    thickness: 2,
    height: 60,
    width: null,
    diameter: null,
    circumference: null,
    sectionArea: 0,
    weight: null,
    matiere: 'Aluminium',
    productCode: 24,
  },
  {
    name: 'Cornière à ailes égales',
    description: 'Epaisseur : 4 mm Hauteur Ailes : 60 mm',
    basePrice: null,
    unitPriceExclTax: 20,
    VATRate: null,
    marginPercent: null,
    sellingPrice: 0,
    linearWeight: 1.38,
    thickness: 4,
    height: 60,
    width: null,
    diameter: null,
    circumference: null,
    sectionArea: 0,
    weight: null,
    matiere: 'Aluminium',
    productCode: 25,
  },
  {
    name: 'Cornière à ailes égales',
    description: 'Epaisseur : 6 mm Hauteur Ailes : 60 mm',
    basePrice: null,
    unitPriceExclTax: 20,
    VATRate: null,
    marginPercent: null,
    sellingPrice: 0,
    linearWeight: 2.02,
    thickness: 6,
    height: 60,
    width: null,
    diameter: null,
    circumference: null,
    sectionArea: 0,
    weight: null,
    matiere: 'Aluminium',
    productCode: 26,
  },
  {
    name: 'Cornière à ailes égales',
    description: 'Epaisseur : 8 mm Hauteur Ailes : 80 mm',
    basePrice: null,
    unitPriceExclTax: 20,
    VATRate: null,
    marginPercent: null,
    sellingPrice: 0,
    linearWeight: 3.61,
    thickness: 8,
    height: 80,
    width: null,
    diameter: null,
    circumference: null,
    sectionArea: 0,
    weight: null,
    matiere: 'Aluminium',
    productCode: 27,
  },
  {
    name: 'Cornière à ailes égales',
    description: 'Epaisseur : 10 mm Hauteur Ailes : 100 mm',
    basePrice: null,
    unitPriceExclTax: 20,
    VATRate: null,
    marginPercent: null,
    sellingPrice: 0,
    linearWeight: 5.64,
    thickness: 10,
    height: 100,
    width: null,
    diameter: null,
    circumference: null,
    sectionArea: 0,
    weight: null,
    matiere: 'Aluminium',
    productCode: 28,
  },
];

const tube_rectangulaire_aluminium = [
  {
    name: 'Tube rectangulaire',
    description: 'Hauteur : 25 mm Largeur : 15 mm Epaisseur : 2 mm',
    basePrice: null,
    unitPriceExclTax: 20,
    VATRate: null,
    marginPercent: null,
    sellingPrice: 0,
    linearWeight: 0.43,
    thickness: 2,
    height: 25,
    width: 15,
    diameter: null,
    circumference: null,
    sectionArea: 0,
    weight: null,
    matiere: 'Aluminium',
    productCode: 29,
  },
  {
    name: 'Tube rectangulaire',
    description: 'Hauteur : 30 mm Largeur : 15 mm Epaisseur : 1.5 mm',
    basePrice: null,
    unitPriceExclTax: 20,
    VATRate: null,
    marginPercent: null,
    sellingPrice: 0,
    linearWeight: 0.37,
    thickness: 1.5,
    height: 30,
    width: 15,
    diameter: null,
    circumference: null,
    sectionArea: 0,
    weight: null,
    matiere: 'Aluminium',
    productCode: 30,
  },
  {
    name: 'Tube rectangulaire',
    description: 'Hauteur : 30 mm Largeur : 20 mm Epaisseur : 2 mm',
    basePrice: null,
    unitPriceExclTax: 20,
    VATRate: null,
    marginPercent: null,
    sellingPrice: 0,
    linearWeight: 0.55,
    thickness: 2,
    height: 30,
    width: 20,
    diameter: null,
    circumference: null,
    sectionArea: 0,
    weight: null,
    matiere: 'Aluminium',
    productCode: 31,
  },
  {
    name: 'Tube rectangulaire',
    description: 'Hauteur : 40 mm Largeur : 20 mm Epaisseur : 2 mm',
    basePrice: null,
    unitPriceExclTax: 20,
    VATRate: null,
    marginPercent: null,
    sellingPrice: 0,
    linearWeight: 0.66,
    thickness: 2,
    height: 40,
    width: 20,
    diameter: null,
    circumference: null,
    sectionArea: 0,
    weight: null,
    matiere: 'Aluminium',
    productCode: 32,
  },
  {
    name: 'Tube rectangulaire',
    description: 'Hauteur : 40 mm Largeur : 20 mm Epaisseur : 3 mm',
    basePrice: null,
    unitPriceExclTax: 20,
    VATRate: null,
    marginPercent: null,
    sellingPrice: 0,
    linearWeight: 0.97,
    thickness: 3,
    height: 40,
    width: 20,
    diameter: null,
    circumference: null,
    sectionArea: 0,
    weight: null,
    matiere: 'Aluminium',
    productCode: 33,
  },
  {
    name: 'Tube rectangulaire',
    description: 'Hauteur : 40 mm Largeur : 20 mm Epaisseur : 4 mm',
    basePrice: null,
    unitPriceExclTax: 30,
    VATRate: null,
    marginPercent: null,
    sellingPrice: 0,
    linearWeight: 1.23,
    thickness: 4,
    height: 40,
    width: 20,
    diameter: null,
    circumference: null,
    sectionArea: 0,
    weight: null,
    matiere: 'Aluminium',
    productCode: 34,
  },
  {
    name: 'Tube rectangulaire',
    description: 'Hauteur : 50 mm Largeur : 20 mm Epaisseur : 2 mm',
    basePrice: null,
    unitPriceExclTax: 20,
    VATRate: null,
    marginPercent: null,
    sellingPrice: 0,
    linearWeight: 0.78,
    thickness: 2,
    height: 50,
    width: 20,
    diameter: null,
    circumference: null,
    sectionArea: 0,
    weight: null,
    matiere: 'Aluminium',
    productCode: 35,
  },
  {
    name: 'Tube rectangulaire',
    description: 'Hauteur : 50 mm Largeur : 25 mm Epaisseur : 2 mm',
    basePrice: null,
    unitPriceExclTax: 20,
    VATRate: null,
    marginPercent: null,
    sellingPrice: 0,
    linearWeight: 0.85,
    thickness: 2,
    height: 50,
    width: 25,
    diameter: null,
    circumference: null,
    sectionArea: 0,
    weight: null,
    matiere: 'Aluminium',
    productCode: 36,
  },
  {
    name: 'Tube rectangulaire',
    description: 'Hauteur : 50 mm Largeur : 30 mm Epaisseur : 2 mm',
    basePrice: null,
    unitPriceExclTax: 20,
    VATRate: null,
    marginPercent: null,
    sellingPrice: 0,
    linearWeight: 0.9,
    thickness: 2,
    height: 50,
    width: 30,
    diameter: null,
    circumference: null,
    sectionArea: 0,
    weight: null,
    matiere: 'Aluminium',
    productCode: 37,
  },
  {
    name: 'Tube rectangulaire',
    description: 'Hauteur : 50 mm Largeur : 30 mm Epaisseur : 3 mm',
    basePrice: null,
    unitPriceExclTax: 20,
    VATRate: null,
    marginPercent: null,
    sellingPrice: 0,
    linearWeight: 1.32,
    thickness: 3,
    height: 50,
    width: 30,
    diameter: null,
    circumference: null,
    sectionArea: 0,
    weight: null,
    matiere: 'Aluminium',
    productCode: 38,
  },
  {
    name: 'Tube rectangulaire',
    description: 'Hauteur : 60 mm Largeur : 30 mm Epaisseur : 2 mm',
    basePrice: null,
    unitPriceExclTax: 20,
    VATRate: null,
    marginPercent: null,
    sellingPrice: 0,
    linearWeight: 1.02,
    thickness: 2,
    height: 60,
    width: 30,
    diameter: null,
    circumference: null,
    sectionArea: 0,
    weight: null,
    matiere: 'Aluminium',
    productCode: 39,
  },
  {
    name: 'Tube rectangulaire',
    description: 'Hauteur : 60 mm Largeur : 30 mm Epaisseur : 3 mm',
    basePrice: null,
    unitPriceExclTax: 20,
    VATRate: null,
    marginPercent: null,
    sellingPrice: 0,
    linearWeight: 1.5,
    thickness: 3,
    height: 60,
    width: 30,
    diameter: null,
    circumference: null,
    sectionArea: 0,
    weight: null,
    matiere: 'Aluminium',
    productCode: 40,
  },
  {
    name: 'Tube rectangulaire',
    description: 'Hauteur : 60 mm Largeur : 40 mm Epaisseur : 2 mm',
    basePrice: null,
    unitPriceExclTax: 20,
    VATRate: null,
    marginPercent: null,
    sellingPrice: 0,
    linearWeight: 1.14,
    thickness: 2,
    height: 60,
    width: 40,
    diameter: null,
    circumference: null,
    sectionArea: 0,
    weight: null,
    matiere: 'Aluminium',
    productCode: 41,
  },
  {
    name: 'Tube rectangulaire',
    description: 'Hauteur : 60 mm Largeur : 40 mm Epaisseur : 3 mm',
    basePrice: null,
    unitPriceExclTax: 20,
    VATRate: null,
    marginPercent: null,
    sellingPrice: 0,
    linearWeight: 1.67,
    thickness: 3,
    height: 60,
    width: 40,
    diameter: null,
    circumference: null,
    sectionArea: 0,
    weight: null,
    matiere: 'Aluminium',
    productCode: 42,
  },
  {
    name: 'Tube rectangulaire',
    description: 'Hauteur : 60 mm Largeur : 40 mm Epaisseur : 4 mm',
    basePrice: null,
    unitPriceExclTax: 30,
    VATRate: null,
    marginPercent: null,
    sellingPrice: 0,
    linearWeight: 2.18,
    thickness: 4,
    height: 60,
    width: 40,
    diameter: null,
    circumference: null,
    sectionArea: 0,
    weight: null,
    matiere: 'Aluminium',
    productCode: 43,
  },
  {
    name: 'Tube rectangulaire',
    description: 'Hauteur : 80 mm Largeur : 20 mm Epaisseur : 2 mm',
    basePrice: null,
    unitPriceExclTax: 20,
    VATRate: null,
    marginPercent: null,
    sellingPrice: 0,
    linearWeight: 1.14,
    thickness: 2,
    height: 80,
    width: 20,
    diameter: null,
    circumference: null,
    sectionArea: 0,
    weight: null,
    matiere: 'Aluminium',
    productCode: 44,
  },
  {
    name: 'Tube rectangulaire',
    description: 'Hauteur : 80 mm Largeur : 40 mm Epaisseur : 2 mm',
    basePrice: null,
    unitPriceExclTax: 20,
    VATRate: null,
    marginPercent: null,
    sellingPrice: 0,
    linearWeight: 1.38,
    thickness: 2,
    height: 80,
    width: 40,
    diameter: null,
    circumference: null,
    sectionArea: 0,
    weight: null,
    matiere: 'Aluminium',
    productCode: 45,
  },
  {
    name: 'Tube rectangulaire',
    description: 'Hauteur : 80 mm Largeur : 40 mm Epaisseur : 3 mm',
    basePrice: null,
    unitPriceExclTax: 20,
    VATRate: null,
    marginPercent: null,
    sellingPrice: 0,
    linearWeight: 2.04,
    thickness: 3,
    height: 80,
    width: 40,
    diameter: null,
    circumference: null,
    sectionArea: 0,
    weight: null,
    matiere: 'Aluminium',
    productCode: 46,
  },
  {
    name: 'Tube rectangulaire',
    description: 'Hauteur : 80 mm Largeur : 40 mm Epaisseur : 4 mm',
    basePrice: null,
    unitPriceExclTax: 30,
    VATRate: null,
    marginPercent: null,
    sellingPrice: 0,
    linearWeight: 2.65,
    thickness: 4,
    height: 80,
    width: 40,
    diameter: null,
    circumference: null,
    sectionArea: 0,
    weight: null,
    matiere: 'Aluminium',
    productCode: 47,
  },
  {
    name: 'Tube rectangulaire',
    description: 'Hauteur : 80 mm Largeur : 50 mm Epaisseur : 5 mm',
    basePrice: null,
    unitPriceExclTax: 30,
    VATRate: null,
    marginPercent: null,
    sellingPrice: 0,
    linearWeight: 3.56,
    thickness: 5,
    height: 80,
    width: 50,
    diameter: null,
    circumference: null,
    sectionArea: 0,
    weight: null,
    matiere: 'Aluminium',
    productCode: 48,
  },
];

const tube_carré_aluminium = [
  {
    name: 'Tube carré',
    description: 'Epaisseur : 1.5 mm Hauteur : 20 mm',
    basePrice: null,
    unitPriceExclTax: 20,
    VATRate: null,
    marginPercent: null,
    sellingPrice: 0,
    linearWeight: 0.33,
    thickness: 1.5,
    height: 20,
    width: null,
    diameter: null,
    circumference: null,
    sectionArea: null,
    weight: null,
    matiere: 'Aluminium',
    productCode: 57,
  },
  {
    name: 'Tube carré',
    description: 'Epaisseur : 2 mm Hauteur : 20 mm',
    basePrice: null,
    unitPriceExclTax: 20,
    VATRate: null,
    marginPercent: null,
    sellingPrice: 0,
    linearWeight: 0.43,
    thickness: 2,
    height: 20,
    width: null,
    diameter: null,
    circumference: null,
    sectionArea: null,
    weight: null,
    matiere: 'Aluminium',
    productCode: 58,
  },
  {
    name: 'Tube carré',
    description: 'Epaisseur : 2 mm Hauteur : 25 mm',
    basePrice: null,
    unitPriceExclTax: 20,
    VATRate: null,
    marginPercent: null,
    sellingPrice: 0,
    linearWeight: 0.55,
    thickness: 2,
    height: 25,
    width: null,
    diameter: null,
    circumference: null,
    sectionArea: null,
    weight: null,
    matiere: 'Aluminium',
    productCode: 59,
  },
  {
    name: 'Tube carré',
    description: 'Epaisseur : 3 mm Hauteur : 25 mm',
    basePrice: null,
    unitPriceExclTax: 20,
    VATRate: null,
    marginPercent: null,
    sellingPrice: 0,
    linearWeight: 0.78,
    thickness: 3,
    height: 25,
    width: null,
    diameter: null,
    circumference: null,
    sectionArea: null,
    weight: null,
    matiere: 'Aluminium',
    productCode: 60,
  },
  {
    name: 'Tube carré',
    description: 'Epaisseur : 1.5 mm Hauteur : 30 mm',
    basePrice: null,
    unitPriceExclTax: 20,
    VATRate: null,
    marginPercent: null,
    sellingPrice: 0,
    linearWeight: 0.51,
    thickness: 1.5,
    height: 30,
    width: null,
    diameter: null,
    circumference: null,
    sectionArea: null,
    weight: null,
    matiere: 'Aluminium',
    productCode: 61,
  },
  {
    name: 'Tube carré',
    description: 'Epaisseur : 2 mm Hauteur : 30 mm',
    basePrice: null,
    unitPriceExclTax: 20,
    VATRate: null,
    marginPercent: null,
    sellingPrice: 0,
    linearWeight: 0.66,
    thickness: 2,
    height: 30,
    width: null,
    diameter: null,
    circumference: null,
    sectionArea: null,
    weight: null,
    matiere: 'Aluminium',
    productCode: 62,
  },
  {
    name: 'Tube carré',
    description: 'Epaisseur : 3 mm Hauteur : 30 mm',
    basePrice: null,
    unitPriceExclTax: 20,
    VATRate: null,
    marginPercent: null,
    sellingPrice: 0,
    linearWeight: 0.97,
    thickness: 3,
    height: 30,
    width: null,
    diameter: null,
    circumference: null,
    sectionArea: null,
    weight: null,
    matiere: 'Aluminium',
    productCode: 63,
  },
  {
    name: 'Tube carré',
    description: 'Epaisseur : 2 mm Hauteur : 35 mm',
    basePrice: null,
    unitPriceExclTax: 20,
    VATRate: null,
    marginPercent: null,
    sellingPrice: 0,
    linearWeight: 0.78,
    thickness: 2,
    height: 35,
    width: null,
    diameter: null,
    circumference: null,
    sectionArea: null,
    weight: null,
    matiere: 'Aluminium',
    productCode: 64,
  },
];

const barre_carree_plein_aluminium = [
  {
    name: 'Barre carrée pleine',
    description: 'Hauteur : 10 mm',
    basePrice: null,
    unitPriceExclTax: 20,
    VATRate: null,
    marginPercent: null,
    sellingPrice: 0,
    linearWeight: 0.31,
    thickness: null,
    height: 10,
    width: null,
    diameter: null,
    circumference: null,
    sectionArea: null,
    weight: null,
    matiere: 'Aluminium',
    productCode: 65,
  },
  {
    name: 'Barre carrée pleine',
    description: 'Hauteur : 12 mm',
    basePrice: null,
    unitPriceExclTax: 20,
    VATRate: null,
    marginPercent: null,
    sellingPrice: 0,
    linearWeight: 0.44,
    thickness: null,
    height: 12,
    width: null,
    diameter: null,
    circumference: null,
    sectionArea: null,
    weight: null,
    matiere: 'Aluminium',
    productCode: 66,
  },
  {
    name: 'Barre carrée pleine',
    description: 'Hauteur : 14 mm',
    basePrice: null,
    unitPriceExclTax: 20,
    VATRate: null,
    marginPercent: null,
    sellingPrice: 0,
    linearWeight: 0.61,
    thickness: null,
    height: 14,
    width: null,
    diameter: null,
    circumference: null,
    sectionArea: null,
    weight: null,
    matiere: 'Aluminium',
    productCode: 67,
  },
  {
    name: 'Barre carrée pleine',
    description: 'Hauteur : 16 mm',
    basePrice: null,
    unitPriceExclTax: 20,
    VATRate: null,
    marginPercent: null,
    sellingPrice: 0,
    linearWeight: 0.79,
    thickness: null,
    height: 16,
    width: null,
    diameter: null,
    circumference: null,
    sectionArea: null,
    weight: null,
    matiere: 'Aluminium',
    productCode: 68,
  },
  {
    name: 'Barre carrée pleine',
    description: 'Hauteur : 20 mm',
    basePrice: null,
    unitPriceExclTax: 20,
    VATRate: null,
    marginPercent: null,
    sellingPrice: 0,
    linearWeight: 1.23,
    thickness: null,
    height: 20,
    width: null,
    diameter: null,
    circumference: null,
    sectionArea: null,
    weight: null,
    matiere: 'Aluminium',
    productCode: 69,
  },
  {
    name: 'Barre carrée pleine',
    description: 'Hauteur : 25 mm',
    basePrice: null,
    unitPriceExclTax: 20,
    VATRate: null,
    marginPercent: null,
    sellingPrice: 0,
    linearWeight: 1.93,
    thickness: null,
    height: 25,
    width: null,
    diameter: null,
    circumference: null,
    sectionArea: null,
    weight: null,
    matiere: 'Aluminium',
    productCode: 70,
  },
  {
    name: 'Barre carrée pleine',
    description: 'Hauteur : 30 mm',
    basePrice: null,
    unitPriceExclTax: 20,
    VATRate: null,
    marginPercent: null,
    sellingPrice: 0,
    linearWeight: 2.48,
    thickness: null,
    height: 30,
    width: null,
    diameter: null,
    circumference: null,
    sectionArea: null,
    weight: null,
    matiere: 'Aluminium',
    productCode: 71,
  },
  {
    name: 'Barre carrée pleine',
    description: 'Hauteur : 40 mm',
    basePrice: null,
    unitPriceExclTax: 20,
    VATRate: null,
    marginPercent: null,
    sellingPrice: 0,
    linearWeight: 4.93,
    thickness: null,
    height: 40,
    width: null,
    diameter: null,
    circumference: null,
    sectionArea: null,
    weight: null,
    matiere: 'Aluminium',
    productCode: 72,
  },
  {
    name: 'Barre carrée pleine',
    description: 'Hauteur : 45 mm',
    basePrice: null,
    unitPriceExclTax: 20,
    VATRate: null,
    marginPercent: null,
    sellingPrice: 0,
    linearWeight: 6.24,
    thickness: null,
    height: 45,
    width: null,
    diameter: null,
    circumference: null,
    sectionArea: null,
    weight: null,
    matiere: 'Aluminium',
    productCode: 73,
  },
  {
    name: 'Barre carrée pleine',
    description: 'Hauteur : 50 mm',
    basePrice: null,
    unitPriceExclTax: 20,
    VATRate: null,
    marginPercent: null,
    sellingPrice: 0,
    linearWeight: 7.7,
    thickness: null,
    height: 50,
    width: null,
    diameter: null,
    circumference: null,
    sectionArea: null,
    weight: null,
    matiere: 'Aluminium',
    productCode: 74,
  },
  {
    name: 'Barre carrée pleine',
    description: 'Hauteur : 55 mm',
    basePrice: null,
    unitPriceExclTax: 20,
    VATRate: null,
    marginPercent: null,
    sellingPrice: 0,
    linearWeight: 9.32,
    thickness: null,
    height: 55,
    width: null,
    diameter: null,
    circumference: null,
    sectionArea: null,
    weight: null,
    matiere: 'Aluminium',
    productCode: 75,
  },
  {
    name: 'Barre carrée pleine',
    description: 'Hauteur : 60 mm',
    basePrice: null,
    unitPriceExclTax: 20,
    VATRate: null,
    marginPercent: null,
    sellingPrice: 0,
    linearWeight: 11.09,
    thickness: null,
    height: 60,
    width: null,
    diameter: null,
    circumference: null,
    sectionArea: null,
    weight: null,
    matiere: 'Aluminium',
    productCode: 76,
  },
  {
    name: 'Barre carrée pleine',
    description: 'Hauteur : 65 mm',
    basePrice: null,
    unitPriceExclTax: 20,
    VATRate: null,
    marginPercent: null,
    sellingPrice: 0,
    linearWeight: 13.01,
    thickness: null,
    height: 65,
    width: null,
    diameter: null,
    circumference: null,
    sectionArea: null,
    weight: null,
    matiere: 'Aluminium',
    productCode: 77,
  },
  {
    name: 'Barre carrée pleine',
    description: 'Hauteur : 70 mm',
    basePrice: null,
    unitPriceExclTax: 20,
    VATRate: null,
    marginPercent: null,
    sellingPrice: 0,
    linearWeight: 15.09,
    thickness: null,
    height: 70,
    width: null,
    diameter: null,
    circumference: null,
    sectionArea: null,
    weight: null,
    matiere: 'Aluminium',
    productCode: 78,
  },
  {
    name: 'Barre carrée pleine',
    description: 'Hauteur : 80 mm',
    basePrice: null,
    unitPriceExclTax: 20,
    VATRate: null,
    marginPercent: null,
    sellingPrice: 0,
    linearWeight: 19.71,
    thickness: null,
    height: 80,
    width: null,
    diameter: null,
    circumference: null,
    sectionArea: null,
    weight: null,
    matiere: 'Aluminium',
    productCode: 79,
  },
  {
    name: 'Barre carrée pleine',
    description: 'Hauteur : 90 mm',
    basePrice: null,
    unitPriceExclTax: 20,
    VATRate: null,
    marginPercent: null,
    sellingPrice: 0,
    linearWeight: 24.95,
    thickness: null,
    height: 90,
    width: null,
    diameter: null,
    circumference: null,
    sectionArea: null,
    weight: null,
    matiere: 'Aluminium',
    productCode: 80,
  },
  {
    name: 'Barre carrée pleine',
    description: 'Hauteur : 100 mm',
    basePrice: null,
    unitPriceExclTax: 20,
    VATRate: null,
    marginPercent: null,
    sellingPrice: 0,
    linearWeight: 30.8,
    thickness: null,
    height: 100,
    width: null,
    diameter: null,
    circumference: null,
    sectionArea: null,
    weight: null,
    matiere: 'Aluminium',
    productCode: 81,
  },
];

//Inox

const corniere_ailes_égales_inox = [
  {
    name: 'Cornière à ailes égales',
    description: 'Epaisseur : 3 mm Hauteur Ailes : 20 mm',
    basePrice: null,
    unitPriceExclTax: 18,
    VATRate: null,
    marginPercent: null,
    sellingPrice: 0,
    linearWeight: 0.97,
    thickness: 3,
    height: 20,
    width: null,
    diameter: null,
    circumference: null,
    sectionArea: 1.13,
    weight: null,
    matiere: 'Inox',
    productCode: 82,
  },
  {
    name: 'Cornière à ailes égales',
    description: 'Epaisseur : 3 mm Hauteur Ailes : 25 mm',
    basePrice: null,
    unitPriceExclTax: 18,
    VATRate: null,
    marginPercent: null,
    sellingPrice: 0,
    linearWeight: 1.23,
    thickness: 3,
    height: 25,
    width: null,
    diameter: null,
    circumference: null,
    sectionArea: 1.43,
    weight: null,
    matiere: 'Inox',
    productCode: 83,
  },
  {
    name: 'Cornière à ailes égales',
    description: 'Epaisseur : 3 mm Hauteur Ailes : 30 mm',
    basePrice: null,
    unitPriceExclTax: 18,
    VATRate: null,
    marginPercent: null,
    sellingPrice: 0,
    linearWeight: 1.5,
    thickness: 3,
    height: 30,
    width: null,
    diameter: null,
    circumference: null,
    sectionArea: 1.74,
    weight: null,
    matiere: 'Inox',
    productCode: 84,
  },
  {
    name: 'Cornière à ailes égales',
    description: 'Epaisseur : 4 mm Hauteur Ailes : 40 mm',
    basePrice: null,
    unitPriceExclTax: 18,
    VATRate: null,
    marginPercent: null,
    sellingPrice: 0,
    linearWeight: 2.66,
    thickness: 4,
    height: 40,
    width: null,
    diameter: null,
    circumference: null,
    sectionArea: 3.08,
    weight: null,
    matiere: 'Inox',
    productCode: 85,
  },
  {
    name: 'Cornière à ailes égales',
    description: 'Epaisseur : 5 mm Hauteur Ailes : 50 mm',
    basePrice: null,
    unitPriceExclTax: 18,
    VATRate: null,
    marginPercent: null,
    sellingPrice: 0,
    linearWeight: 4.15,
    thickness: 5,
    height: 50,
    width: null,
    diameter: null,
    circumference: null,
    sectionArea: 4.8,
    weight: null,
    matiere: 'Inox',
    productCode: 86,
  },
  {
    name: 'Cornière à ailes égales',
    description: 'Epaisseur : 6 mm Hauteur Ailes : 60 mm',
    basePrice: null,
    unitPriceExclTax: 18,
    VATRate: null,
    marginPercent: null,
    sellingPrice: 0,
    linearWeight: 5.96,
    thickness: 6,
    height: 60,
    width: null,
    diameter: null,
    circumference: null,
    sectionArea: 6.91,
    weight: null,
    matiere: 'Inox',
    productCode: 87,
  },
  {
    name: 'Cornière à ailes égales',
    description: 'Epaisseur : 7 mm Hauteur Ailes : 70 mm',
    basePrice: null,
    unitPriceExclTax: 18,
    VATRate: null,
    marginPercent: null,
    sellingPrice: 0,
    linearWeight: 8.12,
    thickness: 7,
    height: 70,
    width: null,
    diameter: null,
    circumference: null,
    sectionArea: 9.4,
    weight: null,
    matiere: 'Inox',
    productCode: 88,
  },
  {
    name: 'Cornière à ailes égales',
    description: 'Epaisseur : 8 mm Hauteur Ailes : 80 mm',
    basePrice: null,
    unitPriceExclTax: 18,
    VATRate: null,
    marginPercent: null,
    sellingPrice: 0,
    linearWeight: 10.59,
    thickness: 8,
    height: 80,
    width: null,
    diameter: null,
    circumference: null,
    sectionArea: 12.3,
    weight: null,
    matiere: 'Inox',
    productCode: 89,
  },
  {
    name: 'Cornière à ailes égales',
    description: 'Epaisseur : 10 mm Hauteur Ailes : 100 mm',
    basePrice: null,
    unitPriceExclTax: 18,
    VATRate: null,
    marginPercent: null,
    sellingPrice: 0,
    linearWeight: 16.5,
    thickness: 10,
    height: 100,
    width: null,
    diameter: null,
    circumference: null,
    sectionArea: 19.2,
    weight: null,
    matiere: 'Inox',
    productCode: 90,
  },
];

const fer_T_inox = [
  {
    name: 'FER T',
    description: 'Epaisseur : 3 mm Hauteur : 20 mm Largeur : 20 mm',
    basePrice: null,
    unitPriceExclTax: 18,
    VATRate: null,
    marginPercent: null,
    sellingPrice: 0,
    linearWeight: 0.97,
    thickness: 3,
    height: 20,
    width: 20,
    diameter: null,
    circumference: null,
    sectionArea: 0,
    weight: null,
    matiere: 'Inox',
    productCode: 91,
  },
  {
    name: 'FER T',
    description: 'Epaisseur : 4 mm Hauteur : 20 mm Largeur : 20 mm',
    basePrice: null,
    unitPriceExclTax: 18,
    VATRate: null,
    marginPercent: null,
    sellingPrice: 0,
    linearWeight: 1.32,
    thickness: 4,
    height: 20,
    width: 20,
    diameter: null,
    circumference: null,
    sectionArea: 0,
    weight: null,
    matiere: 'Inox',
    productCode: 92,
  },
  {
    name: 'FER T',
    description: 'Epaisseur : 3 mm Hauteur : 30 mm Largeur : 30 mm',
    basePrice: null,
    unitPriceExclTax: 18,
    VATRate: null,
    marginPercent: null,
    sellingPrice: 0,
    linearWeight: 1.51,
    thickness: 3,
    height: 30,
    width: 30,
    diameter: null,
    circumference: null,
    sectionArea: 0,
    weight: null,
    matiere: 'Inox',
    productCode: 93,
  },
  {
    name: 'FER T',
    description: 'Epaisseur : 4 mm Hauteur : 40 mm Largeur : 40 mm',
    basePrice: null,
    unitPriceExclTax: 18,
    VATRate: null,
    marginPercent: null,
    sellingPrice: 0,
    linearWeight: 2.67,
    thickness: 4,
    height: 40,
    width: 40,
    diameter: null,
    circumference: null,
    sectionArea: 0,
    weight: null,
    matiere: 'Inox',
    productCode: 94,
  },
  {
    name: 'FER T',
    description: 'Epaisseur : 5 mm Hauteur : 50 mm Largeur : 50 mm',
    basePrice: null,
    unitPriceExclTax: 18,
    VATRate: null,
    marginPercent: null,
    sellingPrice: 0,
    linearWeight: 4.18,
    thickness: 5,
    height: 50,
    width: 50,
    diameter: null,
    circumference: null,
    sectionArea: 0,
    weight: null,
    matiere: 'Inox',
    productCode: 95,
  },
  {
    name: 'FER T',
    description: 'Epaisseur : 6 mm Hauteur : 60 mm Largeur : 60 mm',
    basePrice: null,
    unitPriceExclTax: 18,
    VATRate: null,
    marginPercent: null,
    sellingPrice: 0,
    linearWeight: 6.02,
    thickness: 6,
    height: 60,
    width: 60,
    diameter: null,
    circumference: null,
    sectionArea: 0,
    weight: null,
    matiere: 'Inox',
    productCode: 96,
  },
  {
    name: 'FER T',
    description: 'Epaisseur : 8 mm Hauteur : 80 mm Largeur : 80 mm',
    basePrice: null,
    unitPriceExclTax: 18,
    VATRate: null,
    marginPercent: null,
    sellingPrice: 0,
    linearWeight: 10.7,
    thickness: 8,
    height: 80,
    width: 80,
    diameter: null,
    circumference: null,
    sectionArea: 0,
    weight: null,
    matiere: 'Inox',
    productCode: 97,
  },
  {
    name: 'FER T',
    description: 'Epaisseur : 9 mm Hauteur : 90 mm Largeur : 90 mm',
    basePrice: null,
    unitPriceExclTax: 18,
    VATRate: null,
    marginPercent: null,
    sellingPrice: 0,
    linearWeight: 13.42,
    thickness: 9,
    height: 90,
    width: 90,
    diameter: null,
    circumference: null,
    sectionArea: 0,
    weight: null,
    matiere: 'Inox',
    productCode: 98,
  },
  {
    name: 'FER T',
    description: 'Epaisseur : 10 mm Hauteur : 100 mm Largeur : 100 mm',
    basePrice: null,
    unitPriceExclTax: 18,
    VATRate: null,
    marginPercent: null,
    sellingPrice: 0,
    linearWeight: 16.61,
    thickness: 10,
    height: 100,
    width: 100,
    diameter: null,
    circumference: null,
    sectionArea: 0,
    weight: null,
    matiere: 'Inox',
    productCode: 99,
  },
];

const tube_rond_inox = [
  {
    name: 'Tube rond',
    description: 'Diamètre extérieur : 17.2 mm Epaisseur : 1.6 mm',
    basePrice: null,
    unitPriceExclTax: 18,
    VATRate: null,
    marginPercent: null,
    sellingPrice: 0,
    linearWeight: 0.69,
    thickness: 1.6,
    height: null,
    width: null,
    diameter: 17.2,
    circumference: null,
    sectionArea: null,
    weight: null,
    matiere: 'Inox',
    productCode: 100,
  },
  {
    name: 'Tube rond',
    description: 'Diamètre extérieur : 21.3 mm Epaisseur : 1.6 mm',
    basePrice: null,
    unitPriceExclTax: 18,
    VATRate: null,
    marginPercent: null,
    sellingPrice: 0,
    linearWeight: 0.87,
    thickness: 1.6,
    height: null,
    width: null,
    diameter: 21.3,
    circumference: null,
    sectionArea: null,
    weight: null,
    matiere: 'Inox',
    productCode: 101,
  },
  {
    name: 'Tube rond',
    description: 'Diamètre extérieur : 25 mm Epaisseur : 1.5 mm',
    basePrice: null,
    unitPriceExclTax: 18,
    VATRate: null,
    marginPercent: null,
    sellingPrice: 0,
    linearWeight: 0.96,
    thickness: 1.5,
    height: null,
    width: null,
    diameter: 25,
    circumference: null,
    sectionArea: null,
    weight: null,
    matiere: 'Inox',
    productCode: 102,
  },
  {
    name: 'Tube rond',
    description: 'Diamètre extérieur : 25 mm Epaisseur : 2 mm',
    basePrice: null,
    unitPriceExclTax: 18,
    VATRate: null,
    marginPercent: null,
    sellingPrice: 0,
    linearWeight: 1.24,
    thickness: 2,
    height: null,
    width: null,
    diameter: 25,
    circumference: null,
    sectionArea: null,
    weight: null,
    matiere: 'Inox',
    productCode: 103,
  },
  {
    name: 'Tube rond',
    description: 'Diamètre extérieur : 26.9 mm Epaisseur : 1.6 mm',
    basePrice: null,
    unitPriceExclTax: 18,
    VATRate: null,
    marginPercent: null,
    sellingPrice: 0,
    linearWeight: 1.11,
    thickness: 1.6,
    height: null,
    width: null,
    diameter: 26.9,
    circumference: null,
    sectionArea: null,
    weight: null,
    matiere: 'Inox',
    productCode: 104,
  },
  {
    name: 'Tube rond',
    description: 'Diamètre extérieur : 26.9 mm Epaisseur : 2 mm',
    basePrice: null,
    unitPriceExclTax: 18,
    VATRate: null,
    marginPercent: null,
    sellingPrice: 0,
    linearWeight: 1.35,
    thickness: 2,
    height: null,
    width: null,
    diameter: 26.9,
    circumference: null,
    sectionArea: null,
    weight: null,
    matiere: 'Inox',
    productCode: 105,
  },
  {
    name: 'Tube rond',
    description: 'Diamètre extérieur : 30 mm Epaisseur : 2 mm',
    basePrice: null,
    unitPriceExclTax: 18,
    VATRate: null,
    marginPercent: null,
    sellingPrice: 0,
    linearWeight: 1.52,
    thickness: 2,
    height: null,
    width: null,
    diameter: 30,
    circumference: null,
    sectionArea: null,
    weight: null,
    matiere: 'Inox',
    productCode: 106,
  },
  {
    name: 'Tube rond',
    description: 'Diamètre extérieur : 33.7 mm Epaisseur : 1.5 mm',
    basePrice: null,
    unitPriceExclTax: 18,
    VATRate: null,
    marginPercent: null,
    sellingPrice: 0,
    linearWeight: 2.43,
    thickness: 1.5,
    height: null,
    width: null,
    diameter: 33.7,
    circumference: null,
    sectionArea: null,
    weight: null,
    matiere: 'Inox',
    productCode: 107,
  },
  {
    name: 'Tube rond',
    description: 'Diamètre extérieur : 33.7 mm Epaisseur : 2 mm',
    basePrice: null,
    unitPriceExclTax: 18,
    VATRate: null,
    marginPercent: null,
    sellingPrice: 0,
    linearWeight: 1.72,
    thickness: 2,
    height: null,
    width: null,
    diameter: 33.7,
    circumference: null,
    sectionArea: null,
    weight: null,
    matiere: 'Inox',
    productCode: 108,
  },
  {
    name: 'Tube rond',
    description: 'Diamètre extérieur : 33.7 mm Epaisseur : 2.6 mm',
    basePrice: null,
    unitPriceExclTax: 18,
    VATRate: null,
    marginPercent: null,
    sellingPrice: 0,
    linearWeight: 2.19,
    thickness: 2.6,
    height: null,
    width: null,
    diameter: 33.7,
    circumference: null,
    sectionArea: null,
    weight: null,
    matiere: 'Inox',
    productCode: 109,
  },
  {
    name: 'Tube rond',
    description: 'Diamètre extérieur : 35 mm Epaisseur : 2 mm',
    basePrice: null,
    unitPriceExclTax: 18,
    VATRate: null,
    marginPercent: null,
    sellingPrice: 0,
    linearWeight: 1.79,
    thickness: 2,
    height: null,
    width: null,
    diameter: 35,
    circumference: null,
    sectionArea: null,
    weight: null,
    matiere: 'Inox',
    productCode: 110,
  },
  {
    name: 'Tube rond',
    description: 'Diamètre extérieur : 40 mm Epaisseur : 2 mm',
    basePrice: null,
    unitPriceExclTax: 18,
    VATRate: null,
    marginPercent: null,
    sellingPrice: 0,
    linearWeight: 2.06,
    thickness: 2,
    height: null,
    width: null,
    diameter: 40,
    circumference: null,
    sectionArea: null,
    weight: null,
    matiere: 'Inox',
    productCode: 111,
  },
  {
    name: 'Tube rond',
    description: 'Diamètre extérieur : 42.4 mm Epaisseur : 2 mm',
    basePrice: null,
    unitPriceExclTax: 18,
    VATRate: null,
    marginPercent: null,
    sellingPrice: 0,
    linearWeight: 2.19,
    thickness: 2,
    height: null,
    width: null,
    diameter: 42.4,
    circumference: null,
    sectionArea: null,
    weight: null,
    matiere: 'Inox',
    productCode: 112,
  },
  {
    name: 'Tube rond',
    description: 'Diamètre extérieur : 42.4 mm Epaisseur : 3.2 mm',
    basePrice: null,
    unitPriceExclTax: 18,
    VATRate: null,
    marginPercent: null,
    sellingPrice: 0,
    linearWeight: 3.4,
    thickness: 3.2,
    height: null,
    width: null,
    diameter: 42.4,
    circumference: null,
    sectionArea: null,
    weight: null,
    matiere: 'Inox',
    productCode: 113,
  },
  {
    name: 'Tube rond',
    description: 'Diamètre extérieur : 43 mm Epaisseur : 1.5 mm',
    basePrice: null,
    unitPriceExclTax: 18,
    VATRate: null,
    marginPercent: null,
    sellingPrice: 0,
    linearWeight: 1.79,
    thickness: 1.5,
    height: null,
    width: null,
    diameter: 43,
    circumference: null,
    sectionArea: null,
    weight: null,
    matiere: 'Inox',
    productCode: 114,
  },
  {
    name: 'Tube rond',
    description: 'Diamètre extérieur : 48.3 mm Epaisseur : 3.2 mm',
    basePrice: null,
    unitPriceExclTax: 18,
    VATRate: null,
    marginPercent: null,
    sellingPrice: 0,
    linearWeight: 3.92,
    thickness: 3.2,
    height: null,
    width: null,
    diameter: 48.3,
    circumference: null,
    sectionArea: null,
    weight: null,
    matiere: 'Inox',
    productCode: 115,
  },
  {
    name: 'Tube rond',
    description: 'Diamètre extérieur : 60.3 mm Epaisseur : 2 mm',
    basePrice: null,
    unitPriceExclTax: 18,
    VATRate: null,
    marginPercent: null,
    sellingPrice: 0,
    linearWeight: 3.21,
    thickness: 2,
    height: null,
    width: null,
    diameter: 60.3,
    circumference: null,
    sectionArea: null,
    weight: null,
    matiere: 'Inox',
    productCode: 116,
  },
  {
    name: 'Tube rond',
    description: 'Diamètre extérieur : 60.3 mm Epaisseur : 3.6 mm',
    basePrice: null,
    unitPriceExclTax: 18,
    VATRate: null,
    marginPercent: null,
    sellingPrice: 0,
    linearWeight: 6.11,
    thickness: 3.6,
    height: null,
    width: null,
    diameter: 60.3,
    circumference: null,
    sectionArea: null,
    weight: null,
    matiere: 'Inox',
    productCode: 117,
  },
];

const barre_ronde_plein_inox = [
  {
    name: 'Barre ronde pleine',
    description: 'Diamètre : 6 mm Circonfèrence : 18.8 mm',
    basePrice: null,
    unitPriceExclTax: 18,
    VATRate: null,
    marginPercent: null,
    sellingPrice: 0,
    linearWeight: 0.24,
    thickness: null,
    height: null,
    width: null,
    diameter: 6,
    circumference: 18.8,
    sectionArea: 0.28,
    weight: null,
    matiere: 'Inox',
    productCode: 118,
  },
  {
    name: 'Barre ronde pleine',
    description: 'Diamètre : 8 mm Circonfèrence : 25.1 mm',
    basePrice: null,
    unitPriceExclTax: 18,
    VATRate: null,
    marginPercent: null,
    sellingPrice: 0,
    linearWeight: 0.43,
    thickness: null,
    height: null,
    width: null,
    diameter: 8,
    circumference: 25.1,
    sectionArea: 0.5,
    weight: null,
    matiere: 'Inox',
    productCode: 119,
  },
  {
    name: 'Barre ronde pleine',
    description: 'Diamètre : 10 mm Circonfèrence : 31.4 mm',
    basePrice: null,
    unitPriceExclTax: 18,
    VATRate: null,
    marginPercent: null,
    sellingPrice: 0,
    linearWeight: 0.68,
    thickness: null,
    height: null,
    width: null,
    diameter: 10,
    circumference: 31.4,
    sectionArea: 0.79,
    weight: null,
    matiere: 'Inox',
    productCode: 120,
  },
  {
    name: 'Barre ronde pleine',
    description: 'Diamètre : 12 mm Circonfèrence : 37.7 mm',
    basePrice: null,
    unitPriceExclTax: 18,
    VATRate: null,
    marginPercent: null,
    sellingPrice: 0,
    linearWeight: 0.98,
    thickness: null,
    height: null,
    width: null,
    diameter: 12,
    circumference: 37.7,
    sectionArea: 1.13,
    weight: null,
    matiere: 'Inox',
    productCode: 121,
  },
  {
    name: 'Barre ronde pleine',
    description: 'Diamètre : 14 mm Circonfèrence : 44.0 mm',
    basePrice: null,
    unitPriceExclTax: 18,
    VATRate: null,
    marginPercent: null,
    sellingPrice: 0,
    linearWeight: 1.33,
    thickness: null,
    height: null,
    width: null,
    diameter: 14,
    circumference: 44,
    sectionArea: 1.54,
    weight: null,
    matiere: 'Inox',
    productCode: 122,
  },
  {
    name: 'Barre ronde pleine',
    description: 'Diamètre : 16 mm Circonfèrence : 50.3 mm',
    basePrice: null,
    unitPriceExclTax: 18,
    VATRate: null,
    marginPercent: null,
    sellingPrice: 0,
    linearWeight: 1.74,
    thickness: null,
    height: null,
    width: null,
    diameter: 16,
    circumference: 50.3,
    sectionArea: 2.01,
    weight: null,
    matiere: 'Inox',
    productCode: 123,
  },
  {
    name: 'Barre ronde pleine',
    description: 'Diamètre : 18 mm Circonfèrence : 56.5 mm',
    basePrice: null,
    unitPriceExclTax: 18,
    VATRate: null,
    marginPercent: null,
    sellingPrice: 0,
    linearWeight: 2.2,
    thickness: null,
    height: null,
    width: null,
    diameter: 18,
    circumference: 56.5,
    sectionArea: 2.54,
    weight: null,
    matiere: 'Inox',
    productCode: 124,
  },
  {
    name: 'Barre ronde pleine',
    description: 'Diamètre : 20 mm Circonfèrence : 62.8 mm',
    basePrice: null,
    unitPriceExclTax: 18,
    VATRate: null,
    marginPercent: null,
    sellingPrice: 0,
    linearWeight: 2.72,
    thickness: null,
    height: null,
    width: null,
    diameter: 20,
    circumference: 62.8,
    sectionArea: 3.14,
    weight: null,
    matiere: 'Inox',
    productCode: 125,
  },
  {
    name: 'Barre ronde pleine',
    description: 'Diamètre : 25 mm Circonfèrence : 78.5 mm',
    basePrice: null,
    unitPriceExclTax: 18,
    VATRate: null,
    marginPercent: null,
    sellingPrice: 0,
    linearWeight: 4.24,
    thickness: null,
    height: null,
    width: null,
    diameter: 25,
    circumference: 78.5,
    sectionArea: 4.91,
    weight: null,
    matiere: 'Inox',
    productCode: 126,
  },
  {
    name: 'Barre ronde pleine',
    description: 'Diamètre : 30 mm Circonfèrence : 94.2 mm',
    basePrice: null,
    unitPriceExclTax: 18,
    VATRate: null,
    marginPercent: null,
    sellingPrice: 0,
    linearWeight: 6.11,
    thickness: null,
    height: null,
    width: null,
    diameter: 30,
    circumference: 94.2,
    sectionArea: 7.07,
    weight: null,
    matiere: 'Inox',
    productCode: 127,
  },
  {
    name: 'Barre ronde pleine',
    description: 'Diamètre : 40 mm Circonfèrence : 126 mm',
    basePrice: null,
    unitPriceExclTax: 18,
    VATRate: null,
    marginPercent: null,
    sellingPrice: 0,
    linearWeight: 10.85,
    thickness: null,
    height: null,
    width: null,
    diameter: 40,
    circumference: 126,
    sectionArea: 12.6,
    weight: null,
    matiere: 'Inox',
    productCode: 128,
  },
  {
    name: 'Barre ronde pleine',
    description: 'Diamètre : 50 mm Circonfèrence : 157 mm',
    basePrice: null,
    unitPriceExclTax: 18,
    VATRate: null,
    marginPercent: null,
    sellingPrice: 0,
    linearWeight: 16.94,
    thickness: null,
    height: null,
    width: null,
    diameter: 50,
    circumference: 157,
    sectionArea: 19.6,
    weight: null,
    matiere: 'Inox',
    productCode: 129,
  },
  {
    name: 'Barre ronde pleine',
    description: 'Diamètre : 60 mm Circonfèrence : 188 mm',
    basePrice: null,
    unitPriceExclTax: 18,
    VATRate: null,
    marginPercent: null,
    sellingPrice: 0,
    linearWeight: 24.42,
    thickness: null,
    height: null,
    width: null,
    diameter: 60,
    circumference: 188,
    sectionArea: 28.3,
    weight: null,
    matiere: 'Inox',
    productCode: 130,
  },
  {
    name: 'Barre ronde pleine',
    description: 'Diamètre : 80 mm Circonfèrence : 251 mm',
    basePrice: null,
    unitPriceExclTax: 18,
    VATRate: null,
    marginPercent: null,
    sellingPrice: 0,
    linearWeight: 43.45,
    thickness: null,
    height: null,
    width: null,
    diameter: 80,
    circumference: 251,
    sectionArea: 50.3,
    weight: null,
    matiere: 'Inox',
    productCode: 131,
  },
  {
    name: 'Barre ronde pleine',
    description: 'Diamètre : 100 mm Circonfèrence : 314 mm',
    basePrice: null,
    unitPriceExclTax: 18,
    VATRate: null,
    marginPercent: null,
    sellingPrice: 0,
    linearWeight: 67.87,
    thickness: null,
    height: null,
    width: null,
    diameter: 100,
    circumference: 314,
    sectionArea: 78.5,
    weight: null,
    matiere: 'Inox',
    productCode: 132,
  },
];

const fer_plat_inox = [
  {
    name: 'Fer plat',
    description: 'Epaisseur : 3 mm Largeur : 20 mm',
    basePrice: null,
    unitPriceExclTax: 18,
    VATRate: null,
    marginPercent: null,
    sellingPrice: 0,
    linearWeight: 0.52,
    thickness: 3,
    width: 20,
    height: null,
    diameter: null,
    circumference: null,
    sectionArea: null,
    weight: null,
    material: 'Inox',
    productCode: 133,
  },
  {
    name: 'Fer plat',
    description: 'Epaisseur : 4 mm Largeur : 20 mm',
    basePrice: null,
    unitPriceExclTax: 18,
    VATRate: null,
    marginPercent: null,
    sellingPrice: 0,
    linearWeight: 0.7,
    thickness: 4,
    width: 20,
    height: null,
    diameter: null,
    circumference: null,
    sectionArea: null,
    weight: null,
    material: 'Inox',
    productCode: 134,
  },
  {
    name: 'Fer plat',
    description: 'Epaisseur : 5 mm Largeur : 20 mm',
    basePrice: null,
    unitPriceExclTax: 18,
    VATRate: null,
    marginPercent: null,
    sellingPrice: 0,
    linearWeight: 0.87,
    thickness: 5,
    width: 20,
    height: null,
    diameter: null,
    circumference: null,
    sectionArea: null,
    weight: null,
    material: 'Inox',
    productCode: 135,
  },
  {
    name: 'Fer plat',
    description: 'Epaisseur : 6 mm Largeur : 20 mm',
    basePrice: null,
    unitPriceExclTax: 18,
    VATRate: null,
    marginPercent: null,
    sellingPrice: 0,
    linearWeight: 1.03,
    thickness: 6,
    width: 20,
    height: null,
    diameter: null,
    circumference: null,
    sectionArea: null,
    weight: null,
    material: 'Inox',
    productCode: 136,
  },
  {
    name: 'Fer plat',
    description: 'Epaisseur : 8 mm Largeur : 20 mm',
    basePrice: null,
    unitPriceExclTax: 18,
    VATRate: null,
    marginPercent: null,
    sellingPrice: 0,
    linearWeight: 1.43,
    thickness: 8,
    width: 20,
    height: null,
    diameter: null,
    circumference: null,
    sectionArea: null,
    weight: null,
    material: 'Inox',
    productCode: 137,
  },
  {
    name: 'Fer plat',
    description: 'Epaisseur : 3 mm Largeur : 25 mm',
    basePrice: null,
    unitPriceExclTax: 18,
    VATRate: null,
    marginPercent: null,
    sellingPrice: 0,
    linearWeight: 0.66,
    thickness: 3,
    width: 25,
    height: null,
    diameter: null,
    circumference: null,
    sectionArea: null,
    weight: null,
    material: 'Inox',
    productCode: 138,
  },
  {
    name: 'Fer plat',
    description: 'Epaisseur : 4 mm Largeur : 25 mm',
    basePrice: null,
    unitPriceExclTax: 18,
    VATRate: null,
    marginPercent: null,
    sellingPrice: 0,
    linearWeight: 0.88,
    thickness: 4,
    width: 25,
    height: null,
    diameter: null,
    circumference: null,
    sectionArea: null,
    weight: null,
    material: 'Inox',
    productCode: 139,
  },
  {
    name: 'Fer plat',
    description: 'Epaisseur : 5 mm Largeur : 25 mm',
    basePrice: null,
    unitPriceExclTax: 18,
    VATRate: null,
    marginPercent: null,
    sellingPrice: 0,
    linearWeight: 1.08,
    thickness: 5,
    width: 25,
    height: null,
    diameter: null,
    circumference: null,
    sectionArea: null,
    weight: null,
    material: 'Inox',
    productCode: 140,
  },
  {
    name: 'Fer plat',
    description: 'Epaisseur : 6 mm Largeur : 25 mm',
    basePrice: null,
    unitPriceExclTax: 18,
    VATRate: null,
    marginPercent: null,
    sellingPrice: 0,
    linearWeight: 1.3,
    thickness: 6,
    width: 25,
    height: null,
    diameter: null,
    circumference: null,
    sectionArea: null,
    weight: null,
    material: 'Inox',
    productCode: 141,
  },
  {
    name: 'Fer plat',
    description: 'Epaisseur : 8 mm Largeur : 25 mm',
    basePrice: null,
    unitPriceExclTax: 18,
    VATRate: null,
    marginPercent: null,
    sellingPrice: 0,
    linearWeight: 1.73,
    thickness: 8,
    width: 25,
    height: null,
    diameter: null,
    circumference: null,
    sectionArea: null,
    weight: null,
    material: 'Inox',
    productCode: 142,
  },
];

// Acier

const cornieres_ailes_egales_acier = [
  {
    name: 'Cornière à ailes égales',
    description: 'Epaisseur : 3 mm Hauteur Ailes : 20 mm',
    basePrice: null,
    unitPriceExclTax: 3,
    VATRate: null,
    marginPercent: null,
    sellingPrice: 0,
    thickness: 3,
    height: 20,
    width: null,
    linearWeight: 0.97,
    material: 'Acier',
    productCode: 142,
  },
  {
    name: 'Cornière à ailes égales',
    description: 'Epaisseur : 3 mm Hauteur Ailes : 25 mm',
    basePrice: null,
    unitPriceExclTax: 3,
    VATRate: null,
    marginPercent: null,
    sellingPrice: 0,
    thickness: 3,
    height: 25,
    width: null,
    linearWeight: 1.23,
    material: 'Acier',
    productCode: 143,
  },
  {
    name: 'Cornière à ailes égales',
    description: 'Epaisseur : 3 mm Hauteur Ailes : 30 mm',
    basePrice: null,
    unitPriceExclTax: 3,
    VATRate: null,
    marginPercent: null,
    sellingPrice: 0,
    thickness: 3,
    height: 30,
    width: null,
    linearWeight: 1.5,
    material: 'Acier',
    productCode: 144,
  },
  {
    name: 'Cornière à ailes égales',
    description: 'Epaisseur : 3.5 mm Hauteur Ailes : 35 mm',
    basePrice: null,
    unitPriceExclTax: 3,
    VATRate: null,
    marginPercent: null,
    sellingPrice: 0,
    thickness: 3.5,
    height: 35,
    width: null,
    linearWeight: 2.04,
    material: 'Acier',
    productCode: 145,
  },
  {
    name: 'Cornière à ailes égales',
    description: 'Epaisseur : 4 mm Hauteur Ailes : 40 mm',
    basePrice: null,
    unitPriceExclTax: 3,
    VATRate: null,
    marginPercent: null,
    sellingPrice: 0,
    thickness: 4,
    height: 40,
    width: null,
    linearWeight: 2.66,
    material: 'Acier',
    productCode: 146,
  },
  {
    name: 'Cornière à ailes égales',
    description: 'Epaisseur : 4.5 mm Hauteur Ailes : 45 mm',
    basePrice: null,
    unitPriceExclTax: 3,
    VATRate: null,
    marginPercent: null,
    sellingPrice: 0,
    thickness: 4.5,
    height: 45,
    width: null,
    linearWeight: 3.37,
    material: 'Acier',
    productCode: 147,
  },
  {
    name: 'Cornière à ailes égales',
    description: 'Epaisseur : 5 mm Hauteur Ailes : 50 mm',
    basePrice: null,
    unitPriceExclTax: 3,
    VATRate: null,
    marginPercent: null,
    sellingPrice: 0,
    thickness: 5,
    height: 50,
    width: null,
    linearWeight: 4.15,
    material: 'Acier',
    productCode: 148,
  },
  {
    name: 'Cornière à ailes égales',
    description: 'Epaisseur : 6 mm Hauteur Ailes : 60 mm',
    basePrice: null,
    unitPriceExclTax: 3,
    VATRate: null,
    marginPercent: null,
    sellingPrice: 0,
    thickness: 6,
    height: 60,
    width: null,
    linearWeight: 5.96,
    material: 'Acier',
    productCode: 149,
  },
  {
    name: 'Cornière à ailes égales',
    description: 'Epaisseur : 7 mm Hauteur Ailes : 70 mm',
    basePrice: null,
    unitPriceExclTax: 3,
    VATRate: null,
    marginPercent: null,
    sellingPrice: 0,
    thickness: 7,
    height: 70,
    width: null,
    linearWeight: 8.12,
    material: 'Acier',
    productCode: 150,
  },
  {
    name: 'Cornière à ailes égales',
    description: 'Epaisseur : 8 mm Hauteur Ailes : 80 mm',
    basePrice: null,
    unitPriceExclTax: 3,
    VATRate: null,
    marginPercent: null,
    sellingPrice: 0,
    thickness: 8,
    height: 80,
    width: null,
    linearWeight: 10.59,
    material: 'Acier',
    productCode: 151,
  },
  {
    name: 'Cornière à ailes égales',
    description: 'Epaisseur : 9 mm Hauteur Ailes : 90 mm',
    basePrice: null,
    unitPriceExclTax: 3,
    VATRate: null,
    marginPercent: null,
    sellingPrice: 0,
    thickness: 9,
    height: 90,
    width: null,
    linearWeight: 13.42,
    material: 'Acier',
    productCode: 152,
  },
  {
    name: 'Cornière à ailes égales',
    description: 'Epaisseur : 10 mm Hauteur Ailes : 100 mm',
    basePrice: null,
    unitPriceExclTax: 3,
    VATRate: null,
    marginPercent: null,
    sellingPrice: 0,
    thickness: 10,
    height: 100,
    width: null,
    linearWeight: 16.5,
    material: 'Acier',
    productCode: 153,
  },
  {
    name: 'Cornière à ailes égales',
    description: 'Epaisseur : 12 mm Hauteur Ailes : 120 mm',
    basePrice: null,
    unitPriceExclTax: 3,
    VATRate: null,
    marginPercent: null,
    sellingPrice: 0,
    thickness: 12,
    height: 120,
    width: null,
    linearWeight: 23.76,
    material: 'Acier',
    productCode: 154,
  },
  {
    name: 'Cornière à ailes égales',
    description: 'Epaisseur : 15 mm Hauteur Ailes : 150 mm',
    basePrice: null,
    unitPriceExclTax: 3,
    VATRate: null,
    marginPercent: null,
    sellingPrice: 0,
    thickness: 15,
    height: 150,
    width: null,
    linearWeight: 37.18,
    material: 'Acier',
    productCode: 155,
  },
  {
    name: 'Cornière à ailes égales',
    description: 'Epaisseur : 20 mm Hauteur Ailes : 200 mm',
    basePrice: null,
    unitPriceExclTax: 3,
    VATRate: null,
    marginPercent: null,
    sellingPrice: 0,
    thickness: 20,
    height: 200,
    width: null,
    linearWeight: 65.89,
    material: 'Acier',
    productCode: 156,
  },
];

const cornieres_ailes_inegales_acier = [
  {
    name: 'Cornière à ailes inégales',
    description: 'Hauteur : 30 mm Largeur : 20 mm Epaisseur : 3 mm',
    basePrice: null,
    unitPriceExclTax: 3,
    VATRate: null,
    marginPercent: null,
    sellingPrice: 0,
    thickness: 3,
    height: 30,
    width: 20,
    linearWeight: 1.61,
    material: 'Acier',
    productCode: 157,
  },
  {
    name: 'Cornière à ailes inégales',
    description: 'Hauteur : 40 mm Largeur : 25 mm Epaisseur : 4 mm',
    basePrice: null,
    unitPriceExclTax: 3,
    VATRate: null,
    marginPercent: null,
    sellingPrice: 0,
    thickness: 4,
    height: 40,
    width: 25,
    linearWeight: 2.12,
    material: 'Acier',
    productCode: 158,
  },
  {
    name: 'Cornière à ailes inégales',
    description: 'Hauteur : 45 mm Largeur : 30 mm Epaisseur : 4 mm',
    basePrice: null,
    unitPriceExclTax: 3,
    VATRate: null,
    marginPercent: null,
    sellingPrice: 0,
    thickness: 4,
    height: 45,
    width: 30,
    linearWeight: 2.46,
    material: 'Acier',
    productCode: 159,
  },
  {
    name: 'Cornière à ailes inégales',
    description: 'Hauteur : 50 mm Largeur : 30 mm Epaisseur : 5 mm',
    basePrice: null,
    unitPriceExclTax: 3,
    VATRate: null,
    marginPercent: null,
    sellingPrice: 0,
    thickness: 5,
    height: 50,
    width: 30,
    linearWeight: 3.26,
    material: 'Acier',
    productCode: 160,
  },
  {
    name: 'Cornière à ailes inégales',
    description: 'Hauteur : 60 mm Largeur : 40 mm Epaisseur : 5 mm',
    basePrice: null,
    unitPriceExclTax: 3,
    VATRate: null,
    marginPercent: null,
    sellingPrice: 0,
    thickness: 5,
    height: 60,
    width: 40,
    linearWeight: 4.14,
    material: 'Acier',
    productCode: 161,
  },
  {
    name: 'Cornière à ailes inégales',
    description: 'Hauteur : 70 mm Largeur : 50 mm Epaisseur : 6 mm',
    basePrice: null,
    unitPriceExclTax: 3,
    VATRate: null,
    marginPercent: null,
    sellingPrice: 0,
    thickness: 6,
    height: 70,
    width: 50,
    linearWeight: 6.86,
    material: 'Acier',
    productCode: 162,
  },
  {
    name: 'Cornière à ailes inégales',
    description: 'Hauteur : 80 mm Largeur : 60 mm Epaisseur : 7 mm',
    basePrice: null,
    unitPriceExclTax: 3,
    VATRate: null,
    marginPercent: null,
    sellingPrice: 0,
    thickness: 7,
    height: 80,
    width: 60,
    linearWeight: 8.1,
    material: 'Acier',
    productCode: 163,
  },
  {
    name: 'Cornière à ailes inégales',
    description: 'Hauteur : 100 mm Largeur : 75 mm Epaisseur : 9 mm',
    basePrice: null,
    unitPriceExclTax: 3,
    VATRate: null,
    marginPercent: null,
    sellingPrice: 0,
    thickness: 9,
    height: 100,
    width: 75,
    linearWeight: 12.98,
    material: 'Acier',
    productCode: 164,
  },
  {
    name: 'Cornière à ailes inégales',
    description: 'Hauteur : 120 mm Largeur : 80 mm Epaisseur : 12 mm',
    basePrice: null,
    unitPriceExclTax: 3,
    VATRate: null,
    marginPercent: null,
    sellingPrice: 0,
    thickness: 12,
    height: 120,
    width: 80,
    linearWeight: 19.58,
    material: 'Acier',
    productCode: 165,
  },
  {
    name: 'Cornière à ailes inégales',
    description: 'Hauteur : 150 mm Largeur : 90 mm Epaisseur : 11 mm',
    basePrice: null,
    unitPriceExclTax: 3,
    VATRate: null,
    marginPercent: null,
    sellingPrice: 0,
    thickness: 11,
    height: 150,
    width: 90,
    linearWeight: 21.89,
    material: 'Acier',
    productCode: 166,
  },
  {
    name: 'Cornière à ailes inégales',
    description: 'Hauteur : 200 mm Largeur : 100 mm Epaisseur : 14 mm',
    basePrice: null,
    unitPriceExclTax: 3,
    VATRate: null,
    marginPercent: null,
    sellingPrice: 0,
    thickness: 14,
    height: 200,
    width: 100,
    linearWeight: 34.76,
    material: 'Acier',
    productCode: 167,
  },
];

const fer_t_acier = [
  {
    name: 'FER T',
    description: 'Epaisseur : 3 mm Hauteur : 20 mm Largeur : 20 mm',
    basePrice: null,
    unitPriceExclTax: 3,
    VATRate: null,
    marginPercent: null,
    sellingPrice: 0,
    thickness: 3,
    height: 20,
    width: 20,
    linearWeight: 0.97,
    material: 'Acier',
    productCode: 168,
  },
  {
    name: 'FER T',
    description: 'Epaisseur : 4 mm Hauteur : 30 mm Largeur : 30 mm',
    basePrice: null,
    unitPriceExclTax: 3,
    VATRate: null,
    marginPercent: null,
    sellingPrice: 0,
    thickness: 4,
    height: 30,
    width: 30,
    linearWeight: 1.95,
    material: 'Acier',
    productCode: 169,
  },
  {
    name: 'FER T',
    description: 'Epaisseur : 5 mm Hauteur : 40 mm Largeur : 40 mm',
    basePrice: null,
    unitPriceExclTax: 3,
    VATRate: null,
    marginPercent: null,
    sellingPrice: 0,
    thickness: 5,
    height: 40,
    width: 40,
    linearWeight: 3.26,
    material: 'Acier',
    productCode: 170,
  },
  {
    name: 'FER T',
    description: 'Epaisseur : 6 mm Hauteur : 50 mm Largeur : 50 mm',
    basePrice: null,
    unitPriceExclTax: 3,
    VATRate: null,
    marginPercent: null,
    sellingPrice: 0,
    thickness: 6,
    height: 50,
    width: 50,
    linearWeight: 4.88,
    material: 'Acier',
    productCode: 171,
  },
  {
    name: 'FER T',
    description: 'Epaisseur : 7 mm Hauteur : 60 mm Largeur : 60 mm',
    basePrice: null,
    unitPriceExclTax: 3,
    VATRate: null,
    marginPercent: null,
    sellingPrice: 0,
    thickness: 7,
    height: 60,
    width: 60,
    linearWeight: 6.85,
    material: 'Acier',
    productCode: 172,
  },
  {
    name: 'FER T',
    description: 'Epaisseur : 9 mm Hauteur : 80 mm Largeur : 80 mm',
    basePrice: null,
    unitPriceExclTax: 3,
    VATRate: null,
    marginPercent: null,
    sellingPrice: 0,
    thickness: 9,
    height: 80,
    width: 80,
    linearWeight: 11.77,
    material: 'Acier',
    productCode: 173,
  },
  {
    name: 'FER T',
    description: 'Epaisseur : 11 mm Hauteur : 100 mm Largeur : 100 mm',
    basePrice: null,
    unitPriceExclTax: 3,
    VATRate: null,
    marginPercent: null,
    sellingPrice: 0,
    thickness: 11,
    height: 100,
    width: 100,
    linearWeight: 18.04,
    material: 'Acier',
    productCode: 174,
  },
  {
    name: 'FER T',
    description: 'Epaisseur : 13 mm Hauteur : 120 mm Largeur : 120 mm',
    basePrice: null,
    unitPriceExclTax: 7,
    VATRate: null,
    marginPercent: null,
    sellingPrice: 0,
    thickness: 13,
    height: 120,
    width: 120,
    linearWeight: 31.02,
    material: 'Acier',
    productCode: 175,
  },
];

const tube_carre_acier = [
  {
    name: 'Tube carré',
    description: 'Hauteur : 20 mm Epaisseur : 1.5 mm',
    basePrice: null,
    unitPriceExclTax: 3,
    VATRate: null,
    marginPercent: null,
    sellingPrice: 0,
    thickness: 1.5,
    height: 20,
    width: 20,
    linearWeight: 0.96,
    material: 'Acier',
    productCode: 176,
  },
  {
    name: 'Tube carré',
    description: 'Hauteur : 20 mm Epaisseur : 2 mm',
    basePrice: null,
    unitPriceExclTax: 3,
    VATRate: null,
    marginPercent: null,
    sellingPrice: 0,
    thickness: 2,
    height: 20,
    width: 20,
    linearWeight: 1.24,
    material: 'Acier',
    productCode: 177,
  },
  {
    name: 'Tube carré',
    description: 'Hauteur : 25 mm Epaisseur : 1.5 mm',
    basePrice: null,
    unitPriceExclTax: 3,
    VATRate: null,
    marginPercent: null,
    sellingPrice: 0,
    thickness: 1.5,
    height: 25,
    width: 25,
    linearWeight: 1.22,
    material: 'Acier',
    productCode: 178,
  },
  {
    name: 'Tube carré',
    description: 'Hauteur : 25 mm Epaisseur : 2 mm',
    basePrice: null,
    unitPriceExclTax: 3,
    VATRate: null,
    marginPercent: null,
    sellingPrice: 0,
    thickness: 2,
    height: 25,
    width: 25,
    linearWeight: 1.58,
    material: 'Acier',
    productCode: 179,
  },
  {
    name: 'Tube carré',
    description: 'Hauteur : 30 mm Epaisseur : 1.5 mm',
    basePrice: null,
    unitPriceExclTax: 3,
    VATRate: null,
    marginPercent: null,
    sellingPrice: 0,
    thickness: 1.5,
    height: 30,
    width: 30,
    linearWeight: 1.47,
    material: 'Acier',
    productCode: 180,
  },
  {
    name: 'Tube carré',
    description: 'Hauteur : 30 mm Epaisseur : 2 mm',
    basePrice: null,
    unitPriceExclTax: 3,
    VATRate: null,
    marginPercent: null,
    sellingPrice: 0,
    thickness: 2,
    height: 30,
    width: 30,
    linearWeight: 1.94,
    material: 'Acier',
    productCode: 181,
  },
  {
    name: 'Tube carré',
    description: 'Hauteur : 30 mm Epaisseur : 3 mm',
    basePrice: null,
    unitPriceExclTax: 3,
    VATRate: null,
    marginPercent: null,
    sellingPrice: 0,
    thickness: 3,
    height: 30,
    width: 30,
    linearWeight: 2.66,
    material: 'Acier',
    productCode: 182,
  },
  {
    name: 'Tube carré',
    description: 'Hauteur : 35 mm Epaisseur : 2 mm',
    basePrice: null,
    unitPriceExclTax: 3,
    VATRate: null,
    marginPercent: null,
    sellingPrice: 0,
    thickness: 2,
    height: 35,
    width: 35,
    linearWeight: 2.28,
    material: 'Acier',
    productCode: 183,
  },
  {
    name: 'Tube carré',
    description: 'Hauteur : 35 mm Epaisseur : 3 mm',
    basePrice: null,
    unitPriceExclTax: 3,
    VATRate: null,
    marginPercent: null,
    sellingPrice: 0,
    thickness: 3,
    height: 35,
    width: 35,
    linearWeight: 3.31,
    material: 'Acier',
    productCode: 184,
  },
];

const tube_rectangulaire_acier = [
  {
    name: 'Tube rectangulaire',
    description: 'Hauteur : 30 mm Largeur : 20 mm Epaisseur : 2 mm',
    basePrice: null,
    unitPriceExclTax: 3,
    VATRate: null,
    marginPercent: null,
    sellingPrice: 0,
    thickness: 2,
    height: 30,
    width: 20,
    linearWeight: 1.58,
    material: 'Acier',
    productCode: 185,
  },
  {
    name: 'Tube rectangulaire',
    description: 'Hauteur : 35 mm Largeur : 20 mm Epaisseur : 2 mm',
    basePrice: null,
    unitPriceExclTax: 3,
    VATRate: null,
    marginPercent: null,
    sellingPrice: 0,
    thickness: 2,
    height: 35,
    width: 20,
    linearWeight: 1.76,
    material: 'Acier',
    productCode: 186,
  },
  {
    name: 'Tube rectangulaire',
    description: 'Hauteur : 40 mm Largeur : 20 mm Epaisseur : 2 mm',
    basePrice: null,
    unitPriceExclTax: 3,
    VATRate: null,
    marginPercent: null,
    sellingPrice: 0,
    thickness: 2,
    height: 40,
    width: 20,
    linearWeight: 1.94,
    material: 'Acier',
    productCode: 187,
  },
  {
    name: 'Tube rectangulaire',
    description: 'Hauteur : 40 mm Largeur : 27 mm Epaisseur : 2 mm',
    basePrice: null,
    unitPriceExclTax: 3,
    VATRate: null,
    marginPercent: null,
    sellingPrice: 0,
    thickness: 2,
    height: 40,
    width: 27,
    linearWeight: 2.18,
    material: 'Acier',
    productCode: 188,
  },
  {
    name: 'Tube rectangulaire',
    description: 'Hauteur : 50 mm Largeur : 30 mm Epaisseur : 2 mm',
    basePrice: null,
    unitPriceExclTax: 3,
    VATRate: null,
    marginPercent: null,
    sellingPrice: 0,
    thickness: 2,
    height: 50,
    width: 30,
    linearWeight: 2.63,
    material: 'Acier',
    productCode: 189,
  },
  {
    name: 'Tube rectangulaire',
    description: 'Hauteur : 50 mm Largeur : 30 mm Epaisseur : 3 mm',
    basePrice: null,
    unitPriceExclTax: 3,
    VATRate: null,
    marginPercent: null,
    sellingPrice: 0,
    thickness: 3,
    height: 50,
    width: 30,
    linearWeight: 3.81,
    material: 'Acier',
    productCode: 190,
  },
  {
    name: 'Tube rectangulaire',
    description: 'Hauteur : 60 mm Largeur : 30 mm Epaisseur : 2 mm',
    basePrice: null,
    unitPriceExclTax: 3,
    VATRate: null,
    marginPercent: null,
    sellingPrice: 0,
    thickness: 2,
    height: 60,
    width: 30,
    linearWeight: 2.97,
    material: 'Acier',
    productCode: 191,
  },
  {
    name: 'Tube rectangulaire',
    description: 'Hauteur : 60 mm Largeur : 40 mm Epaisseur : 2 mm',
    basePrice: null,
    unitPriceExclTax: 3,
    VATRate: null,
    marginPercent: null,
    sellingPrice: 0,
    thickness: 2,
    height: 60,
    width: 40,
    linearWeight: 3.32,
    material: 'Acier',
    productCode: 192,
  },
  {
    name: 'Tube rectangulaire',
    description: 'Hauteur : 60 mm Largeur : 40 mm Epaisseur : 3 mm',
    basePrice: null,
    unitPriceExclTax: 3,
    VATRate: null,
    marginPercent: null,
    sellingPrice: 0,
    thickness: 3,
    height: 60,
    width: 40,
    linearWeight: 4.84,
    material: 'Acier',
    productCode: 193,
  },
  {
    name: 'Tube rectangulaire',
    description: 'Hauteur : 80 mm Largeur : 40 mm Epaisseur : 2 mm',
    basePrice: null,
    unitPriceExclTax: 3,
    VATRate: null,
    marginPercent: null,
    sellingPrice: 0,
    thickness: 2,
    height: 80,
    width: 40,
    linearWeight: 4,
    material: 'Acier',
    productCode: 194,
  },
  {
    name: 'Tube rectangulaire',
    description: 'Hauteur : 80 mm Largeur : 40 mm Epaisseur : 3 mm',
    basePrice: null,
    unitPriceExclTax: 3,
    VATRate: null,
    marginPercent: null,
    sellingPrice: 0,
    thickness: 3,
    height: 80,
    width: 40,
    linearWeight: 5.87,
    material: 'Acier',
    productCode: 195,
  },
  {
    name: 'Tube rectangulaire',
    description: 'Hauteur : 80 mm Largeur : 40 mm Epaisseur : 4 mm',
    basePrice: null,
    unitPriceExclTax: 6,
    VATRate: null,
    marginPercent: null,
    sellingPrice: 0,
    thickness: 4,
    height: 80,
    width: 40,
    linearWeight: 7.66,
    material: 'Acier',
    productCode: 196,
  },
  {
    name: 'Tube rectangulaire',
    description: 'Hauteur : 80 mm Largeur : 40 mm Epaisseur : 5 mm',
    basePrice: null,
    unitPriceExclTax: 6,
    VATRate: null,
    marginPercent: null,
    sellingPrice: 0,
    thickness: 5,
    height: 80,
    width: 40,
    linearWeight: 8.94,
    material: 'Acier',
    productCode: 197,
  },
];

//Galva

const cornieres_ailes_egales_galva = [
  {
    name: 'Cornière à ailes égales',
    description: 'Epaisseur : 3 mm Hauteur Ailes : 30 mm',
    basePrice: null,
    unitPriceExclTax: 6,
    VATRate: null,
    marginPercent: null,
    sellingPrice: 0,
    linearWeight: 1.5,
    thickness: 3,
    height: 30,
    width: null,
    diameter: null,
    circumference: null,
    sectionArea: 1.74,
    weight: null,
    material: 'Galvanisé',
    productCode: 197,
  },
  {
    name: 'Cornière à ailes égales',
    description: 'Epaisseur : 3.5 mm Hauteur Ailes : 35 mm',
    basePrice: null,
    unitPriceExclTax: 6,
    VATRate: null,
    marginPercent: null,
    sellingPrice: 0,
    linearWeight: 2.04,
    thickness: 3.5,
    height: 35,
    width: null,
    diameter: null,
    circumference: null,
    sectionArea: 2.35,
    weight: null,
    material: 'Galvanisé',
    productCode: 198,
  },
  {
    name: 'Cornière à ailes égales',
    description: 'Epaisseur : 4 mm Hauteur Ailes : 40 mm',
    basePrice: null,
    unitPriceExclTax: 6,
    VATRate: null,
    marginPercent: null,
    sellingPrice: 0,
    linearWeight: 2.66,
    thickness: 4,
    height: 40,
    width: null,
    diameter: null,
    circumference: null,
    sectionArea: 3.08,
    weight: null,
    material: 'Galvanisé',
    productCode: 199,
  },
  {
    name: 'Cornière à ailes égales',
    description: 'Epaisseur : 5 mm Hauteur Ailes : 50 mm',
    basePrice: null,
    unitPriceExclTax: 6,
    VATRate: null,
    marginPercent: null,
    sellingPrice: 0,
    linearWeight: 4.15,
    thickness: 5,
    height: 50,
    width: null,
    diameter: null,
    circumference: null,
    sectionArea: 4.8,
    weight: null,
    material: 'Galvanisé',
    productCode: 200,
  },
];

const tubes_ronds_galva = [
  {
    name: 'Tube rond SENDZINIR NF EN 10305-3 S4',
    description: 'Diamètre extérieur : 21.3 mm Epaisseur : 2.3 mm',
    basePrice: null,
    unitPriceExclTax: 6,
    VATRate: null,
    marginPercent: null,
    sellingPrice: 0,
    linearWeight: 1.18,
    thickness: 2.3,
    height: null,
    width: null,
    diameter: 21.3,
    circumference: null,
    sectionArea: null,
    weight: null,
    material: 'Galvanisé',
    productCode: 201,
  },
  {
    name: 'Tube rond SENDZINIR NF EN 10305-3 S4',
    description: 'Diamètre extérieur : 26.9 mm Epaisseur : 2.3 mm',
    basePrice: null,
    unitPriceExclTax: 6,
    VATRate: null,
    marginPercent: null,
    sellingPrice: 0,
    linearWeight: 1.54,
    thickness: 2.3,
    height: null,
    width: null,
    diameter: 26.9,
    circumference: null,
    sectionArea: null,
    weight: null,
    material: 'Galvanisé',
    productCode: 202,
  },
  {
    name: 'Tube rond SENDZINIR NF EN 10305-3 S4',
    description: 'Diamètre extérieur : 30 mm Epaisseur : 1.5 mm',
    basePrice: null,
    unitPriceExclTax: 6,
    VATRate: null,
    marginPercent: null,
    sellingPrice: 0,
    linearWeight: 1.28,
    thickness: 1.5,
    height: null,
    width: null,
    diameter: 30,
    circumference: null,
    sectionArea: null,
    weight: null,
    material: 'Galvanisé',
    productCode: 203,
  },
  {
    name: 'Tube rond SENDZINIR NF EN 10305-3 S4',
    description: 'Diamètre extérieur : 33.7 mm Epaisseur : 2.9 mm',
    basePrice: null,
    unitPriceExclTax: 6,
    VATRate: null,
    marginPercent: null,
    sellingPrice: 0,
    linearWeight: 2.42,
    thickness: 2.9,
    height: null,
    width: null,
    diameter: 33.7,
    circumference: null,
    sectionArea: null,
    weight: null,
    material: 'Galvanisé',
    productCode: 204,
  },
  {
    name: 'Tube rond SENDZINIR NF EN 10305-3 S4',
    description: 'Diamètre extérieur : 40 mm Epaisseur : 1.5 mm',
    basePrice: null,
    unitPriceExclTax: 6,
    VATRate: null,
    marginPercent: null,
    sellingPrice: 0,
    linearWeight: 1.72,
    thickness: 1.5,
    height: null,
    width: null,
    diameter: 40,
    circumference: null,
    sectionArea: null,
    weight: null,
    material: 'Galvanisé',
    productCode: 205,
  },
  {
    name: 'Tube rond SENDZINIR NF EN 10305-3 S4',
    description: 'Diamètre extérieur : 42.4 mm Epaisseur : 2.9 mm',
    basePrice: null,
    unitPriceExclTax: 6,
    VATRate: null,
    marginPercent: null,
    sellingPrice: 0,
    linearWeight: 3.1,
    thickness: 2.9,
    height: null,
    width: null,
    diameter: 42.4,
    circumference: null,
    sectionArea: null,
    weight: null,
    material: 'Galvanisé',
    productCode: 206,
  },
  {
    name: 'Tube rond SENDZINIR NF EN 10305-3 S4',
    description: 'Diamètre extérieur : 48.3 mm Epaisseur : 2.9 mm',
    basePrice: null,
    unitPriceExclTax: 6,
    VATRate: null,
    marginPercent: null,
    sellingPrice: 0,
    linearWeight: 3.58,
    thickness: 2.9,
    height: null,
    width: null,
    diameter: 48.3,
    circumference: null,
    sectionArea: null,
    weight: null,
    material: 'Galvanisé',
    productCode: 207,
  },
  {
    name: 'Tube rond SENDZINIR NF EN 10305-3 S4',
    description: 'Diamètre extérieur : 50 mm Epaisseur : 1.5 mm',
    basePrice: null,
    unitPriceExclTax: 6,
    VATRate: null,
    marginPercent: null,
    sellingPrice: 0,
    linearWeight: 2.16,
    thickness: 1.5,
    height: null,
    width: null,
    diameter: 50,
    circumference: null,
    sectionArea: null,
    weight: null,
    material: 'Galvanisé',
    productCode: 208,
  },
  {
    name: 'Tube rond SENDZINIR NF EN 10305-3 S4',
    description: 'Diamètre extérieur : 50 mm Epaisseur : 2 mm',
    basePrice: null,
    unitPriceExclTax: 6,
    VATRate: null,
    marginPercent: null,
    sellingPrice: 0,
    linearWeight: 2.61,
    thickness: 2,
    height: null,
    width: null,
    diameter: 50,
    circumference: null,
    sectionArea: null,
    weight: null,
    material: 'Galvanisé',
    productCode: 209,
  },
  {
    name: 'Tube rond SENDZINIR NF EN 10305-3 S4',
    description: 'Diamètre extérieur : 60 mm Epaisseur : 1.5 mm',
    basePrice: null,
    unitPriceExclTax: 6,
    VATRate: null,
    marginPercent: null,
    sellingPrice: 0,
    linearWeight: 2.6,
    thickness: 1.5,
    height: null,
    width: null,
    diameter: 60,
    circumference: null,
    sectionArea: null,
    weight: null,
    material: 'Galvanisé',
    productCode: 210,
  },
  {
    name: 'Tube rond SENDZINIR NF EN 10305-3 S4',
    description: 'Diamètre extérieur : 60 mm Epaisseur : 2 mm',
    basePrice: null,
    unitPriceExclTax: 6,
    VATRate: null,
    marginPercent: null,
    sellingPrice: 0,
    linearWeight: 3.45,
    thickness: 2,
    height: null,
    width: null,
    diameter: 60,
    circumference: null,
    sectionArea: null,
    weight: null,
    material: 'Galvanisé',
    productCode: 211,
  },
];

const tube_carre_galva = [
  {
    name: 'Tube carré SENDZINIR NF EN 10305-3 S4',
    description: 'Hauteur : 20 mm Epaisseur : 1.5 mm',
    basePrice: null,
    unitPriceExclTax: 6,
    VATRate: null,
    marginPercent: null,
    sellingPrice: 0,
    linearWeight: 0.96,
    thickness: 1.5,
    height: 20,
    width: 20,
    diameter: null,
    circumference: null,
    sectionArea: null,
    weight: null,
    material: 'Galvanisé',
    productCode: 212,
  },
  {
    name: 'Tube carré SENDZINIR NF EN 10305-3 S4',
    description: 'Hauteur : 25 mm Epaisseur : 1.5 mm',
    basePrice: null,
    unitPriceExclTax: 6,
    VATRate: null,
    marginPercent: null,
    sellingPrice: 0,
    linearWeight: 1.22,
    thickness: 1.5,
    height: 25,
    width: 25,
    diameter: null,
    circumference: null,
    sectionArea: null,
    weight: null,
    material: 'Galvanisé',
    productCode: 213,
  },
  {
    name: 'Tube carré SENDZINIR NF EN 10305-3 S4',
    description: 'Hauteur : 25 mm Epaisseur : 2 mm',
    basePrice: null,
    unitPriceExclTax: 6,
    VATRate: null,
    marginPercent: null,
    sellingPrice: 0,
    linearWeight: 1.58,
    thickness: 2,
    height: 25,
    width: 25,
    diameter: null,
    circumference: null,
    sectionArea: null,
    weight: null,
    material: 'Galvanisé',
    productCode: 214,
  },
  {
    name: 'Tube carré SENDZINIR NF EN 10305-3 S4',
    description: 'Hauteur : 30 mm Epaisseur : 2 mm',
    basePrice: null,
    unitPriceExclTax: 6,
    VATRate: null,
    marginPercent: null,
    sellingPrice: 0,
    linearWeight: 1.94,
    thickness: 2,
    height: 30,
    width: 30,
    diameter: null,
    circumference: null,
    sectionArea: null,
    weight: null,
    material: 'Galvanisé',
    productCode: 215,
  },
  {
    name: 'Tube carré SENDZINIR NF EN 10305-3 S4',
    description: 'Hauteur : 35 mm Epaisseur : 2 mm',
    basePrice: null,
    unitPriceExclTax: 6,
    VATRate: null,
    marginPercent: null,
    sellingPrice: 0,
    linearWeight: 2.28,
    thickness: 2,
    height: 35,
    width: 35,
    diameter: null,
    circumference: null,
    sectionArea: null,
    weight: null,
    material: 'Galvanisé',
    productCode: 216,
  },
  {
    name: 'Tube carré SENDZINIR NF EN 10305-3 S4',
    description: 'Hauteur : 40 mm Epaisseur : 2 mm',
    basePrice: null,
    unitPriceExclTax: 6,
    VATRate: null,
    marginPercent: null,
    sellingPrice: 0,
    linearWeight: 2.63,
    thickness: 2,
    height: 40,
    width: 40,
    diameter: null,
    circumference: null,
    sectionArea: null,
    weight: null,
    material: 'Galvanisé',
    productCode: 217,
  },
  {
    name: 'Tube carré SENDZINIR NF EN 10305-3 S4',
    description: 'Hauteur : 50 mm Epaisseur : 2 mm',
    basePrice: null,
    unitPriceExclTax: 6,
    VATRate: null,
    marginPercent: null,
    sellingPrice: 0,
    linearWeight: 3.32,
    thickness: 2,
    height: 50,
    width: 50,
    diameter: null,
    circumference: null,
    sectionArea: null,
    weight: null,
    material: 'Galvanisé',
    productCode: 218,
  },
  {
    name: 'Tube carré SENDZINIR NF EN 10305-3 S4',
    description: 'Hauteur : 60 mm Epaisseur : 2 mm',
    basePrice: null,
    unitPriceExclTax: 6,
    VATRate: null,
    marginPercent: null,
    sellingPrice: 0,
    linearWeight: 3.95,
    thickness: 2,
    height: 60,
    width: 60,
    diameter: null,
    circumference: null,
    sectionArea: null,
    weight: null,
    material: 'Galvanisé',
    productCode: 219,
  },
  {
    name: 'Tube carré SENDZINIR NF EN 10305-3 S4',
    description: 'Hauteur : 80 mm Epaisseur : 2 mm',
    basePrice: null,
    unitPriceExclTax: 6,
    VATRate: null,
    marginPercent: null,
    sellingPrice: 0,
    linearWeight: 5.39,
    thickness: 2,
    height: 80,
    width: 80,
    diameter: null,
    circumference: null,
    sectionArea: null,
    weight: null,
    material: 'Galvanisé',
    productCode: 220,
  },
  {
    name: 'Tube carré SENDZINIR NF EN 10305-3 S4',
    description: 'Hauteur : 100 mm Epaisseur : 2 mm',
    basePrice: null,
    unitPriceExclTax: 6,
    VATRate: null,
    marginPercent: null,
    sellingPrice: 0,
    linearWeight: 7.45,
    thickness: 2,
    height: 100,
    width: 100,
    diameter: null,
    circumference: null,
    sectionArea: null,
    weight: null,
    material: 'Galvanisé',
    productCode: 221,
  },
  {
    name: 'Tube carré SENDZINIR NF EN 10305-3 S4',
    description: 'Hauteur : 100 mm Epaisseur : 3 mm',
    basePrice: null,
    unitPriceExclTax: 6,
    VATRate: null,
    marginPercent: null,
    sellingPrice: 0,
    linearWeight: 9.92,
    thickness: 3,
    height: 100,
    width: 100,
    diameter: null,
    circumference: null,
    sectionArea: null,
    weight: null,
    material: 'Galvanisé',
    productCode: 222,
  },
];
const tube_rectangulaire_galva = [
  {
    name: 'Tube rectangulaire SENDZINIR NF EN 10305-3 S4',
    description: 'Hauteur : 35 mm Largeur : 20 mm Epaisseur : 2 mm',
    basePrice: null,
    unitPriceExclTax: 6,
    VATRate: null,
    marginPercent: null,
    sellingPrice: 0,
    linearWeight: 1.76,
    thickness: 2,
    height: 35,
    width: 20,
    diameter: null,
    circumference: null,
    sectionArea: null,
    weight: null,
    material: 'Galvanisé',
    productCode: 223,
  },
  {
    name: 'Tube rectangulaire SENDZINIR NF EN 10305-3 S4',
    description: 'Hauteur : 40 mm Largeur : 20 mm Epaisseur : 2 mm',
    basePrice: null,
    unitPriceExclTax: 6,
    VATRate: null,
    marginPercent: null,
    sellingPrice: 0,
    linearWeight: 1.94,
    thickness: 2,
    height: 40,
    width: 20,
    diameter: null,
    circumference: null,
    sectionArea: null,
    weight: null,
    material: 'Galvanisé',
    productCode: 224,
  },
  {
    name: 'Tube rectangulaire SENDZINIR NF EN 10305-3 S4',
    description: 'Hauteur : 40 mm Largeur : 27 mm Epaisseur : 2 mm',
    basePrice: null,
    unitPriceExclTax: 6,
    VATRate: null,
    marginPercent: null,
    sellingPrice: 0,
    linearWeight: 2.18,
    thickness: 2,
    height: 40,
    width: 27,
    diameter: null,
    circumference: null,
    sectionArea: null,
    weight: null,
    material: 'Galvanisé',
    productCode: 225,
  },
  {
    name: 'Tube rectangulaire SENDZINIR NF EN 10305-3 S4',
    description: 'Hauteur : 50 mm Largeur : 30 mm Epaisseur : 2 mm',
    basePrice: null,
    unitPriceExclTax: 6,
    VATRate: null,
    marginPercent: null,
    sellingPrice: 0,
    linearWeight: 2.63,
    thickness: 2,
    height: 50,
    width: 30,
    diameter: null,
    circumference: null,
    sectionArea: null,
    weight: null,
    material: 'Galvanisé',
    productCode: 226,
  },
  {
    name: 'Tube rectangulaire SENDZINIR NF EN 10305-3 S4',
    description: 'Hauteur : 60 mm Largeur : 30 mm Epaisseur : 2 mm',
    basePrice: null,
    unitPriceExclTax: 6,
    VATRate: null,
    marginPercent: null,
    sellingPrice: 0,
    linearWeight: 2.97,
    thickness: 2,
    height: 60,
    width: 30,
    diameter: null,
    circumference: null,
    sectionArea: null,
    weight: null,
    material: 'Galvanisé',
    productCode: 227,
  },
  {
    name: 'Tube rectangulaire SENDZINIR NF EN 10305-3 S4',
    description: 'Hauteur : 60 mm Largeur : 40 mm Epaisseur : 2 mm',
    basePrice: null,
    unitPriceExclTax: 6,
    VATRate: null,
    marginPercent: null,
    sellingPrice: 0,
    linearWeight: 3.32,
    thickness: 2,
    height: 60,
    width: 40,
    diameter: null,
    circumference: null,
    sectionArea: null,
    weight: null,
    material: 'Galvanisé',
    productCode: 228,
  },
  {
    name: 'Tube rectangulaire SENDZINIR NF EN 10305-3 S4',
    description: 'Hauteur : 80 mm Largeur : 40 mm Epaisseur : 2 mm',
    basePrice: null,
    unitPriceExclTax: 6,
    VATRate: null,
    marginPercent: null,
    sellingPrice: 0,
    linearWeight: 4,
    thickness: 2,
    height: 80,
    width: 40,
    diameter: null,
    circumference: null,
    sectionArea: null,
    weight: null,
    material: 'Galvanisé',
    productCode: 229,
  },
  {
    name: 'Tube rectangulaire SENDZINIR NF EN 10305-3 S4',
    description: 'Hauteur : 100 mm Largeur : 20 mm Epaisseur : 2 mm',
    basePrice: null,
    unitPriceExclTax: 6,
    VATRate: null,
    marginPercent: null,
    sellingPrice: 0,
    linearWeight: 4.31,
    thickness: 2,
    height: 100,
    width: 20,
    diameter: null,
    circumference: null,
    sectionArea: null,
    weight: null,
    material: 'Galvanisé',
    productCode: 230,
  },
  {
    name: 'Tube rectangulaire SENDZINIR NF EN 10305-3 S4',
    description: 'Hauteur : 100 mm Largeur : 50 mm Epaisseur : 2 mm',
    basePrice: null,
    unitPriceExclTax: 6,
    VATRate: null,
    marginPercent: null,
    sellingPrice: 0,
    linearWeight: 4.9,
    thickness: 2,
    height: 100,
    width: 50,
    diameter: null,
    circumference: null,
    sectionArea: null,
    weight: null,
    material: 'Galvanisé',
    productCode: 231,
  },
];

const tolle_perforee_galva = [
  {
    name: 'Tôle perforée',
    description: 'Épaisseur : 1.5 mm Trous ronds diamètre 10 mm',
    basePrice: null,
    unitPriceExclTax: 8.5,
    VATRate: null,
    marginPercent: null,
    sellingPrice: 0,
    linearWeight: 12.98,
    thickness: 1.5,
    height: null,
    width: null,
    diameter: null,
    circumference: null,
    sectionArea: null,
    weight: 12.98,
    material: 'Galvanisé',
    productCode: 232,
  },
  {
    name: 'Tôle perforée',
    description: 'Épaisseur : 2 mm Trous ronds diamètre 5 mm',
    basePrice: null,
    unitPriceExclTax: 8.5,
    VATRate: null,
    marginPercent: null,
    sellingPrice: 0,
    linearWeight: 17.27,
    thickness: 2,
    height: null,
    width: null,
    diameter: null,
    circumference: null,
    sectionArea: null,
    weight: 17.27,
    material: 'Galvanisé',
    productCode: 233,
  },
  {
    name: 'Tôle perforée',
    description: 'Épaisseur : 1.5 mm Trous carré 10/10 mm',
    basePrice: null,
    unitPriceExclTax: 8.5,
    VATRate: null,
    marginPercent: null,
    sellingPrice: 0,
    linearWeight: 12.98,
    thickness: 1.5,
    height: null,
    width: null,
    diameter: null,
    circumference: null,
    sectionArea: null,
    weight: 12.98,
    material: 'Galvanisé',
    productCode: 234,
  },
];
//fer_t_aluminium, corniere_egale_aluminium,tube_rectangulaire_aluminium,tube_carré_aluminium,barre_carree_plein_aluminium,corniere_ailes_égales_inox ,fer_T_inox,tube_rond_inox,cornieres_ailes_egales_acier,cornieres_ailes_inegales_acier,fer_t_acier,tube_carre_acier,tube_rectangulaire_acier,cornieres_ailes_egales_galva,tubes_ronds_galva,tube_carre_galva,tube_rectangulaire_galva,tolle_perforee_galva

// Ceux qui
